// Code generated by connector-gen. DO NOT EDIT.

package googleads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// ListAccessibleCustomersRequest holds the parameters for ListAccessibleCustomers.
type ListAccessibleCustomersRequest struct {
}

// ListAccessibleCustomers calls GET /{version}/customers:listAccessibleCustomers.
func (c *Client) ListAccessibleCustomers(ctx context.Context, req *ListAccessibleCustomersRequest) (*ListAccessibleCustomersResponse, error) {
	if req == nil {
		req = &ListAccessibleCustomersRequest{}
	}
	out := &ListAccessibleCustomersResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/customers:listAccessibleCustomers",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
