// Code generated by connector-gen. DO NOT EDIT.

package googleads

import (
	"context"
	"encoding/json"
	"github.com/pax-beehive/connector"
)

var connectorActionManifest = [...]connector.ActionDescriptor{
	{
		Provider:      "googleads",
		Method:        "ListAccessibleCustomers",
		HTTPMethod:    "GET",
		RequestType:   "ListAccessibleCustomersRequest",
		ResponseType:  "ListAccessibleCustomersResponse",
		RequiredScope: "actions:googleads:ListAccessibleCustomers",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "googleads",
		Method:        "MutateAdGroupAds",
		HTTPMethod:    "POST",
		RequestType:   "MutateAdGroupAdsRequest",
		ResponseType:  "MutateAdGroupAdsResponse",
		RequiredScope: "actions:googleads:MutateAdGroupAds",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "MutateAdGroupCriteria",
		HTTPMethod:    "POST",
		RequestType:   "MutateAdGroupCriteriaRequest",
		ResponseType:  "MutateAdGroupCriteriaResponse",
		RequiredScope: "actions:googleads:MutateAdGroupCriteria",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "MutateAdGroups",
		HTTPMethod:    "POST",
		RequestType:   "MutateAdGroupsRequest",
		ResponseType:  "MutateAdGroupsResponse",
		RequiredScope: "actions:googleads:MutateAdGroups",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "MutateCampaignBudgets",
		HTTPMethod:    "POST",
		RequestType:   "MutateCampaignBudgetsRequest",
		ResponseType:  "MutateCampaignBudgetsResponse",
		RequiredScope: "actions:googleads:MutateCampaignBudgets",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "MutateCampaigns",
		HTTPMethod:    "POST",
		RequestType:   "MutateCampaignsRequest",
		ResponseType:  "MutateCampaignsResponse",
		RequiredScope: "actions:googleads:MutateCampaigns",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "SearchGoogleAds",
		HTTPMethod:    "POST",
		RequestType:   "SearchGoogleAdsRequest",
		ResponseType:  "SearchGoogleAdsResponse",
		RequiredScope: "actions:googleads:SearchGoogleAds",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "googleads",
		Method:        "SearchGoogleAdsStream",
		HTTPMethod:    "POST",
		RequestType:   "SearchGoogleAdsStreamRequest",
		ResponseType:  "SearchGoogleAdsStreamResponse",
		RequiredScope: "actions:googleads:SearchGoogleAdsStream",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
	"ListAccessibleCustomers": invokeListAccessibleCustomersAction,
	"MutateAdGroupAds":        invokeMutateAdGroupAdsAction,
	"MutateAdGroupCriteria":   invokeMutateAdGroupCriteriaAction,
	"MutateAdGroups":          invokeMutateAdGroupsAction,
	"MutateCampaignBudgets":   invokeMutateCampaignBudgetsAction,
	"MutateCampaigns":         invokeMutateCampaignsAction,
	"SearchGoogleAds":         invokeSearchGoogleAdsAction,
	"SearchGoogleAdsStream":   invokeSearchGoogleAdsStreamAction,
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "googleads" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}

func invokeListAccessibleCustomersAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
	}
	if err := connector.DecodeActionRequest("googleads", "ListAccessibleCustomers", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAccessibleCustomers(ctx, &ListAccessibleCustomersRequest{})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeMutateAdGroupAdsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId     string               `json:"customerId,omitempty"`
		Operations     []AdGroupAdOperation `json:"operations,omitempty"`
		PartialFailure *bool                `json:"partialFailure,omitempty"`
		ValidateOnly   *bool                `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "MutateAdGroupAds", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.MutateAdGroupAds(ctx, &MutateAdGroupAdsRequest{
		CustomerId:     wire.CustomerId,
		Operations:     wire.Operations,
		PartialFailure: wire.PartialFailure,
		ValidateOnly:   wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeMutateAdGroupCriteriaAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId     string                      `json:"customerId,omitempty"`
		Operations     []AdGroupCriterionOperation `json:"operations,omitempty"`
		PartialFailure *bool                       `json:"partialFailure,omitempty"`
		ValidateOnly   *bool                       `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "MutateAdGroupCriteria", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.MutateAdGroupCriteria(ctx, &MutateAdGroupCriteriaRequest{
		CustomerId:     wire.CustomerId,
		Operations:     wire.Operations,
		PartialFailure: wire.PartialFailure,
		ValidateOnly:   wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeMutateAdGroupsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId     string             `json:"customerId,omitempty"`
		Operations     []AdGroupOperation `json:"operations,omitempty"`
		PartialFailure *bool              `json:"partialFailure,omitempty"`
		ValidateOnly   *bool              `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "MutateAdGroups", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.MutateAdGroups(ctx, &MutateAdGroupsRequest{
		CustomerId:     wire.CustomerId,
		Operations:     wire.Operations,
		PartialFailure: wire.PartialFailure,
		ValidateOnly:   wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeMutateCampaignBudgetsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId     string                    `json:"customerId,omitempty"`
		Operations     []CampaignBudgetOperation `json:"operations,omitempty"`
		PartialFailure *bool                     `json:"partialFailure,omitempty"`
		ValidateOnly   *bool                     `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "MutateCampaignBudgets", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.MutateCampaignBudgets(ctx, &MutateCampaignBudgetsRequest{
		CustomerId:     wire.CustomerId,
		Operations:     wire.Operations,
		PartialFailure: wire.PartialFailure,
		ValidateOnly:   wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeMutateCampaignsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId     string              `json:"customerId,omitempty"`
		Operations     []CampaignOperation `json:"operations,omitempty"`
		PartialFailure *bool               `json:"partialFailure,omitempty"`
		ValidateOnly   *bool               `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "MutateCampaigns", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.MutateCampaigns(ctx, &MutateCampaignsRequest{
		CustomerId:     wire.CustomerId,
		Operations:     wire.Operations,
		PartialFailure: wire.PartialFailure,
		ValidateOnly:   wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeSearchGoogleAdsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId   string  `json:"customerId,omitempty"`
		PageSize     *int    `json:"pageSize,omitempty"`
		PageToken    *string `json:"pageToken,omitempty"`
		Query        *string `json:"query,omitempty"`
		ValidateOnly *bool   `json:"validateOnly,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "SearchGoogleAds", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.SearchGoogleAds(ctx, &SearchGoogleAdsRequest{
		CustomerId:   wire.CustomerId,
		PageSize:     wire.PageSize,
		PageToken:    wire.PageToken,
		Query:        wire.Query,
		ValidateOnly: wire.ValidateOnly,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeSearchGoogleAdsStreamAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomerId        string  `json:"customerId,omitempty"`
		Query             *string `json:"query,omitempty"`
		SummaryRowSetting *string `json:"summaryRowSetting,omitempty"`
	}
	if err := connector.DecodeActionRequest("googleads", "SearchGoogleAdsStream", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.SearchGoogleAdsStream(ctx, &SearchGoogleAdsStreamRequest{
		CustomerId:        wire.CustomerId,
		Query:             wire.Query,
		SummaryRowSetting: wire.SummaryRowSetting,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
