// Code generated by connector-gen. DO NOT EDIT.

package googleads

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
	{
		name:   "ListAccessibleCustomers",
		method: "GET",
		path:   "/v23/customers:listAccessibleCustomers",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAccessibleCustomers(ctx, &ListAccessibleCustomersRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAccessibleCustomers(ctx, nil)
		},
	},
	{
		name:   "MutateAdGroupAds",
		method: "POST",
		path:   "/v23/customers//adGroupAds:mutate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroupAds(ctx, &MutateAdGroupAdsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroupAds(ctx, nil)
		},
	},
	{
		name:   "MutateAdGroupCriteria",
		method: "POST",
		path:   "/v23/customers//adGroupCriteria:mutate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroupCriteria(ctx, &MutateAdGroupCriteriaRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroupCriteria(ctx, nil)
		},
	},
	{
		name:   "MutateAdGroups",
		method: "POST",
		path:   "/v23/customers//adGroups:mutate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroups(ctx, &MutateAdGroupsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateAdGroups(ctx, nil)
		},
	},
	{
		name:   "MutateCampaignBudgets",
		method: "POST",
		path:   "/v23/customers//campaignBudgets:mutate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateCampaignBudgets(ctx, &MutateCampaignBudgetsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateCampaignBudgets(ctx, nil)
		},
	},
	{
		name:   "MutateCampaigns",
		method: "POST",
		path:   "/v23/customers//campaigns:mutate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateCampaigns(ctx, &MutateCampaignsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.MutateCampaigns(ctx, nil)
		},
	},
	{
		name:   "SearchGoogleAds",
		method: "POST",
		path:   "/v23/customers//googleAds:search",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchGoogleAds(ctx, &SearchGoogleAdsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchGoogleAds(ctx, nil)
		},
	},
	{
		name:   "SearchGoogleAdsStream",
		method: "POST",
		path:   "/v23/customers//googleAds:searchStream",
		resp:   "[]",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchGoogleAdsStream(ctx, &SearchGoogleAdsStreamRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchGoogleAdsStream(ctx, nil)
		},
	},
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{DeveloperToken: "d", AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{DeveloperToken: "d", AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
