// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"encoding/json"
	"github.com/pax-beehive/connector"
)

var connectorActionManifest = [...]connector.ActionDescriptor{
	{
		Provider:      "openaiads",
		Method:        "ActivateAdAccount",
		HTTPMethod:    "POST",
		RequestType:   "ActivateAdAccountRequest",
		ResponseType:  "ActivateAdAccountResponse",
		RequiredScope: "actions:openaiads:ActivateAdAccount",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAdAccount",
		HTTPMethod:    "GET",
		RequestType:   "GetAdAccountRequest",
		ResponseType:  "GetAdAccountResponse",
		RequiredScope: "actions:openaiads:GetAdAccount",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAdAccountInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetAdAccountInsightsRequest",
		ResponseType:  "GetAdAccountInsightsResponse",
		RequiredScope: "actions:openaiads:GetAdAccountInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "PauseAdAccount",
		HTTPMethod:    "POST",
		RequestType:   "PauseAdAccountRequest",
		ResponseType:  "PauseAdAccountResponse",
		RequiredScope: "actions:openaiads:PauseAdAccount",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "UpdateAdAccount",
		HTTPMethod:    "POST",
		RequestType:   "UpdateAdAccountRequest",
		ResponseType:  "UpdateAdAccountResponse",
		RequiredScope: "actions:openaiads:UpdateAdAccount",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ActivateAdGroup",
		HTTPMethod:    "POST",
		RequestType:   "ActivateAdGroupRequest",
		ResponseType:  "ActivateAdGroupResponse",
		RequiredScope: "actions:openaiads:ActivateAdGroup",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ArchiveAdGroup",
		HTTPMethod:    "POST",
		RequestType:   "ArchiveAdGroupRequest",
		ResponseType:  "ArchiveAdGroupResponse",
		RequiredScope: "actions:openaiads:ArchiveAdGroup",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateAdGroup",
		HTTPMethod:    "POST",
		RequestType:   "CreateAdGroupRequest",
		ResponseType:  "CreateAdGroupResponse",
		RequiredScope: "actions:openaiads:CreateAdGroup",
		Idempotency:   connector.ActionIdempotency("provider-key"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAdGroup",
		HTTPMethod:    "GET",
		RequestType:   "GetAdGroupRequest",
		ResponseType:  "GetAdGroupResponse",
		RequiredScope: "actions:openaiads:GetAdGroup",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAdGroupInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetAdGroupInsightsRequest",
		ResponseType:  "GetAdGroupInsightsResponse",
		RequiredScope: "actions:openaiads:GetAdGroupInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ListAdGroups",
		HTTPMethod:    "GET",
		RequestType:   "ListAdGroupsRequest",
		ResponseType:  "ListAdGroupsResponse",
		RequiredScope: "actions:openaiads:ListAdGroups",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "PauseAdGroup",
		HTTPMethod:    "POST",
		RequestType:   "PauseAdGroupRequest",
		ResponseType:  "PauseAdGroupResponse",
		RequiredScope: "actions:openaiads:PauseAdGroup",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "UpdateAdGroup",
		HTTPMethod:    "POST",
		RequestType:   "UpdateAdGroupRequest",
		ResponseType:  "UpdateAdGroupResponse",
		RequiredScope: "actions:openaiads:UpdateAdGroup",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ActivateAd",
		HTTPMethod:    "POST",
		RequestType:   "ActivateAdRequest",
		ResponseType:  "ActivateAdResponse",
		RequiredScope: "actions:openaiads:ActivateAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ArchiveAd",
		HTTPMethod:    "POST",
		RequestType:   "ArchiveAdRequest",
		ResponseType:  "ArchiveAdResponse",
		RequiredScope: "actions:openaiads:ArchiveAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateAd",
		HTTPMethod:    "POST",
		RequestType:   "CreateAdRequest",
		ResponseType:  "CreateAdResponse",
		RequiredScope: "actions:openaiads:CreateAd",
		Idempotency:   connector.ActionIdempotency("provider-key"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAd",
		HTTPMethod:    "GET",
		RequestType:   "GetAdRequest",
		ResponseType:  "GetAdResponse",
		RequiredScope: "actions:openaiads:GetAd",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetAdInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetAdInsightsRequest",
		ResponseType:  "GetAdInsightsResponse",
		RequiredScope: "actions:openaiads:GetAdInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ListAds",
		HTTPMethod:    "GET",
		RequestType:   "ListAdsRequest",
		ResponseType:  "ListAdsResponse",
		RequiredScope: "actions:openaiads:ListAds",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "PauseAd",
		HTTPMethod:    "POST",
		RequestType:   "PauseAdRequest",
		ResponseType:  "PauseAdResponse",
		RequiredScope: "actions:openaiads:PauseAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "UpdateAd",
		HTTPMethod:    "POST",
		RequestType:   "UpdateAdRequest",
		ResponseType:  "UpdateAdResponse",
		RequiredScope: "actions:openaiads:UpdateAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ArchiveCustomAudience",
		HTTPMethod:    "POST",
		RequestType:   "ArchiveCustomAudienceRequest",
		ResponseType:  "ArchiveCustomAudienceResponse",
		RequiredScope: "actions:openaiads:ArchiveCustomAudience",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateCustomAudience",
		HTTPMethod:    "POST",
		RequestType:   "CreateCustomAudienceRequest",
		ResponseType:  "CreateCustomAudienceResponse",
		RequiredScope: "actions:openaiads:CreateCustomAudience",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateCustomAudienceUpload",
		HTTPMethod:    "POST",
		RequestType:   "CreateCustomAudienceUploadRequest",
		ResponseType:  "CreateCustomAudienceUploadResponse",
		RequiredScope: "actions:openaiads:CreateCustomAudienceUpload",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetCustomAudience",
		HTTPMethod:    "GET",
		RequestType:   "GetCustomAudienceRequest",
		ResponseType:  "GetCustomAudienceResponse",
		RequiredScope: "actions:openaiads:GetCustomAudience",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ListCustomAudiences",
		HTTPMethod:    "GET",
		RequestType:   "ListCustomAudiencesRequest",
		ResponseType:  "ListCustomAudiencesResponse",
		RequiredScope: "actions:openaiads:ListCustomAudiences",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ActivateCampaign",
		HTTPMethod:    "POST",
		RequestType:   "ActivateCampaignRequest",
		ResponseType:  "ActivateCampaignResponse",
		RequiredScope: "actions:openaiads:ActivateCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ArchiveCampaign",
		HTTPMethod:    "POST",
		RequestType:   "ArchiveCampaignRequest",
		ResponseType:  "ArchiveCampaignResponse",
		RequiredScope: "actions:openaiads:ArchiveCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateCampaign",
		HTTPMethod:    "POST",
		RequestType:   "CreateCampaignRequest",
		ResponseType:  "CreateCampaignResponse",
		RequiredScope: "actions:openaiads:CreateCampaign",
		Idempotency:   connector.ActionIdempotency("provider-key"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetCampaign",
		HTTPMethod:    "GET",
		RequestType:   "GetCampaignRequest",
		ResponseType:  "GetCampaignResponse",
		RequiredScope: "actions:openaiads:GetCampaign",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetCampaignInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetCampaignInsightsRequest",
		ResponseType:  "GetCampaignInsightsResponse",
		RequiredScope: "actions:openaiads:GetCampaignInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ListCampaigns",
		HTTPMethod:    "GET",
		RequestType:   "ListCampaignsRequest",
		ResponseType:  "ListCampaignsResponse",
		RequiredScope: "actions:openaiads:ListCampaigns",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "PauseCampaign",
		HTTPMethod:    "POST",
		RequestType:   "PauseCampaignRequest",
		ResponseType:  "PauseCampaignResponse",
		RequiredScope: "actions:openaiads:PauseCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "UpdateCampaign",
		HTTPMethod:    "POST",
		RequestType:   "UpdateCampaignRequest",
		ResponseType:  "UpdateCampaignResponse",
		RequiredScope: "actions:openaiads:UpdateCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateConversionApiKey",
		HTTPMethod:    "POST",
		RequestType:   "CreateConversionApiKeyRequest",
		ResponseType:  "CreateConversionApiKeyResponse",
		RequiredScope: "actions:openaiads:CreateConversionApiKey",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateConversionEventSetting",
		HTTPMethod:    "POST",
		RequestType:   "CreateConversionEventSettingRequest",
		ResponseType:  "CreateConversionEventSettingResponse",
		RequiredScope: "actions:openaiads:CreateConversionEventSetting",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "CreateConversionSource",
		HTTPMethod:    "POST",
		RequestType:   "CreateConversionSourceRequest",
		ResponseType:  "CreateConversionSourceResponse",
		RequiredScope: "actions:openaiads:CreateConversionSource",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "ListConversionEventSettings",
		HTTPMethod:    "GET",
		RequestType:   "ListConversionEventSettingsRequest",
		ResponseType:  "ListConversionEventSettingsResponse",
		RequiredScope: "actions:openaiads:ListConversionEventSettings",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "openaiads",
		Method:        "PostConversionInsights",
		HTTPMethod:    "POST",
		RequestType:   "PostConversionInsightsRequest",
		ResponseType:  "PostConversionInsightsResponse",
		RequiredScope: "actions:openaiads:PostConversionInsights",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "UploadImage",
		HTTPMethod:    "POST",
		RequestType:   "UploadImageRequest",
		ResponseType:  "UploadImageResponse",
		RequiredScope: "actions:openaiads:UploadImage",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "openaiads",
		Method:        "GetGeoLookup",
		HTTPMethod:    "GET",
		RequestType:   "GetGeoLookupRequest",
		ResponseType:  "GetGeoLookupResponse",
		RequiredScope: "actions:openaiads:GetGeoLookup",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
	"ActivateAdAccount":            invokeActivateAdAccountAction,
	"GetAdAccount":                 invokeGetAdAccountAction,
	"GetAdAccountInsights":         invokeGetAdAccountInsightsAction,
	"PauseAdAccount":               invokePauseAdAccountAction,
	"UpdateAdAccount":              invokeUpdateAdAccountAction,
	"ActivateAdGroup":              invokeActivateAdGroupAction,
	"ArchiveAdGroup":               invokeArchiveAdGroupAction,
	"CreateAdGroup":                invokeCreateAdGroupAction,
	"GetAdGroup":                   invokeGetAdGroupAction,
	"GetAdGroupInsights":           invokeGetAdGroupInsightsAction,
	"ListAdGroups":                 invokeListAdGroupsAction,
	"PauseAdGroup":                 invokePauseAdGroupAction,
	"UpdateAdGroup":                invokeUpdateAdGroupAction,
	"ActivateAd":                   invokeActivateAdAction,
	"ArchiveAd":                    invokeArchiveAdAction,
	"CreateAd":                     invokeCreateAdAction,
	"GetAd":                        invokeGetAdAction,
	"GetAdInsights":                invokeGetAdInsightsAction,
	"ListAds":                      invokeListAdsAction,
	"PauseAd":                      invokePauseAdAction,
	"UpdateAd":                     invokeUpdateAdAction,
	"ArchiveCustomAudience":        invokeArchiveCustomAudienceAction,
	"CreateCustomAudience":         invokeCreateCustomAudienceAction,
	"CreateCustomAudienceUpload":   invokeCreateCustomAudienceUploadAction,
	"GetCustomAudience":            invokeGetCustomAudienceAction,
	"ListCustomAudiences":          invokeListCustomAudiencesAction,
	"ActivateCampaign":             invokeActivateCampaignAction,
	"ArchiveCampaign":              invokeArchiveCampaignAction,
	"CreateCampaign":               invokeCreateCampaignAction,
	"GetCampaign":                  invokeGetCampaignAction,
	"GetCampaignInsights":          invokeGetCampaignInsightsAction,
	"ListCampaigns":                invokeListCampaignsAction,
	"PauseCampaign":                invokePauseCampaignAction,
	"UpdateCampaign":               invokeUpdateCampaignAction,
	"CreateConversionApiKey":       invokeCreateConversionApiKeyAction,
	"CreateConversionEventSetting": invokeCreateConversionEventSettingAction,
	"CreateConversionSource":       invokeCreateConversionSourceAction,
	"ListConversionEventSettings":  invokeListConversionEventSettingsAction,
	"PostConversionInsights":       invokePostConversionInsightsAction,
	"UploadImage":                  invokeUploadImageAction,
	"GetGeoLookup":                 invokeGetGeoLookupAction,
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "openaiads" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}

func invokeActivateAdAccountAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
	}
	if err := connector.DecodeActionRequest("openaiads", "ActivateAdAccount", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ActivateAdAccount(ctx, &ActivateAdAccountRequest{})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdAccountAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAdAccount", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdAccount(ctx, &GetAdAccountRequest{})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdAccountInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		TimeGranularity           *string  `json:"time_granularity,omitempty"`
		AggregationLevel          *string  `json:"aggregation_level,omitempty"`
		Limit                     *int     `json:"limit,omitempty"`
		Before                    *string  `json:"before,omitempty"`
		After                     *string  `json:"after,omitempty"`
		TimeRanges                []string `json:"time_ranges,omitempty"`
		Filters                   []string `json:"filters,omitempty"`
		Fields                    []string `json:"fields,omitempty"`
		Sort                      []string `json:"sort,omitempty"`
		Segments                  []string `json:"segments,omitempty"`
		OverrideSegmentGroupOrder []string `json:"override_segment_group_order,omitempty"`
		Includes                  []string `json:"includes,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAdAccountInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdAccountInsights(ctx, &GetAdAccountInsightsRequest{
		TimeGranularity:           wire.TimeGranularity,
		AggregationLevel:          wire.AggregationLevel,
		Limit:                     wire.Limit,
		Before:                    wire.Before,
		After:                     wire.After,
		TimeRanges:                wire.TimeRanges,
		Filters:                   wire.Filters,
		Fields:                    wire.Fields,
		Sort:                      wire.Sort,
		Segments:                  wire.Segments,
		OverrideSegmentGroupOrder: wire.OverrideSegmentGroupOrder,
		Includes:                  wire.Includes,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePauseAdAccountAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
	}
	if err := connector.DecodeActionRequest("openaiads", "PauseAdAccount", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PauseAdAccount(ctx, &PauseAdAccountRequest{})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateAdAccountAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FaviconFileId *string `json:"favicon_file_id,omitempty"`
		Name          *string `json:"name,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "UpdateAdAccount", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateAdAccount(ctx, &UpdateAdAccountRequest{
		FaviconFileId: wire.FaviconFileId,
		Name:          wire.Name,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeActivateAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId string `json:"ad_group_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ActivateAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ActivateAdGroup(ctx, &ActivateAdGroupRequest{
		AdGroupId: wire.AdGroupId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeArchiveAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId string `json:"ad_group_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ArchiveAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ArchiveAdGroup(ctx, &ArchiveAdGroupRequest{
		AdGroupId: wire.AdGroupId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IdempotencyKey *string              `json:"Idempotency-Key,omitempty"`
		BiddingConfig  *BiddingConfigParams `json:"bidding_config,omitempty"`
		CampaignId     *string              `json:"campaign_id,omitempty"`
		ContextHints   []string             `json:"context_hints,omitempty"`
		Description    *string              `json:"description,omitempty"`
		Name           *string              `json:"name,omitempty"`
		ProductSet     *ProductSetParams    `json:"product_set,omitempty"`
		Status         *string              `json:"status,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateAdGroup(ctx, &CreateAdGroupRequest{
		IdempotencyKey: wire.IdempotencyKey,
		BiddingConfig:  wire.BiddingConfig,
		CampaignId:     wire.CampaignId,
		ContextHints:   wire.ContextHints,
		Description:    wire.Description,
		Name:           wire.Name,
		ProductSet:     wire.ProductSet,
		Status:         wire.Status,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId string `json:"ad_group_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdGroup(ctx, &GetAdGroupRequest{
		AdGroupId: wire.AdGroupId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdGroupInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId                 string   `json:"ad_group_id,omitempty"`
		TimeGranularity           *string  `json:"time_granularity,omitempty"`
		AggregationLevel          *string  `json:"aggregation_level,omitempty"`
		Limit                     *int     `json:"limit,omitempty"`
		Before                    *string  `json:"before,omitempty"`
		After                     *string  `json:"after,omitempty"`
		TimeRanges                []string `json:"time_ranges,omitempty"`
		Filters                   []string `json:"filters,omitempty"`
		Fields                    []string `json:"fields,omitempty"`
		Sort                      []string `json:"sort,omitempty"`
		Segments                  []string `json:"segments,omitempty"`
		OverrideSegmentGroupOrder []string `json:"override_segment_group_order,omitempty"`
		Includes                  []string `json:"includes,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAdGroupInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdGroupInsights(ctx, &GetAdGroupInsightsRequest{
		AdGroupId:                 wire.AdGroupId,
		TimeGranularity:           wire.TimeGranularity,
		AggregationLevel:          wire.AggregationLevel,
		Limit:                     wire.Limit,
		Before:                    wire.Before,
		After:                     wire.After,
		TimeRanges:                wire.TimeRanges,
		Filters:                   wire.Filters,
		Fields:                    wire.Fields,
		Sort:                      wire.Sort,
		Segments:                  wire.Segments,
		OverrideSegmentGroupOrder: wire.OverrideSegmentGroupOrder,
		Includes:                  wire.Includes,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdGroupsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId *string `json:"campaign_id,omitempty"`
		Limit      *int    `json:"limit,omitempty"`
		After      *string `json:"after,omitempty"`
		Before     *string `json:"before,omitempty"`
		Order      *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ListAdGroups", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAdGroups(ctx, &ListAdGroupsRequest{
		CampaignId: wire.CampaignId,
		Limit:      wire.Limit,
		After:      wire.After,
		Before:     wire.Before,
		Order:      wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePauseAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId string `json:"ad_group_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "PauseAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PauseAdGroup(ctx, &PauseAdGroupRequest{
		AdGroupId: wire.AdGroupId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateAdGroupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId     string               `json:"ad_group_id,omitempty"`
		BiddingConfig *BiddingConfigParams `json:"bidding_config,omitempty"`
		ContextHints  []string             `json:"context_hints,omitempty"`
		Description   *string              `json:"description,omitempty"`
		Name          *string              `json:"name,omitempty"`
		ProductSet    *ProductSetParams    `json:"product_set,omitempty"`
		Status        *string              `json:"status,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "UpdateAdGroup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateAdGroup(ctx, &UpdateAdGroupRequest{
		AdGroupId:     wire.AdGroupId,
		BiddingConfig: wire.BiddingConfig,
		ContextHints:  wire.ContextHints,
		Description:   wire.Description,
		Name:          wire.Name,
		ProductSet:    wire.ProductSet,
		Status:        wire.Status,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeActivateAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId string `json:"ad_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ActivateAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ActivateAd(ctx, &ActivateAdRequest{
		AdId: wire.AdId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeArchiveAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId string `json:"ad_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ArchiveAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ArchiveAd(ctx, &ArchiveAdRequest{
		AdId: wire.AdId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IdempotencyKey *string                 `json:"Idempotency-Key,omitempty"`
		AdGroupId      *string                 `json:"ad_group_id,omitempty"`
		Creative       *CreateAdCreativeParams `json:"creative,omitempty"`
		Name           *string                 `json:"name,omitempty"`
		Status         *string                 `json:"status,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateAd(ctx, &CreateAdRequest{
		IdempotencyKey: wire.IdempotencyKey,
		AdGroupId:      wire.AdGroupId,
		Creative:       wire.Creative,
		Name:           wire.Name,
		Status:         wire.Status,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId string `json:"ad_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAd(ctx, &GetAdRequest{
		AdId: wire.AdId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId                      string   `json:"ad_id,omitempty"`
		TimeGranularity           *string  `json:"time_granularity,omitempty"`
		AggregationLevel          *string  `json:"aggregation_level,omitempty"`
		Limit                     *int     `json:"limit,omitempty"`
		Before                    *string  `json:"before,omitempty"`
		After                     *string  `json:"after,omitempty"`
		TimeRanges                []string `json:"time_ranges,omitempty"`
		Filters                   []string `json:"filters,omitempty"`
		Fields                    []string `json:"fields,omitempty"`
		Sort                      []string `json:"sort,omitempty"`
		Segments                  []string `json:"segments,omitempty"`
		OverrideSegmentGroupOrder []string `json:"override_segment_group_order,omitempty"`
		Includes                  []string `json:"includes,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetAdInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdInsights(ctx, &GetAdInsightsRequest{
		AdId:                      wire.AdId,
		TimeGranularity:           wire.TimeGranularity,
		AggregationLevel:          wire.AggregationLevel,
		Limit:                     wire.Limit,
		Before:                    wire.Before,
		After:                     wire.After,
		TimeRanges:                wire.TimeRanges,
		Filters:                   wire.Filters,
		Fields:                    wire.Fields,
		Sort:                      wire.Sort,
		Segments:                  wire.Segments,
		OverrideSegmentGroupOrder: wire.OverrideSegmentGroupOrder,
		Includes:                  wire.Includes,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdGroupId *string `json:"ad_group_id,omitempty"`
		Limit     *int    `json:"limit,omitempty"`
		After     *string `json:"after,omitempty"`
		Before    *string `json:"before,omitempty"`
		Order     *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ListAds", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAds(ctx, &ListAdsRequest{
		AdGroupId: wire.AdGroupId,
		Limit:     wire.Limit,
		After:     wire.After,
		Before:    wire.Before,
		Order:     wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePauseAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId string `json:"ad_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "PauseAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PauseAd(ctx, &PauseAdRequest{
		AdId: wire.AdId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId     string                  `json:"ad_id,omitempty"`
		Creative *UpdateAdCreativeParams `json:"creative,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Status   *string                 `json:"status,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "UpdateAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateAd(ctx, &UpdateAdRequest{
		AdId:     wire.AdId,
		Creative: wire.Creative,
		Name:     wire.Name,
		Status:   wire.Status,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeArchiveCustomAudienceAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomAudienceId string `json:"custom_audience_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ArchiveCustomAudience", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ArchiveCustomAudience(ctx, &ArchiveCustomAudienceRequest{
		CustomAudienceId: wire.CustomAudienceId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateCustomAudienceAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Description *string                     `json:"description,omitempty"`
		Members     []CustomAudienceMemberParam `json:"members,omitempty"`
		Name        *string                     `json:"name,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateCustomAudience", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateCustomAudience(ctx, &CreateCustomAudienceRequest{
		Description: wire.Description,
		Members:     wire.Members,
		Name:        wire.Name,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateCustomAudienceUploadAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Description    *string `json:"description,omitempty"`
		FileId         *string `json:"file_id,omitempty"`
		FileSize       *int    `json:"file_size,omitempty"`
		Filename       *string `json:"filename,omitempty"`
		IdentifierType *string `json:"identifier_type,omitempty"`
		Mimetype       *string `json:"mimetype,omitempty"`
		Name           *string `json:"name,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateCustomAudienceUpload", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateCustomAudienceUpload(ctx, &CreateCustomAudienceUploadRequest{
		Description:    wire.Description,
		FileId:         wire.FileId,
		FileSize:       wire.FileSize,
		Filename:       wire.Filename,
		IdentifierType: wire.IdentifierType,
		Mimetype:       wire.Mimetype,
		Name:           wire.Name,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetCustomAudienceAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CustomAudienceId string `json:"custom_audience_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetCustomAudience", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetCustomAudience(ctx, &GetCustomAudienceRequest{
		CustomAudienceId: wire.CustomAudienceId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListCustomAudiencesAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
		Before *string `json:"before,omitempty"`
		Order  *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ListCustomAudiences", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListCustomAudiences(ctx, &ListCustomAudiencesRequest{
		Limit:  wire.Limit,
		After:  wire.After,
		Before: wire.Before,
		Order:  wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeActivateCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string `json:"campaign_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ActivateCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ActivateCampaign(ctx, &ActivateCampaignRequest{
		CampaignId: wire.CampaignId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeArchiveCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string `json:"campaign_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ArchiveCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ArchiveCampaign(ctx, &ArchiveCampaignRequest{
		CampaignId: wire.CampaignId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IdempotencyKey            *string          `json:"Idempotency-Key,omitempty"`
		BiddingType               *string          `json:"bidding_type,omitempty"`
		Budget                    *BudgetParams    `json:"budget,omitempty"`
		ConversionEventSettingIds []string         `json:"conversion_event_setting_ids,omitempty"`
		Description               *string          `json:"description,omitempty"`
		EndTime                   *int             `json:"end_time,omitempty"`
		Mode                      *string          `json:"mode,omitempty"`
		Name                      *string          `json:"name,omitempty"`
		StartTime                 *int             `json:"start_time,omitempty"`
		Status                    *string          `json:"status,omitempty"`
		Targeting                 *TargetingParams `json:"targeting,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateCampaign(ctx, &CreateCampaignRequest{
		IdempotencyKey:            wire.IdempotencyKey,
		BiddingType:               wire.BiddingType,
		Budget:                    wire.Budget,
		ConversionEventSettingIds: wire.ConversionEventSettingIds,
		Description:               wire.Description,
		EndTime:                   wire.EndTime,
		Mode:                      wire.Mode,
		Name:                      wire.Name,
		StartTime:                 wire.StartTime,
		Status:                    wire.Status,
		Targeting:                 wire.Targeting,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string `json:"campaign_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetCampaign(ctx, &GetCampaignRequest{
		CampaignId: wire.CampaignId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetCampaignInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId                string   `json:"campaign_id,omitempty"`
		TimeGranularity           *string  `json:"time_granularity,omitempty"`
		AggregationLevel          *string  `json:"aggregation_level,omitempty"`
		Limit                     *int     `json:"limit,omitempty"`
		Before                    *string  `json:"before,omitempty"`
		After                     *string  `json:"after,omitempty"`
		TimeRanges                []string `json:"time_ranges,omitempty"`
		Filters                   []string `json:"filters,omitempty"`
		Fields                    []string `json:"fields,omitempty"`
		Sort                      []string `json:"sort,omitempty"`
		Segments                  []string `json:"segments,omitempty"`
		OverrideSegmentGroupOrder []string `json:"override_segment_group_order,omitempty"`
		Includes                  []string `json:"includes,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetCampaignInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetCampaignInsights(ctx, &GetCampaignInsightsRequest{
		CampaignId:                wire.CampaignId,
		TimeGranularity:           wire.TimeGranularity,
		AggregationLevel:          wire.AggregationLevel,
		Limit:                     wire.Limit,
		Before:                    wire.Before,
		After:                     wire.After,
		TimeRanges:                wire.TimeRanges,
		Filters:                   wire.Filters,
		Fields:                    wire.Fields,
		Sort:                      wire.Sort,
		Segments:                  wire.Segments,
		OverrideSegmentGroupOrder: wire.OverrideSegmentGroupOrder,
		Includes:                  wire.Includes,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListCampaignsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
		Before *string `json:"before,omitempty"`
		Order  *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ListCampaigns", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListCampaigns(ctx, &ListCampaignsRequest{
		Limit:  wire.Limit,
		After:  wire.After,
		Before: wire.Before,
		Order:  wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePauseCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string `json:"campaign_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "PauseCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PauseCampaign(ctx, &PauseCampaignRequest{
		CampaignId: wire.CampaignId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId                string           `json:"campaign_id,omitempty"`
		Budget                    *BudgetParams    `json:"budget,omitempty"`
		ConversionEventSettingIds []string         `json:"conversion_event_setting_ids,omitempty"`
		Description               *string          `json:"description,omitempty"`
		EndTime                   *int             `json:"end_time,omitempty"`
		Name                      *string          `json:"name,omitempty"`
		StartTime                 *int             `json:"start_time,omitempty"`
		Status                    *string          `json:"status,omitempty"`
		Targeting                 *TargetingParams `json:"targeting,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "UpdateCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateCampaign(ctx, &UpdateCampaignRequest{
		CampaignId:                wire.CampaignId,
		Budget:                    wire.Budget,
		ConversionEventSettingIds: wire.ConversionEventSettingIds,
		Description:               wire.Description,
		EndTime:                   wire.EndTime,
		Name:                      wire.Name,
		StartTime:                 wire.StartTime,
		Status:                    wire.Status,
		Targeting:                 wire.Targeting,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateConversionApiKeyAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Name *string `json:"name,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateConversionApiKey", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateConversionApiKey(ctx, &CreateConversionApiKeyRequest{
		Name: wire.Name,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateConversionEventSettingAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AttributionWindowDays *int     `json:"attribution_window_days,omitempty"`
		CustomEventName       *string  `json:"custom_event_name,omitempty"`
		EventType             *string  `json:"event_type,omitempty"`
		Name                  *string  `json:"name,omitempty"`
		SourceIds             []string `json:"source_ids,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateConversionEventSetting", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateConversionEventSetting(ctx, &CreateConversionEventSettingRequest{
		AttributionWindowDays: wire.AttributionWindowDays,
		CustomEventName:       wire.CustomEventName,
		EventType:             wire.EventType,
		Name:                  wire.Name,
		SourceIds:             wire.SourceIds,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateConversionSourceAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AutomaticAdvancedMatchingEnabled *bool   `json:"automatic_advanced_matching_enabled,omitempty"`
		ClientType                       *string `json:"client_type,omitempty"`
		Name                             *string `json:"name,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "CreateConversionSource", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateConversionSource(ctx, &CreateConversionSourceRequest{
		AutomaticAdvancedMatchingEnabled: wire.AutomaticAdvancedMatchingEnabled,
		ClientType:                       wire.ClientType,
		Name:                             wire.Name,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListConversionEventSettingsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
		Before *string `json:"before,omitempty"`
		Order  *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "ListConversionEventSettings", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListConversionEventSettings(ctx, &ListConversionEventSettingsRequest{
		Limit:  wire.Limit,
		After:  wire.After,
		Before: wire.Before,
		Order:  wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePostConversionInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AggregationLevel *string  `json:"aggregation_level,omitempty"`
		EntityIds        []string `json:"entity_ids,omitempty"`
		TimeRanges       []string `json:"time_ranges,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "PostConversionInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PostConversionInsights(ctx, &PostConversionInsightsRequest{
		AggregationLevel: wire.AggregationLevel,
		EntityIds:        wire.EntityIds,
		TimeRanges:       wire.TimeRanges,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUploadImageAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		File     *string `json:"file,omitempty"`
		ImageUrl *string `json:"image_url,omitempty"`
		Purpose  *string `json:"purpose,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "UploadImage", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UploadImage(ctx, &UploadImageRequest{
		File:     wire.File,
		ImageUrl: wire.ImageUrl,
		Purpose:  wire.Purpose,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetGeoLookupAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Q     *string `json:"q,omitempty"`
		Limit *int    `json:"limit,omitempty"`
	}
	if err := connector.DecodeActionRequest("openaiads", "GetGeoLookup", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetGeoLookup(ctx, &GetGeoLookupRequest{
		Q:     wire.Q,
		Limit: wire.Limit,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
