// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// ActivateAdGroupRequest holds the parameters for ActivateAdGroup.
type ActivateAdGroupRequest struct {
	AdGroupId string `json:"-" path:"ad_group_id"`
}

// ActivateAdGroupResponse is the response type of ActivateAdGroup.
type ActivateAdGroupResponse = AdGroupItemBody

// ActivateAdGroup calls POST /ad_groups/{ad_group_id}/activate.
func (c *Client) ActivateAdGroup(ctx context.Context, req *ActivateAdGroupRequest) (*ActivateAdGroupResponse, error) {
	if req == nil {
		req = &ActivateAdGroupRequest{}
	}
	out := &ActivateAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/ad_groups/{ad_group_id}/activate",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveAdGroupRequest holds the parameters for ArchiveAdGroup.
type ArchiveAdGroupRequest struct {
	AdGroupId string `json:"-" path:"ad_group_id"`
}

// ArchiveAdGroupResponse is the response type of ArchiveAdGroup.
type ArchiveAdGroupResponse = AdGroupItemBody

// ArchiveAdGroup calls POST /ad_groups/{ad_group_id}/archive.
func (c *Client) ArchiveAdGroup(ctx context.Context, req *ArchiveAdGroupRequest) (*ArchiveAdGroupResponse, error) {
	if req == nil {
		req = &ArchiveAdGroupRequest{}
	}
	out := &ArchiveAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/ad_groups/{ad_group_id}/archive",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateAdGroupRequest holds the parameters for CreateAdGroup.
type CreateAdGroupRequest struct {
	IdempotencyKey *string              `json:"-" header:"Idempotency-Key"`
	BiddingConfig  *BiddingConfigParams `json:"bidding_config,omitempty"`
	CampaignId     *string              `json:"campaign_id,omitempty"`
	ContextHints   []string             `json:"context_hints,omitempty"`
	Description    *string              `json:"description,omitempty"`
	Name           *string              `json:"name,omitempty"`
	ProductSet     *ProductSetParams    `json:"product_set,omitempty"`
	Status         *string              `json:"status,omitempty"`
}

// CreateAdGroupResponse is the response type of CreateAdGroup.
type CreateAdGroupResponse = AdGroupItemBody

// CreateAdGroup calls POST /ad_groups.
func (c *Client) CreateAdGroup(ctx context.Context, req *CreateAdGroupRequest) (*CreateAdGroupResponse, error) {
	if req == nil {
		req = &CreateAdGroupRequest{}
	}
	out := &CreateAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/ad_groups",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAdGroupRequest holds the parameters for GetAdGroup.
type GetAdGroupRequest struct {
	AdGroupId string `json:"-" path:"ad_group_id"`
}

// GetAdGroupResponse is the response type of GetAdGroup.
type GetAdGroupResponse = AdGroupItemBody

// GetAdGroup calls GET /ad_groups/{ad_group_id}.
func (c *Client) GetAdGroup(ctx context.Context, req *GetAdGroupRequest) (*GetAdGroupResponse, error) {
	if req == nil {
		req = &GetAdGroupRequest{}
	}
	out := &GetAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/ad_groups/{ad_group_id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAdGroupInsightsRequest holds the parameters for GetAdGroupInsights.
type GetAdGroupInsightsRequest struct {
	AdGroupId                 string   `json:"-" path:"ad_group_id"`
	TimeGranularity           *string  `json:"-" query:"time_granularity"`
	AggregationLevel          *string  `json:"-" query:"aggregation_level"`
	Limit                     *int     `json:"-" query:"limit"`
	Before                    *string  `json:"-" query:"before"`
	After                     *string  `json:"-" query:"after"`
	TimeRanges                []string `json:"-" query:"time_ranges"`
	Filters                   []string `json:"-" query:"filters"`
	Fields                    []string `json:"-" query:"fields"`
	Sort                      []string `json:"-" query:"sort"`
	Segments                  []string `json:"-" query:"segments"`
	OverrideSegmentGroupOrder []string `json:"-" query:"override_segment_group_order"`
	Includes                  []string `json:"-" query:"includes"`
}

// GetAdGroupInsightsResponse is the response type of GetAdGroupInsights.
type GetAdGroupInsightsResponse = InsightsResource

// GetAdGroupInsights calls GET /ad_groups/{ad_group_id}/insights.
func (c *Client) GetAdGroupInsights(ctx context.Context, req *GetAdGroupInsightsRequest) (*GetAdGroupInsightsResponse, error) {
	if req == nil {
		req = &GetAdGroupInsightsRequest{}
	}
	out := &GetAdGroupInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/ad_groups/{ad_group_id}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListAdGroupsRequest holds the parameters for ListAdGroups.
type ListAdGroupsRequest struct {
	CampaignId *string `json:"-" query:"campaign_id"`
	Limit      *int    `json:"-" query:"limit"`
	After      *string `json:"-" query:"after"`
	Before     *string `json:"-" query:"before"`
	Order      *string `json:"-" query:"order"`
}

// ListAdGroupsResponse is the response type of ListAdGroups.
type ListAdGroupsResponse = AdGroupsResource

// ListAdGroups calls GET /ad_groups.
func (c *Client) ListAdGroups(ctx context.Context, req *ListAdGroupsRequest) (*ListAdGroupsResponse, error) {
	if req == nil {
		req = &ListAdGroupsRequest{}
	}
	out := &ListAdGroupsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/ad_groups",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PauseAdGroupRequest holds the parameters for PauseAdGroup.
type PauseAdGroupRequest struct {
	AdGroupId string `json:"-" path:"ad_group_id"`
}

// PauseAdGroupResponse is the response type of PauseAdGroup.
type PauseAdGroupResponse = AdGroupItemBody

// PauseAdGroup calls POST /ad_groups/{ad_group_id}/pause.
func (c *Client) PauseAdGroup(ctx context.Context, req *PauseAdGroupRequest) (*PauseAdGroupResponse, error) {
	if req == nil {
		req = &PauseAdGroupRequest{}
	}
	out := &PauseAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/ad_groups/{ad_group_id}/pause",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAdGroupRequest holds the parameters for UpdateAdGroup.
type UpdateAdGroupRequest struct {
	AdGroupId     string               `json:"-" path:"ad_group_id"`
	BiddingConfig *BiddingConfigParams `json:"bidding_config,omitempty"`
	ContextHints  []string             `json:"context_hints,omitempty"`
	Description   *string              `json:"description,omitempty"`
	Name          *string              `json:"name,omitempty"`
	ProductSet    *ProductSetParams    `json:"product_set,omitempty"`
	Status        *string              `json:"status,omitempty"`
}

// UpdateAdGroupResponse is the response type of UpdateAdGroup.
type UpdateAdGroupResponse = AdGroupItemBody

// UpdateAdGroup calls POST /ad_groups/{ad_group_id}.
func (c *Client) UpdateAdGroup(ctx context.Context, req *UpdateAdGroupRequest) (*UpdateAdGroupResponse, error) {
	if req == nil {
		req = &UpdateAdGroupRequest{}
	}
	out := &UpdateAdGroupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/ad_groups/{ad_group_id}",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
