// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// ArchiveCustomAudienceRequest holds the parameters for ArchiveCustomAudience.
type ArchiveCustomAudienceRequest struct {
	CustomAudienceId string `json:"-" path:"custom_audience_id"`
}

// ArchiveCustomAudienceResponse is the response type of ArchiveCustomAudience.
type ArchiveCustomAudienceResponse = CustomAudienceItemBody

// ArchiveCustomAudience calls POST /custom_audiences/{custom_audience_id}/archive.
func (c *Client) ArchiveCustomAudience(ctx context.Context, req *ArchiveCustomAudienceRequest) (*ArchiveCustomAudienceResponse, error) {
	if req == nil {
		req = &ArchiveCustomAudienceRequest{}
	}
	out := &ArchiveCustomAudienceResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/custom_audiences/{custom_audience_id}/archive",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateCustomAudienceRequest holds the parameters for CreateCustomAudience.
type CreateCustomAudienceRequest struct {
	Description *string                     `json:"description,omitempty"`
	Members     []CustomAudienceMemberParam `json:"members,omitempty"`
	Name        *string                     `json:"name,omitempty"`
}

// CreateCustomAudienceResponse is the response type of CreateCustomAudience.
type CreateCustomAudienceResponse = CustomAudienceItemBody

// CreateCustomAudience calls POST /custom_audiences.
func (c *Client) CreateCustomAudience(ctx context.Context, req *CreateCustomAudienceRequest) (*CreateCustomAudienceResponse, error) {
	if req == nil {
		req = &CreateCustomAudienceRequest{}
	}
	out := &CreateCustomAudienceResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/custom_audiences",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateCustomAudienceUploadRequest holds the parameters for CreateCustomAudienceUpload.
type CreateCustomAudienceUploadRequest struct {
	Description    *string `json:"description,omitempty"`
	FileId         *string `json:"file_id,omitempty"`
	FileSize       *int    `json:"file_size,omitempty"`
	Filename       *string `json:"filename,omitempty"`
	IdentifierType *string `json:"identifier_type,omitempty"`
	Mimetype       *string `json:"mimetype,omitempty"`
	Name           *string `json:"name,omitempty"`
}

// CreateCustomAudienceUploadResponse is the response type of CreateCustomAudienceUpload.
type CreateCustomAudienceUploadResponse = CustomAudienceItemBody

// CreateCustomAudienceUpload calls POST /custom_audiences/upload.
func (c *Client) CreateCustomAudienceUpload(ctx context.Context, req *CreateCustomAudienceUploadRequest) (*CreateCustomAudienceUploadResponse, error) {
	if req == nil {
		req = &CreateCustomAudienceUploadRequest{}
	}
	out := &CreateCustomAudienceUploadResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/custom_audiences/upload",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCustomAudienceRequest holds the parameters for GetCustomAudience.
type GetCustomAudienceRequest struct {
	CustomAudienceId string `json:"-" path:"custom_audience_id"`
}

// GetCustomAudienceResponse is the response type of GetCustomAudience.
type GetCustomAudienceResponse = CustomAudienceItemBody

// GetCustomAudience calls GET /custom_audiences/{custom_audience_id}.
func (c *Client) GetCustomAudience(ctx context.Context, req *GetCustomAudienceRequest) (*GetCustomAudienceResponse, error) {
	if req == nil {
		req = &GetCustomAudienceRequest{}
	}
	out := &GetCustomAudienceResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/custom_audiences/{custom_audience_id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListCustomAudiencesRequest holds the parameters for ListCustomAudiences.
type ListCustomAudiencesRequest struct {
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
	Before *string `json:"-" query:"before"`
	Order  *string `json:"-" query:"order"`
}

// ListCustomAudiencesResponse is the response type of ListCustomAudiences.
type ListCustomAudiencesResponse = CustomAudiencesResource

// ListCustomAudiences calls GET /custom_audiences.
func (c *Client) ListCustomAudiences(ctx context.Context, req *ListCustomAudiencesRequest) (*ListCustomAudiencesResponse, error) {
	if req == nil {
		req = &ListCustomAudiencesRequest{}
	}
	out := &ListCustomAudiencesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/custom_audiences",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
