// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// ActivateCampaignRequest holds the parameters for ActivateCampaign.
type ActivateCampaignRequest struct {
	CampaignId string `json:"-" path:"campaign_id"`
}

// ActivateCampaignResponse is the response type of ActivateCampaign.
type ActivateCampaignResponse = CampaignItemBody

// ActivateCampaign calls POST /campaigns/{campaign_id}/activate.
func (c *Client) ActivateCampaign(ctx context.Context, req *ActivateCampaignRequest) (*ActivateCampaignResponse, error) {
	if req == nil {
		req = &ActivateCampaignRequest{}
	}
	out := &ActivateCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/campaigns/{campaign_id}/activate",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveCampaignRequest holds the parameters for ArchiveCampaign.
type ArchiveCampaignRequest struct {
	CampaignId string `json:"-" path:"campaign_id"`
}

// ArchiveCampaignResponse is the response type of ArchiveCampaign.
type ArchiveCampaignResponse = CampaignItemBody

// ArchiveCampaign calls POST /campaigns/{campaign_id}/archive.
func (c *Client) ArchiveCampaign(ctx context.Context, req *ArchiveCampaignRequest) (*ArchiveCampaignResponse, error) {
	if req == nil {
		req = &ArchiveCampaignRequest{}
	}
	out := &ArchiveCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/campaigns/{campaign_id}/archive",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateCampaignRequest holds the parameters for CreateCampaign.
type CreateCampaignRequest struct {
	IdempotencyKey            *string          `json:"-" header:"Idempotency-Key"`
	BiddingType               *string          `json:"bidding_type,omitempty"`
	Budget                    *BudgetParams    `json:"budget,omitempty"`
	ConversionEventSettingIds []string         `json:"conversion_event_setting_ids,omitempty"`
	Description               *string          `json:"description,omitempty"`
	EndTime                   *int             `json:"end_time,omitempty"`
	Mode                      *string          `json:"mode,omitempty"`
	Name                      *string          `json:"name,omitempty"`
	StartTime                 *int             `json:"start_time,omitempty"`
	Status                    *string          `json:"status,omitempty"`
	Targeting                 *TargetingParams `json:"targeting,omitempty"`
}

// CreateCampaignResponse is the response type of CreateCampaign.
type CreateCampaignResponse = CampaignItemBody

// CreateCampaign calls POST /campaigns.
func (c *Client) CreateCampaign(ctx context.Context, req *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	if req == nil {
		req = &CreateCampaignRequest{}
	}
	out := &CreateCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/campaigns",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCampaignRequest holds the parameters for GetCampaign.
type GetCampaignRequest struct {
	CampaignId string `json:"-" path:"campaign_id"`
}

// GetCampaignResponse is the response type of GetCampaign.
type GetCampaignResponse = CampaignItemBody

// GetCampaign calls GET /campaigns/{campaign_id}.
func (c *Client) GetCampaign(ctx context.Context, req *GetCampaignRequest) (*GetCampaignResponse, error) {
	if req == nil {
		req = &GetCampaignRequest{}
	}
	out := &GetCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/campaigns/{campaign_id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCampaignInsightsRequest holds the parameters for GetCampaignInsights.
type GetCampaignInsightsRequest struct {
	CampaignId                string   `json:"-" path:"campaign_id"`
	TimeGranularity           *string  `json:"-" query:"time_granularity"`
	AggregationLevel          *string  `json:"-" query:"aggregation_level"`
	Limit                     *int     `json:"-" query:"limit"`
	Before                    *string  `json:"-" query:"before"`
	After                     *string  `json:"-" query:"after"`
	TimeRanges                []string `json:"-" query:"time_ranges"`
	Filters                   []string `json:"-" query:"filters"`
	Fields                    []string `json:"-" query:"fields"`
	Sort                      []string `json:"-" query:"sort"`
	Segments                  []string `json:"-" query:"segments"`
	OverrideSegmentGroupOrder []string `json:"-" query:"override_segment_group_order"`
	Includes                  []string `json:"-" query:"includes"`
}

// GetCampaignInsightsResponse is the response type of GetCampaignInsights.
type GetCampaignInsightsResponse = InsightsResource

// GetCampaignInsights calls GET /campaigns/{campaign_id}/insights.
func (c *Client) GetCampaignInsights(ctx context.Context, req *GetCampaignInsightsRequest) (*GetCampaignInsightsResponse, error) {
	if req == nil {
		req = &GetCampaignInsightsRequest{}
	}
	out := &GetCampaignInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/campaigns/{campaign_id}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListCampaignsRequest holds the parameters for ListCampaigns.
type ListCampaignsRequest struct {
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
	Before *string `json:"-" query:"before"`
	Order  *string `json:"-" query:"order"`
}

// ListCampaignsResponse is the response type of ListCampaigns.
type ListCampaignsResponse = CampaignsResource

// ListCampaigns calls GET /campaigns.
func (c *Client) ListCampaigns(ctx context.Context, req *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	if req == nil {
		req = &ListCampaignsRequest{}
	}
	out := &ListCampaignsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/campaigns",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PauseCampaignRequest holds the parameters for PauseCampaign.
type PauseCampaignRequest struct {
	CampaignId string `json:"-" path:"campaign_id"`
}

// PauseCampaignResponse is the response type of PauseCampaign.
type PauseCampaignResponse = CampaignItemBody

// PauseCampaign calls POST /campaigns/{campaign_id}/pause.
func (c *Client) PauseCampaign(ctx context.Context, req *PauseCampaignRequest) (*PauseCampaignResponse, error) {
	if req == nil {
		req = &PauseCampaignRequest{}
	}
	out := &PauseCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/campaigns/{campaign_id}/pause",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateCampaignRequest holds the parameters for UpdateCampaign.
type UpdateCampaignRequest struct {
	CampaignId                string           `json:"-" path:"campaign_id"`
	Budget                    *BudgetParams    `json:"budget,omitempty"`
	ConversionEventSettingIds []string         `json:"conversion_event_setting_ids,omitempty"`
	Description               *string          `json:"description,omitempty"`
	EndTime                   *int             `json:"end_time,omitempty"`
	Name                      *string          `json:"name,omitempty"`
	StartTime                 *int             `json:"start_time,omitempty"`
	Status                    *string          `json:"status,omitempty"`
	Targeting                 *TargetingParams `json:"targeting,omitempty"`
}

// UpdateCampaignResponse is the response type of UpdateCampaign.
type UpdateCampaignResponse = CampaignItemBody

// UpdateCampaign calls POST /campaigns/{campaign_id}.
func (c *Client) UpdateCampaign(ctx context.Context, req *UpdateCampaignRequest) (*UpdateCampaignResponse, error) {
	if req == nil {
		req = &UpdateCampaignRequest{}
	}
	out := &UpdateCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/campaigns/{campaign_id}",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
