// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateConversionApiKeyRequest holds the parameters for CreateConversionApiKey.
type CreateConversionApiKeyRequest struct {
	Name *string `json:"name,omitempty"`
}

// CreateConversionApiKeyResponse is the response type of CreateConversionApiKey.
type CreateConversionApiKeyResponse = ConversionApiKeyResource

// CreateConversionApiKey calls POST /conversions/api_keys.
func (c *Client) CreateConversionApiKey(ctx context.Context, req *CreateConversionApiKeyRequest) (*CreateConversionApiKeyResponse, error) {
	if req == nil {
		req = &CreateConversionApiKeyRequest{}
	}
	out := &CreateConversionApiKeyResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/conversions/api_keys",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateConversionEventSettingRequest holds the parameters for CreateConversionEventSetting.
type CreateConversionEventSettingRequest struct {
	AttributionWindowDays *int     `json:"attribution_window_days,omitempty"`
	CustomEventName       *string  `json:"custom_event_name,omitempty"`
	EventType             *string  `json:"event_type,omitempty"`
	Name                  *string  `json:"name,omitempty"`
	SourceIds             []string `json:"source_ids,omitempty"`
}

// CreateConversionEventSettingResponse is the response type of CreateConversionEventSetting.
type CreateConversionEventSettingResponse = ConversionEventSettingItemResource

// CreateConversionEventSetting calls POST /conversions/event_settings.
func (c *Client) CreateConversionEventSetting(ctx context.Context, req *CreateConversionEventSettingRequest) (*CreateConversionEventSettingResponse, error) {
	if req == nil {
		req = &CreateConversionEventSettingRequest{}
	}
	out := &CreateConversionEventSettingResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/conversions/event_settings",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateConversionSourceRequest holds the parameters for CreateConversionSource.
type CreateConversionSourceRequest struct {
	AutomaticAdvancedMatchingEnabled *bool   `json:"automatic_advanced_matching_enabled,omitempty"`
	ClientType                       *string `json:"client_type,omitempty"`
	Name                             *string `json:"name,omitempty"`
}

// CreateConversionSourceResponse is the response type of CreateConversionSource.
type CreateConversionSourceResponse = ClientDataSourceItemResource

// CreateConversionSource calls POST /conversions/pixels.
func (c *Client) CreateConversionSource(ctx context.Context, req *CreateConversionSourceRequest) (*CreateConversionSourceResponse, error) {
	if req == nil {
		req = &CreateConversionSourceRequest{}
	}
	out := &CreateConversionSourceResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/conversions/pixels",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListConversionEventSettingsRequest holds the parameters for ListConversionEventSettings.
type ListConversionEventSettingsRequest struct {
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
	Before *string `json:"-" query:"before"`
	Order  *string `json:"-" query:"order"`
}

// ListConversionEventSettingsResponse is the response type of ListConversionEventSettings.
type ListConversionEventSettingsResponse = ListConversionEventSettingsResource

// ListConversionEventSettings calls GET /conversions/event_settings.
func (c *Client) ListConversionEventSettings(ctx context.Context, req *ListConversionEventSettingsRequest) (*ListConversionEventSettingsResponse, error) {
	if req == nil {
		req = &ListConversionEventSettingsRequest{}
	}
	out := &ListConversionEventSettingsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/conversions/event_settings",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostConversionInsightsRequest holds the parameters for PostConversionInsights.
type PostConversionInsightsRequest struct {
	AggregationLevel *string  `json:"aggregation_level,omitempty"`
	EntityIds        []string `json:"entity_ids,omitempty"`
	TimeRanges       []string `json:"time_ranges,omitempty"`
}

// PostConversionInsightsResponse is the response type of PostConversionInsights.
type PostConversionInsightsResponse = ConversionSummaryRowsResource

// PostConversionInsights calls POST /conversions/insights.
func (c *Client) PostConversionInsights(ctx context.Context, req *PostConversionInsightsRequest) (*PostConversionInsightsResponse, error) {
	if req == nil {
		req = &PostConversionInsightsRequest{}
	}
	out := &PostConversionInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/conversions/insights",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
