// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// UploadImageRequest holds the parameters for UploadImage.
type UploadImageRequest struct {
	File     *string `json:"file,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	Purpose  *string `json:"purpose,omitempty"`
}

// UploadImageResponse is the response type of UploadImage.
type UploadImageResponse = UploadImageResource

// UploadImage calls POST /upload.
func (c *Client) UploadImage(ctx context.Context, req *UploadImageRequest) (*UploadImageResponse, error) {
	if req == nil {
		req = &UploadImageRequest{}
	}
	out := &UploadImageResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/upload",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
