// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetGeoLookupRequest holds the parameters for GetGeoLookup.
type GetGeoLookupRequest struct {
	Q     *string `json:"-" query:"q"`
	Limit *int    `json:"-" query:"limit"`
}

// GetGeoLookupResponse is the response type of GetGeoLookup.
type GetGeoLookupResponse = GeoLookupSearchResource

// GetGeoLookup calls GET /geo_lookup/search.
func (c *Client) GetGeoLookup(ctx context.Context, req *GetGeoLookupRequest) (*GetGeoLookupResponse, error) {
	if req == nil {
		req = &GetGeoLookupRequest{}
	}
	out := &GetGeoLookupResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/geo_lookup/search",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
