// Code generated by connector-gen. DO NOT EDIT.

package openaiads

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
	{
		name:   "ActivateAdAccount",
		method: "POST",
		path:   "/ad_account/activate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAdAccount(ctx, &ActivateAdAccountRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAdAccount(ctx, nil)
		},
	},
	{
		name:   "GetAdAccount",
		method: "GET",
		path:   "/ad_account",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccount(ctx, &GetAdAccountRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccount(ctx, nil)
		},
	},
	{
		name:   "GetAdAccountInsights",
		method: "GET",
		path:   "/ad_account/insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccountInsights(ctx, &GetAdAccountInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccountInsights(ctx, nil)
		},
	},
	{
		name:   "PauseAdAccount",
		method: "POST",
		path:   "/ad_account/pause",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAdAccount(ctx, &PauseAdAccountRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAdAccount(ctx, nil)
		},
	},
	{
		name:   "UpdateAdAccount",
		method: "POST",
		path:   "/ad_account/brand",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdAccount(ctx, &UpdateAdAccountRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdAccount(ctx, nil)
		},
	},
	{
		name:   "ActivateAdGroup",
		method: "POST",
		path:   "/ad_groups//activate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAdGroup(ctx, &ActivateAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAdGroup(ctx, nil)
		},
	},
	{
		name:   "ArchiveAdGroup",
		method: "POST",
		path:   "/ad_groups//archive",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveAdGroup(ctx, &ArchiveAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveAdGroup(ctx, nil)
		},
	},
	{
		name:   "CreateAdGroup",
		method: "POST",
		path:   "/ad_groups",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdGroup(ctx, &CreateAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdGroup(ctx, nil)
		},
	},
	{
		name:   "GetAdGroup",
		method: "GET",
		path:   "/ad_groups/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdGroup(ctx, &GetAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdGroup(ctx, nil)
		},
	},
	{
		name:   "GetAdGroupInsights",
		method: "GET",
		path:   "/ad_groups//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdGroupInsights(ctx, &GetAdGroupInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdGroupInsights(ctx, nil)
		},
	},
	{
		name:   "ListAdGroups",
		method: "GET",
		path:   "/ad_groups",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdGroups(ctx, &ListAdGroupsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdGroups(ctx, nil)
		},
	},
	{
		name:   "PauseAdGroup",
		method: "POST",
		path:   "/ad_groups//pause",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAdGroup(ctx, &PauseAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAdGroup(ctx, nil)
		},
	},
	{
		name:   "UpdateAdGroup",
		method: "POST",
		path:   "/ad_groups/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdGroup(ctx, &UpdateAdGroupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdGroup(ctx, nil)
		},
	},
	{
		name:   "ActivateAd",
		method: "POST",
		path:   "/ads//activate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAd(ctx, &ActivateAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateAd(ctx, nil)
		},
	},
	{
		name:   "ArchiveAd",
		method: "POST",
		path:   "/ads//archive",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveAd(ctx, &ArchiveAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveAd(ctx, nil)
		},
	},
	{
		name:   "CreateAd",
		method: "POST",
		path:   "/ads",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAd(ctx, &CreateAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAd(ctx, nil)
		},
	},
	{
		name:   "GetAd",
		method: "GET",
		path:   "/ads/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAd(ctx, &GetAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAd(ctx, nil)
		},
	},
	{
		name:   "GetAdInsights",
		method: "GET",
		path:   "/ads//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdInsights(ctx, &GetAdInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdInsights(ctx, nil)
		},
	},
	{
		name:   "ListAds",
		method: "GET",
		path:   "/ads",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAds(ctx, &ListAdsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAds(ctx, nil)
		},
	},
	{
		name:   "PauseAd",
		method: "POST",
		path:   "/ads//pause",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAd(ctx, &PauseAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseAd(ctx, nil)
		},
	},
	{
		name:   "UpdateAd",
		method: "POST",
		path:   "/ads/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAd(ctx, &UpdateAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAd(ctx, nil)
		},
	},
	{
		name:   "ArchiveCustomAudience",
		method: "POST",
		path:   "/custom_audiences//archive",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveCustomAudience(ctx, &ArchiveCustomAudienceRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveCustomAudience(ctx, nil)
		},
	},
	{
		name:   "CreateCustomAudience",
		method: "POST",
		path:   "/custom_audiences",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCustomAudience(ctx, &CreateCustomAudienceRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCustomAudience(ctx, nil)
		},
	},
	{
		name:   "CreateCustomAudienceUpload",
		method: "POST",
		path:   "/custom_audiences/upload",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCustomAudienceUpload(ctx, &CreateCustomAudienceUploadRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCustomAudienceUpload(ctx, nil)
		},
	},
	{
		name:   "GetCustomAudience",
		method: "GET",
		path:   "/custom_audiences/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCustomAudience(ctx, &GetCustomAudienceRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCustomAudience(ctx, nil)
		},
	},
	{
		name:   "ListCustomAudiences",
		method: "GET",
		path:   "/custom_audiences",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCustomAudiences(ctx, &ListCustomAudiencesRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCustomAudiences(ctx, nil)
		},
	},
	{
		name:   "ActivateCampaign",
		method: "POST",
		path:   "/campaigns//activate",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateCampaign(ctx, &ActivateCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ActivateCampaign(ctx, nil)
		},
	},
	{
		name:   "ArchiveCampaign",
		method: "POST",
		path:   "/campaigns//archive",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveCampaign(ctx, &ArchiveCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ArchiveCampaign(ctx, nil)
		},
	},
	{
		name:   "CreateCampaign",
		method: "POST",
		path:   "/campaigns",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCampaign(ctx, &CreateCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCampaign(ctx, nil)
		},
	},
	{
		name:   "GetCampaign",
		method: "GET",
		path:   "/campaigns/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaign(ctx, &GetCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaign(ctx, nil)
		},
	},
	{
		name:   "GetCampaignInsights",
		method: "GET",
		path:   "/campaigns//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaignInsights(ctx, &GetCampaignInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaignInsights(ctx, nil)
		},
	},
	{
		name:   "ListCampaigns",
		method: "GET",
		path:   "/campaigns",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCampaigns(ctx, &ListCampaignsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCampaigns(ctx, nil)
		},
	},
	{
		name:   "PauseCampaign",
		method: "POST",
		path:   "/campaigns//pause",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseCampaign(ctx, &PauseCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.PauseCampaign(ctx, nil)
		},
	},
	{
		name:   "UpdateCampaign",
		method: "POST",
		path:   "/campaigns/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateCampaign(ctx, &UpdateCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateCampaign(ctx, nil)
		},
	},
	{
		name:   "CreateConversionApiKey",
		method: "POST",
		path:   "/conversions/api_keys",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionApiKey(ctx, &CreateConversionApiKeyRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionApiKey(ctx, nil)
		},
	},
	{
		name:   "CreateConversionEventSetting",
		method: "POST",
		path:   "/conversions/event_settings",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionEventSetting(ctx, &CreateConversionEventSettingRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionEventSetting(ctx, nil)
		},
	},
	{
		name:   "CreateConversionSource",
		method: "POST",
		path:   "/conversions/pixels",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionSource(ctx, &CreateConversionSourceRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateConversionSource(ctx, nil)
		},
	},
	{
		name:   "ListConversionEventSettings",
		method: "GET",
		path:   "/conversions/event_settings",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListConversionEventSettings(ctx, &ListConversionEventSettingsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListConversionEventSettings(ctx, nil)
		},
	},
	{
		name:   "PostConversionInsights",
		method: "POST",
		path:   "/conversions/insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.PostConversionInsights(ctx, &PostConversionInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.PostConversionInsights(ctx, nil)
		},
	},
	{
		name:   "UploadImage",
		method: "POST",
		path:   "/upload",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UploadImage(ctx, &UploadImageRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UploadImage(ctx, nil)
		},
	},
	{
		name:   "GetGeoLookup",
		method: "GET",
		path:   "/geo_lookup/search",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetGeoLookup(ctx, &GetGeoLookupRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetGeoLookup(ctx, nil)
		},
	},
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{APIKey: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{APIKey: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
