// Code generated by connector-gen. DO NOT EDIT.

package openaiads

// AccountIntegrityReviewBody is the AccountIntegrityReviewBody model.
type AccountIntegrityReviewBody struct {
	Details *AccountIntegrityReviewDetailsBody `json:"details,omitempty"`
	Review  *ReviewBody                        `json:"review,omitempty"`
}

// AccountIntegrityReviewDetailsBody is the AccountIntegrityReviewDetailsBody model.
type AccountIntegrityReviewDetailsBody struct {
	Decision        *string `json:"decision,omitempty"`
	Reason          *string `json:"reason,omitempty"`
	StatusUpdatedAt *string `json:"status_updated_at,omitempty"`
}

// AdAccountResource is the AdAccountResource model.
type AdAccountResource struct {
	AccountIntegrityReview *AccountIntegrityReviewBody `json:"account_integrity_review,omitempty"`
	CurrencyCode           *string                     `json:"currency_code,omitempty"`
	Id                     *string                     `json:"id,omitempty"`
	Name                   *string                     `json:"name,omitempty"`
	PreviewUrl             *string                     `json:"preview_url,omitempty"`
	Review                 *ReviewBody                 `json:"review,omitempty"`
	Status                 *string                     `json:"status,omitempty"`
	Timezone               *string                     `json:"timezone,omitempty"`
	Url                    *string                     `json:"url,omitempty"`
}

// AdGroupItemBody is the AdGroupItemBody model.
type AdGroupItemBody struct {
	BiddingConfig *BiddingConfigBody `json:"bidding_config,omitempty"`
	ContextHints  []string           `json:"context_hints,omitempty"`
	CreatedAt     *int               `json:"created_at,omitempty"`
	Description   *string            `json:"description,omitempty"`
	Id            *string            `json:"id,omitempty"`
	Name          *string            `json:"name,omitempty"`
	ProductSet    *ProductSetBody    `json:"product_set,omitempty"`
	Status        *string            `json:"status,omitempty"`
	UpdatedAt     *int               `json:"updated_at,omitempty"`
}

// AdGroupsResource is the AdGroupsResource model.
type AdGroupsResource struct {
	Data    []AdGroupItemBody `json:"data,omitempty"`
	FirstId *string           `json:"first_id,omitempty"`
	HasMore *bool             `json:"has_more,omitempty"`
	LastId  *string           `json:"last_id,omitempty"`
	Object  *string           `json:"object,omitempty"`
}

// AdItemBody is the AdItemBody model.
type AdItemBody struct {
	CreatedAt    *int                             `json:"created_at,omitempty"`
	Creative     *ConversationalBottomOtmSpecBody `json:"creative,omitempty"`
	Id           *string                          `json:"id,omitempty"`
	Name         *string                          `json:"name,omitempty"`
	Review       *ReviewBody                      `json:"review,omitempty"`
	ReviewStatus *string                          `json:"review_status,omitempty"`
	Status       *string                          `json:"status,omitempty"`
	UpdatedAt    *int                             `json:"updated_at,omitempty"`
}

// AdsResource is the AdsResource model.
type AdsResource struct {
	Data    []AdItemBody `json:"data,omitempty"`
	FirstId *string      `json:"first_id,omitempty"`
	HasMore *bool        `json:"has_more,omitempty"`
	LastId  *string      `json:"last_id,omitempty"`
	Object  *string      `json:"object,omitempty"`
}

// BiddingConfigBody is the BiddingConfigBody model.
type BiddingConfigBody struct {
	BillingEventType             *string                           `json:"billing_event_type,omitempty"`
	CustomAudienceBidMultipliers []CustomAudienceBidMultiplierBody `json:"custom_audience_bid_multipliers,omitempty"`
	MaxBidMicros                 *int                              `json:"max_bid_micros,omitempty"`
}

// BiddingConfigParams is the BiddingConfigParams model.
type BiddingConfigParams struct {
	BillingEventType             *string                             `json:"billing_event_type,omitempty"`
	CustomAudienceBidMultipliers []CustomAudienceBidMultiplierParams `json:"custom_audience_bid_multipliers,omitempty"`
	MaxBidMicros                 *int                                `json:"max_bid_micros,omitempty"`
}

// BudgetBody is the BudgetBody model.
type BudgetBody struct {
	DailySpendLimitMicros    *int `json:"daily_spend_limit_micros,omitempty"`
	LifetimeSpendLimitMicros *int `json:"lifetime_spend_limit_micros,omitempty"`
}

// BudgetParams is the BudgetParams model.
type BudgetParams struct {
	DailySpendLimitMicros    *int `json:"daily_spend_limit_micros,omitempty"`
	LifetimeSpendLimitMicros *int `json:"lifetime_spend_limit_micros,omitempty"`
}

// CampaignItemBody is the CampaignItemBody model.
type CampaignItemBody struct {
	BiddingType               *string        `json:"bidding_type,omitempty"`
	Budget                    *BudgetBody    `json:"budget,omitempty"`
	ConversionEventSettingIds []string       `json:"conversion_event_setting_ids,omitempty"`
	CreatedAt                 *int           `json:"created_at,omitempty"`
	Description               *string        `json:"description,omitempty"`
	EndTime                   *int           `json:"end_time,omitempty"`
	Id                        *string        `json:"id,omitempty"`
	Mode                      *string        `json:"mode,omitempty"`
	Name                      *string        `json:"name,omitempty"`
	StartTime                 *int           `json:"start_time,omitempty"`
	Status                    *string        `json:"status,omitempty"`
	Targeting                 *TargetingBody `json:"targeting,omitempty"`
	UpdatedAt                 *int           `json:"updated_at,omitempty"`
}

// CampaignsResource is the CampaignsResource model.
type CampaignsResource struct {
	Data    []CampaignItemBody `json:"data,omitempty"`
	FirstId *string            `json:"first_id,omitempty"`
	HasMore *bool              `json:"has_more,omitempty"`
	LastId  *string            `json:"last_id,omitempty"`
	Object  *string            `json:"object,omitempty"`
}

// ClientDataSourceItemResource is the ClientDataSourceItemResource model.
type ClientDataSourceItemResource struct {
	AutomaticAdvancedMatchingEnabled *bool   `json:"automatic_advanced_matching_enabled,omitempty"`
	ClientType                       *string `json:"client_type,omitempty"`
	Id                               *string `json:"id,omitempty"`
	Name                             *string `json:"name,omitempty"`
	PixelId                          *string `json:"pixel_id,omitempty"`
}

// ConversationalBottomOtmSpecBody is the ConversationalBottomOtmSpecBody model.
type ConversationalBottomOtmSpecBody struct {
	Body      *string `json:"body,omitempty"`
	FileId    *string `json:"file_id,omitempty"`
	ImageUrl  *string `json:"image_url,omitempty"`
	Price     *string `json:"price,omitempty"`
	TargetUrl *string `json:"target_url,omitempty"`
	Title     *string `json:"title,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// ConversionApiKeyResource is the ConversionApiKeyResource model.
type ConversionApiKeyResource struct {
	ApiKey *string `json:"api_key,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// ConversionEventSettingCampaignBody is the ConversionEventSettingCampaignBody model.
type ConversionEventSettingCampaignBody struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ConversionEventSettingItemResource is the ConversionEventSettingItemResource model.
type ConversionEventSettingItemResource struct {
	AdAccountId           *string                              `json:"ad_account_id,omitempty"`
	Archived              *bool                                `json:"archived,omitempty"`
	AttributionWindowDays *int                                 `json:"attribution_window_days,omitempty"`
	Campaigns             []ConversionEventSettingCampaignBody `json:"campaigns,omitempty"`
	CustomEventName       *string                              `json:"custom_event_name,omitempty"`
	EventType             *string                              `json:"event_type,omitempty"`
	Id                    *string                              `json:"id,omitempty"`
	Name                  *string                              `json:"name,omitempty"`
	SourceIds             []string                             `json:"source_ids,omitempty"`
	Sources               []ConversionEventSettingSourceBody   `json:"sources,omitempty"`
	Version               *int                                 `json:"version,omitempty"`
}

// ConversionEventSettingSourceBody is the ConversionEventSettingSourceBody model.
type ConversionEventSettingSourceBody struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// ConversionSummaryRowBody is the ConversionSummaryRowBody model.
type ConversionSummaryRowBody struct {
	ClickThroughConversions *int    `json:"click_through_conversions,omitempty"`
	Conversions             *int    `json:"conversions,omitempty"`
	EntityId                *string `json:"entity_id,omitempty"`
	ViewThroughConversions  *int    `json:"view_through_conversions,omitempty"`
}

// ConversionSummaryRowsResource is the ConversionSummaryRowsResource model.
type ConversionSummaryRowsResource struct {
	Count  *int                       `json:"count,omitempty"`
	Data   []ConversionSummaryRowBody `json:"data,omitempty"`
	Object *string                    `json:"object,omitempty"`
}

// CreateAdCreativeParams is the CreateAdCreativeParams model.
type CreateAdCreativeParams struct {
	Body      *string `json:"body,omitempty"`
	FileId    *string `json:"file_id,omitempty"`
	Price     *string `json:"price,omitempty"`
	TargetUrl *string `json:"target_url,omitempty"`
	Title     *string `json:"title,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// CustomAudienceBidMultiplierBody is the CustomAudienceBidMultiplierBody model.
type CustomAudienceBidMultiplierBody struct {
	BidMultiplierMicros *int    `json:"bid_multiplier_micros,omitempty"`
	CustomAudienceId    *string `json:"custom_audience_id,omitempty"`
}

// CustomAudienceBidMultiplierParams is the CustomAudienceBidMultiplierParams model.
type CustomAudienceBidMultiplierParams struct {
	BidMultiplierMicros *int    `json:"bid_multiplier_micros,omitempty"`
	CustomAudienceId    *string `json:"custom_audience_id,omitempty"`
}

// CustomAudienceItemBody is the CustomAudienceItemBody model.
type CustomAudienceItemBody struct {
	CreatedAt                    *int    `json:"created_at,omitempty"`
	Description                  *string `json:"description,omitempty"`
	HashSpecVersion              *string `json:"hash_spec_version,omitempty"`
	Id                           *string `json:"id,omitempty"`
	InvalidIdentifierCountRange  *string `json:"invalid_identifier_count_range,omitempty"`
	MatchedIdentifierCountRange  *string `json:"matched_identifier_count_range,omitempty"`
	Name                         *string `json:"name,omitempty"`
	Status                       *string `json:"status,omitempty"`
	UpdatedAt                    *int    `json:"updated_at,omitempty"`
	UploadedIdentifierCountRange *string `json:"uploaded_identifier_count_range,omitempty"`
}

// CustomAudienceMemberParam is the CustomAudienceMemberParam model.
type CustomAudienceMemberParam struct {
	IdentifierType *string `json:"identifier_type,omitempty"`
	Value          *string `json:"value,omitempty"`
}

// CustomAudiencesResource is the CustomAudiencesResource model.
type CustomAudiencesResource struct {
	Data    []CustomAudienceItemBody `json:"data,omitempty"`
	FirstId *string                  `json:"first_id,omitempty"`
	HasMore *bool                    `json:"has_more,omitempty"`
	LastId  *string                  `json:"last_id,omitempty"`
	Object  *string                  `json:"object,omitempty"`
}

// GeoLookupEntry is the GeoLookupEntry model.
type GeoLookupEntry struct {
	CanonicalName *string `json:"canonical_name,omitempty"`
	CountryCode   *string `json:"country_code,omitempty"`
	Id            *string `json:"id,omitempty"`
	Name          *string `json:"name,omitempty"`
	ParentCountry *string `json:"parent_country,omitempty"`
	ParentId      *string `json:"parent_id,omitempty"`
	RegionCode    *string `json:"region_code,omitempty"`
	Type          *string `json:"type,omitempty"`
}

// GeoLookupSearchResource is the GeoLookupSearchResource model.
type GeoLookupSearchResource struct {
	Count   *int             `json:"count,omitempty"`
	Query   *string          `json:"query,omitempty"`
	Results []GeoLookupEntry `json:"results,omitempty"`
}

// InsightItemBody is the InsightItemBody model.
type InsightItemBody struct {
	AdAccountBudgetDaily    *float64 `json:"ad_account_budget_daily,omitempty"`
	AdAccountBudgetLifetime *float64 `json:"ad_account_budget_lifetime,omitempty"`
	AdAccountClicks         *int     `json:"ad_account_clicks,omitempty"`
	AdAccountCpc            *float64 `json:"ad_account_cpc,omitempty"`
	AdAccountCpm            *float64 `json:"ad_account_cpm,omitempty"`
	AdAccountCtr            *float64 `json:"ad_account_ctr,omitempty"`
	AdAccountId             *string  `json:"ad_account_id,omitempty"`
	AdAccountImpressions    *int     `json:"ad_account_impressions,omitempty"`
	AdAccountName           *string  `json:"ad_account_name,omitempty"`
	AdAccountSpend          *float64 `json:"ad_account_spend,omitempty"`
	AdAccountUrl            *string  `json:"ad_account_url,omitempty"`
	AdClicks                *int     `json:"ad_clicks,omitempty"`
	AdCopy                  *string  `json:"ad_copy,omitempty"`
	AdCpc                   *float64 `json:"ad_cpc,omitempty"`
	AdCpm                   *float64 `json:"ad_cpm,omitempty"`
	AdCtr                   *float64 `json:"ad_ctr,omitempty"`
	AdGroupClicks           *int     `json:"ad_group_clicks,omitempty"`
	AdGroupCpc              *float64 `json:"ad_group_cpc,omitempty"`
	AdGroupCpm              *float64 `json:"ad_group_cpm,omitempty"`
	AdGroupCtr              *float64 `json:"ad_group_ctr,omitempty"`
	AdGroupDescription      *string  `json:"ad_group_description,omitempty"`
	AdGroupId               *string  `json:"ad_group_id,omitempty"`
	AdGroupImpressions      *int     `json:"ad_group_impressions,omitempty"`
	AdGroupName             *string  `json:"ad_group_name,omitempty"`
	AdGroupSpend            *float64 `json:"ad_group_spend,omitempty"`
	AdGroupStatus           *string  `json:"ad_group_status,omitempty"`
	AdId                    *string  `json:"ad_id,omitempty"`
	AdImpressions           *int     `json:"ad_impressions,omitempty"`
	AdLink                  *string  `json:"ad_link,omitempty"`
	AdName                  *string  `json:"ad_name,omitempty"`
	AdReviewStatus          *string  `json:"ad_review_status,omitempty"`
	AdSpend                 *float64 `json:"ad_spend,omitempty"`
	AdStatus                *string  `json:"ad_status,omitempty"`
	AdTitle                 *string  `json:"ad_title,omitempty"`
	CampaignBudgetDaily     *float64 `json:"campaign_budget_daily,omitempty"`
	CampaignBudgetLifetime  *float64 `json:"campaign_budget_lifetime,omitempty"`
	CampaignClicks          *int     `json:"campaign_clicks,omitempty"`
	CampaignCpc             *float64 `json:"campaign_cpc,omitempty"`
	CampaignCpm             *float64 `json:"campaign_cpm,omitempty"`
	CampaignCtr             *float64 `json:"campaign_ctr,omitempty"`
	CampaignDescription     *string  `json:"campaign_description,omitempty"`
	CampaignEndTime         *string  `json:"campaign_end_time,omitempty"`
	CampaignId              *string  `json:"campaign_id,omitempty"`
	CampaignImpressions     *int     `json:"campaign_impressions,omitempty"`
	CampaignName            *string  `json:"campaign_name,omitempty"`
	CampaignSpend           *float64 `json:"campaign_spend,omitempty"`
	CampaignStartTime       *string  `json:"campaign_start_time,omitempty"`
	CampaignStatus          *string  `json:"campaign_status,omitempty"`
	Clicks                  *int     `json:"clicks,omitempty"`
	CountryClicks           *int     `json:"country_clicks,omitempty"`
	CountryCpc              *float64 `json:"country_cpc,omitempty"`
	CountryCpm              *float64 `json:"country_cpm,omitempty"`
	CountryCtr              *float64 `json:"country_ctr,omitempty"`
	CountryImpressions      *int     `json:"country_impressions,omitempty"`
	CountryName             *string  `json:"country_name,omitempty"`
	CountrySpend            *float64 `json:"country_spend,omitempty"`
	Cpc                     *float64 `json:"cpc,omitempty"`
	Cpm                     *float64 `json:"cpm,omitempty"`
	Ctr                     *float64 `json:"ctr,omitempty"`
	DataStatus              *string  `json:"data_status,omitempty"`
	DeviceClicks            *int     `json:"device_clicks,omitempty"`
	DeviceCpc               *float64 `json:"device_cpc,omitempty"`
	DeviceCpm               *float64 `json:"device_cpm,omitempty"`
	DeviceCtr               *float64 `json:"device_ctr,omitempty"`
	DeviceImpressions       *int     `json:"device_impressions,omitempty"`
	DeviceSpend             *float64 `json:"device_spend,omitempty"`
	DeviceType              *string  `json:"device_type,omitempty"`
	EndTime                 *int     `json:"end_time,omitempty"`
	Id                      *string  `json:"id,omitempty"`
	Impressions             *int     `json:"impressions,omitempty"`
	ItemId                  *string  `json:"item_id,omitempty"`
	ProductAvailability     *string  `json:"product_availability,omitempty"`
	ProductBody             *string  `json:"product_body,omitempty"`
	ProductBrand            *string  `json:"product_brand,omitempty"`
	ProductClicks           *int     `json:"product_clicks,omitempty"`
	ProductCpc              *float64 `json:"product_cpc,omitempty"`
	ProductCpm              *float64 `json:"product_cpm,omitempty"`
	ProductCtr              *float64 `json:"product_ctr,omitempty"`
	ProductDescription      *string  `json:"product_description,omitempty"`
	ProductFeedId           *string  `json:"product_feed_id,omitempty"`
	ProductImageUrl         *string  `json:"product_image_url,omitempty"`
	ProductImpressions      *int     `json:"product_impressions,omitempty"`
	ProductPrice            *string  `json:"product_price,omitempty"`
	ProductSellerName       *string  `json:"product_seller_name,omitempty"`
	ProductSpend            *float64 `json:"product_spend,omitempty"`
	ProductTargetUrl        *string  `json:"product_target_url,omitempty"`
	ProductTitle            *string  `json:"product_title,omitempty"`
	ReadableTime            *string  `json:"readable_time,omitempty"`
	Spend                   *float64 `json:"spend,omitempty"`
	StartTime               *int     `json:"start_time,omitempty"`
	Timezone                *string  `json:"timezone,omitempty"`
}

// InsightsResource is the InsightsResource model.
type InsightsResource struct {
	Count   *int              `json:"count,omitempty"`
	Data    []InsightItemBody `json:"data,omitempty"`
	FirstId *string           `json:"first_id,omitempty"`
	HasMore *bool             `json:"has_more,omitempty"`
	LastId  *string           `json:"last_id,omitempty"`
	Object  *string           `json:"object,omitempty"`
}

// ListConversionEventSettingsResource is the ListConversionEventSettingsResource model.
type ListConversionEventSettingsResource struct {
	Data    []ConversionEventSettingItemResource `json:"data,omitempty"`
	FirstId *string                              `json:"first_id,omitempty"`
	HasMore *bool                                `json:"has_more,omitempty"`
	LastId  *string                              `json:"last_id,omitempty"`
	Object  *string                              `json:"object,omitempty"`
}

// ProductSetBody is the ProductSetBody model.
type ProductSetBody struct {
	Filters       []ProductSetFilterBody `json:"filters,omitempty"`
	ProductFeedId *string                `json:"product_feed_id,omitempty"`
}

// ProductSetFilterBody is the ProductSetFilterBody model.
type ProductSetFilterBody struct {
	Field    *string  `json:"field,omitempty"`
	Operator *string  `json:"operator,omitempty"`
	Values   []string `json:"values,omitempty"`
}

// ProductSetFilterParams is the ProductSetFilterParams model.
type ProductSetFilterParams struct {
	Field    *string  `json:"field,omitempty"`
	Operator *string  `json:"operator,omitempty"`
	Values   []string `json:"values,omitempty"`
}

// ProductSetParams is the ProductSetParams model.
type ProductSetParams struct {
	Filters       []ProductSetFilterParams `json:"filters,omitempty"`
	ProductFeedId *string                  `json:"product_feed_id,omitempty"`
}

// ReviewBody is the ReviewBody model.
type ReviewBody struct {
	Reason *string `json:"reason,omitempty"`
	Status *string `json:"status,omitempty"`
}

// TargetingBody is the TargetingBody model.
type TargetingBody struct {
	CustomAudiences         *TargetingCustomAudiencesBody `json:"custom_audiences,omitempty"`
	ExcludedCustomAudiences *TargetingCustomAudiencesBody `json:"excluded_custom_audiences,omitempty"`
	Locations               *TargetingGeoLocationsBody    `json:"locations,omitempty"`
}

// TargetingCustomAudiencesBody is the TargetingCustomAudiencesBody model.
type TargetingCustomAudiencesBody struct {
	Ids []string `json:"ids,omitempty"`
}

// TargetingCustomAudiencesParams is the TargetingCustomAudiencesParams model.
type TargetingCustomAudiencesParams struct {
	Ids []string `json:"ids,omitempty"`
}

// TargetingGeoLocationBody is the TargetingGeoLocationBody model.
type TargetingGeoLocationBody struct {
	CountryCode *string `json:"country_code,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	RegionCode  *string `json:"region_code,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// TargetingGeoLocationParams is the TargetingGeoLocationParams model.
type TargetingGeoLocationParams struct {
	CountryCode *string `json:"country_code,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	RegionCode  *string `json:"region_code,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// TargetingGeoLocationsBody is the TargetingGeoLocationsBody model.
type TargetingGeoLocationsBody struct {
	Countries []string                   `json:"countries,omitempty"`
	Include   []TargetingGeoLocationBody `json:"include,omitempty"`
}

// TargetingGeoLocationsParams is the TargetingGeoLocationsParams model.
type TargetingGeoLocationsParams struct {
	Countries []string                     `json:"countries,omitempty"`
	Include   []TargetingGeoLocationParams `json:"include,omitempty"`
}

// TargetingParams is the TargetingParams model.
type TargetingParams struct {
	CustomAudiences         *TargetingCustomAudiencesParams `json:"custom_audiences,omitempty"`
	ExcludedCustomAudiences *TargetingCustomAudiencesParams `json:"excluded_custom_audiences,omitempty"`
	Locations               *TargetingGeoLocationsParams    `json:"locations,omitempty"`
}

// UpdateAdCreativeParams is the UpdateAdCreativeParams model.
type UpdateAdCreativeParams struct {
	Body      *string `json:"body,omitempty"`
	FileId    *string `json:"file_id,omitempty"`
	Price     *string `json:"price,omitempty"`
	TargetUrl *string `json:"target_url,omitempty"`
	Title     *string `json:"title,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// UploadImageResource is the UploadImageResource model.
type UploadImageResource struct {
	FileId *string `json:"file_id,omitempty"`
}
