// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"encoding/json"
	"github.com/pax-beehive/connector"
)

var connectorActionManifest = [...]connector.ActionDescriptor{
	{
		Provider:      "facebook",
		Method:        "CreateComment",
		HTTPMethod:    "POST",
		RequestType:   "CreateCommentRequest",
		ResponseType:  "CreateCommentResponse",
		RequiredScope: "actions:facebook:CreateComment",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "facebook",
		Method:        "DeleteComment",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteCommentRequest",
		ResponseType:  "DeleteCommentResponse",
		RequiredScope: "actions:facebook:DeleteComment",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "facebook",
		Method:        "HideComment",
		HTTPMethod:    "POST",
		RequestType:   "HideCommentRequest",
		ResponseType:  "HideCommentResponse",
		RequiredScope: "actions:facebook:HideComment",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "facebook",
		Method:        "ListComments",
		HTTPMethod:    "GET",
		RequestType:   "ListCommentsRequest",
		ResponseType:  "ListCommentsResponse",
		RequiredScope: "actions:facebook:ListComments",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "GetPageInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetPageInsightsRequest",
		ResponseType:  "GetPageInsightsResponse",
		RequiredScope: "actions:facebook:GetPageInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "GetPostInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetPostInsightsRequest",
		ResponseType:  "GetPostInsightsResponse",
		RequiredScope: "actions:facebook:GetPostInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "GetPage",
		HTTPMethod:    "GET",
		RequestType:   "GetPageRequest",
		ResponseType:  "GetPageResponse",
		RequiredScope: "actions:facebook:GetPage",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "ListManagedPages",
		HTTPMethod:    "GET",
		RequestType:   "ListManagedPagesRequest",
		ResponseType:  "ListManagedPagesResponse",
		RequiredScope: "actions:facebook:ListManagedPages",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "CreatePagePhoto",
		HTTPMethod:    "POST",
		RequestType:   "CreatePagePhotoRequest",
		ResponseType:  "CreatePagePhotoResponse",
		RequiredScope: "actions:facebook:CreatePagePhoto",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "facebook",
		Method:        "CreatePagePost",
		HTTPMethod:    "POST",
		RequestType:   "CreatePagePostRequest",
		ResponseType:  "CreatePagePostResponse",
		RequiredScope: "actions:facebook:CreatePagePost",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "facebook",
		Method:        "CreatePageVideo",
		HTTPMethod:    "POST",
		RequestType:   "CreatePageVideoRequest",
		ResponseType:  "CreatePageVideoResponse",
		RequiredScope: "actions:facebook:CreatePageVideo",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "facebook",
		Method:        "DeletePost",
		HTTPMethod:    "DELETE",
		RequestType:   "DeletePostRequest",
		ResponseType:  "DeletePostResponse",
		RequiredScope: "actions:facebook:DeletePost",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "facebook",
		Method:        "GetPost",
		HTTPMethod:    "GET",
		RequestType:   "GetPostRequest",
		ResponseType:  "GetPostResponse",
		RequiredScope: "actions:facebook:GetPost",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "ListPagePosts",
		HTTPMethod:    "GET",
		RequestType:   "ListPagePostsRequest",
		ResponseType:  "ListPagePostsResponse",
		RequiredScope: "actions:facebook:ListPagePosts",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "facebook",
		Method:        "UpdatePost",
		HTTPMethod:    "POST",
		RequestType:   "UpdatePostRequest",
		ResponseType:  "UpdatePostResponse",
		RequiredScope: "actions:facebook:UpdatePost",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
	"CreateComment":    invokeCreateCommentAction,
	"DeleteComment":    invokeDeleteCommentAction,
	"HideComment":      invokeHideCommentAction,
	"ListComments":     invokeListCommentsAction,
	"GetPageInsights":  invokeGetPageInsightsAction,
	"GetPostInsights":  invokeGetPostInsightsAction,
	"GetPage":          invokeGetPageAction,
	"ListManagedPages": invokeListManagedPagesAction,
	"CreatePagePhoto":  invokeCreatePagePhotoAction,
	"CreatePagePost":   invokeCreatePagePostAction,
	"CreatePageVideo":  invokeCreatePageVideoAction,
	"DeletePost":       invokeDeletePostAction,
	"GetPost":          invokeGetPostAction,
	"ListPagePosts":    invokeListPagePostsAction,
	"UpdatePost":       invokeUpdatePostAction,
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "facebook" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}

func invokeCreateCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbObjectId    string  `json:"fbObjectId,omitempty"`
		Message       *string `json:"message,omitempty"`
		AttachmentUrl *string `json:"attachment_url,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "CreateComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateComment(ctx, &CreateCommentRequest{
		FbObjectId:    wire.FbObjectId,
		Message:       wire.Message,
		AttachmentUrl: wire.AttachmentUrl,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbCommentId string `json:"fbCommentId,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "DeleteComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteComment(ctx, &DeleteCommentRequest{
		FbCommentId: wire.FbCommentId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeHideCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbCommentId string `json:"fbCommentId,omitempty"`
		IsHidden    *bool  `json:"is_hidden,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "HideComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.HideComment(ctx, &HideCommentRequest{
		FbCommentId: wire.FbCommentId,
		IsHidden:    wire.IsHidden,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListCommentsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbObjectId string  `json:"fbObjectId,omitempty"`
		Fields     *string `json:"fields,omitempty"`
		Limit      *int    `json:"limit,omitempty"`
		After      *string `json:"after,omitempty"`
		Filter     *string `json:"filter,omitempty"`
		Order      *string `json:"order,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "ListComments", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListComments(ctx, &ListCommentsRequest{
		FbObjectId: wire.FbObjectId,
		Fields:     wire.Fields,
		Limit:      wire.Limit,
		After:      wire.After,
		Filter:     wire.Filter,
		Order:      wire.Order,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetPageInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		PageId     string  `json:"pageId,omitempty"`
		Metric     *string `json:"metric,omitempty"`
		Period     *string `json:"period,omitempty"`
		DatePreset *string `json:"date_preset,omitempty"`
		Since      *int64  `json:"since,omitempty"`
		Until      *int64  `json:"until,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "GetPageInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetPageInsights(ctx, &GetPageInsightsRequest{
		PageId:     wire.PageId,
		Metric:     wire.Metric,
		Period:     wire.Period,
		DatePreset: wire.DatePreset,
		Since:      wire.Since,
		Until:      wire.Until,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetPostInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbPostId string  `json:"fbPostId,omitempty"`
		Metric   *string `json:"metric,omitempty"`
		Period   *string `json:"period,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "GetPostInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetPostInsights(ctx, &GetPostInsightsRequest{
		FbPostId: wire.FbPostId,
		Metric:   wire.Metric,
		Period:   wire.Period,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetPageAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbPageId string  `json:"fbPageId,omitempty"`
		Fields   *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "GetPage", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetPage(ctx, &GetPageRequest{
		FbPageId: wire.FbPageId,
		Fields:   wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListManagedPagesAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Fields *string `json:"fields,omitempty"`
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "ListManagedPages", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListManagedPages(ctx, &ListManagedPagesRequest{
		Fields: wire.Fields,
		Limit:  wire.Limit,
		After:  wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreatePagePhotoAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		PageId               string  `json:"pageId,omitempty"`
		Url                  *string `json:"url,omitempty"`
		Message              *string `json:"message,omitempty"`
		Published            *bool   `json:"published,omitempty"`
		ScheduledPublishTime *int64  `json:"scheduled_publish_time,omitempty"`
		Temporary            *bool   `json:"temporary,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "CreatePagePhoto", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreatePagePhoto(ctx, &CreatePagePhotoRequest{
		PageId:               wire.PageId,
		Url:                  wire.Url,
		Message:              wire.Message,
		Published:            wire.Published,
		ScheduledPublishTime: wire.ScheduledPublishTime,
		Temporary:            wire.Temporary,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreatePagePostAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		PageId               string  `json:"pageId,omitempty"`
		Message              *string `json:"message,omitempty"`
		Link                 *string `json:"link,omitempty"`
		Published            *bool   `json:"published,omitempty"`
		ScheduledPublishTime *int64  `json:"scheduled_publish_time,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "CreatePagePost", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreatePagePost(ctx, &CreatePagePostRequest{
		PageId:               wire.PageId,
		Message:              wire.Message,
		Link:                 wire.Link,
		Published:            wire.Published,
		ScheduledPublishTime: wire.ScheduledPublishTime,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreatePageVideoAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		PageId               string  `json:"pageId,omitempty"`
		FileUrl              *string `json:"file_url,omitempty"`
		Title                *string `json:"title,omitempty"`
		Description          *string `json:"description,omitempty"`
		Published            *bool   `json:"published,omitempty"`
		ScheduledPublishTime *int64  `json:"scheduled_publish_time,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "CreatePageVideo", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreatePageVideo(ctx, &CreatePageVideoRequest{
		PageId:               wire.PageId,
		FileUrl:              wire.FileUrl,
		Title:                wire.Title,
		Description:          wire.Description,
		Published:            wire.Published,
		ScheduledPublishTime: wire.ScheduledPublishTime,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeletePostAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbPostId string `json:"fbPostId,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "DeletePost", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeletePost(ctx, &DeletePostRequest{
		FbPostId: wire.FbPostId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetPostAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbPostId string  `json:"fbPostId,omitempty"`
		Fields   *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "GetPost", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetPost(ctx, &GetPostRequest{
		FbPostId: wire.FbPostId,
		Fields:   wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListPagePostsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		PageId string  `json:"pageId,omitempty"`
		Fields *string `json:"fields,omitempty"`
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
		Before *string `json:"before,omitempty"`
		Since  *int64  `json:"since,omitempty"`
		Until  *int64  `json:"until,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "ListPagePosts", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListPagePosts(ctx, &ListPagePostsRequest{
		PageId: wire.PageId,
		Fields: wire.Fields,
		Limit:  wire.Limit,
		After:  wire.After,
		Before: wire.Before,
		Since:  wire.Since,
		Until:  wire.Until,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdatePostAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		FbPostId string  `json:"fbPostId,omitempty"`
		Message  *string `json:"message,omitempty"`
		IsHidden *bool   `json:"is_hidden,omitempty"`
	}
	if err := connector.DecodeActionRequest("facebook", "UpdatePost", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdatePost(ctx, &UpdatePostRequest{
		FbPostId: wire.FbPostId,
		Message:  wire.Message,
		IsHidden: wire.IsHidden,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
