// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateCommentRequest holds the parameters for CreateComment.
type CreateCommentRequest struct {
	FbObjectId    string  `json:"-" path:"fbObjectId"`
	Message       *string `json:"-" query:"message"`
	AttachmentUrl *string `json:"-" query:"attachment_url"`
}

// CreateComment calls POST /{version}/{fbObjectId}/comments.
func (c *Client) CreateComment(ctx context.Context, req *CreateCommentRequest) (*CreateCommentResponse, error) {
	if req == nil {
		req = &CreateCommentRequest{}
	}
	out := &CreateCommentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{fbObjectId}/comments",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteCommentRequest holds the parameters for DeleteComment.
type DeleteCommentRequest struct {
	FbCommentId string `json:"-" path:"fbCommentId"`
}

// DeleteComment calls DELETE /{version}/{fbCommentId}.
func (c *Client) DeleteComment(ctx context.Context, req *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	if req == nil {
		req = &DeleteCommentRequest{}
	}
	out := &DeleteCommentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{fbCommentId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HideCommentRequest holds the parameters for HideComment.
type HideCommentRequest struct {
	FbCommentId string `json:"-" path:"fbCommentId"`
	IsHidden    *bool  `json:"-" query:"is_hidden"`
}

// HideComment calls POST /{version}/{fbCommentId}.
func (c *Client) HideComment(ctx context.Context, req *HideCommentRequest) (*HideCommentResponse, error) {
	if req == nil {
		req = &HideCommentRequest{}
	}
	out := &HideCommentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{fbCommentId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListCommentsRequest holds the parameters for ListComments.
type ListCommentsRequest struct {
	FbObjectId string  `json:"-" path:"fbObjectId"`
	Fields     *string `json:"-" query:"fields"`
	Limit      *int    `json:"-" query:"limit"`
	After      *string `json:"-" query:"after"`
	Filter     *string `json:"-" query:"filter"`
	Order      *string `json:"-" query:"order"`
}

// ListCommentsResponse is the response type of ListComments.
type ListCommentsResponse = CommentList

// ListComments calls GET /{version}/{fbObjectId}/comments.
func (c *Client) ListComments(ctx context.Context, req *ListCommentsRequest) (*ListCommentsResponse, error) {
	if req == nil {
		req = &ListCommentsRequest{}
	}
	out := &ListCommentsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{fbObjectId}/comments",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
