// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetPageInsightsRequest holds the parameters for GetPageInsights.
type GetPageInsightsRequest struct {
	PageId     string  `json:"-" path:"pageId"`
	Metric     *string `json:"-" query:"metric"`
	Period     *string `json:"-" query:"period"`
	DatePreset *string `json:"-" query:"date_preset"`
	Since      *int64  `json:"-" query:"since"`
	Until      *int64  `json:"-" query:"until"`
}

// GetPageInsightsResponse is the response type of GetPageInsights.
type GetPageInsightsResponse = InsightList

// GetPageInsights calls GET /{version}/{pageId}/insights.
func (c *Client) GetPageInsights(ctx context.Context, req *GetPageInsightsRequest) (*GetPageInsightsResponse, error) {
	if req == nil {
		req = &GetPageInsightsRequest{}
	}
	out := &GetPageInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{pageId}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPostInsightsRequest holds the parameters for GetPostInsights.
type GetPostInsightsRequest struct {
	FbPostId string  `json:"-" path:"fbPostId"`
	Metric   *string `json:"-" query:"metric"`
	Period   *string `json:"-" query:"period"`
}

// GetPostInsightsResponse is the response type of GetPostInsights.
type GetPostInsightsResponse = InsightList

// GetPostInsights calls GET /{version}/{fbPostId}/insights.
func (c *Client) GetPostInsights(ctx context.Context, req *GetPostInsightsRequest) (*GetPostInsightsResponse, error) {
	if req == nil {
		req = &GetPostInsightsRequest{}
	}
	out := &GetPostInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{fbPostId}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
