// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetPageRequest holds the parameters for GetPage.
type GetPageRequest struct {
	FbPageId string  `json:"-" path:"fbPageId"`
	Fields   *string `json:"-" query:"fields"`
}

// GetPageResponse is the response type of GetPage.
type GetPageResponse = Page

// GetPage calls GET /{version}/{fbPageId}.
func (c *Client) GetPage(ctx context.Context, req *GetPageRequest) (*GetPageResponse, error) {
	if req == nil {
		req = &GetPageRequest{}
	}
	out := &GetPageResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{fbPageId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListManagedPagesRequest holds the parameters for ListManagedPages.
type ListManagedPagesRequest struct {
	Fields *string `json:"-" query:"fields"`
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
}

// ListManagedPages calls GET /{version}/me/accounts.
func (c *Client) ListManagedPages(ctx context.Context, req *ListManagedPagesRequest) (*ListManagedPagesResponse, error) {
	if req == nil {
		req = &ListManagedPagesRequest{}
	}
	out := &ListManagedPagesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/me/accounts",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
