// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreatePagePhotoRequest holds the parameters for CreatePagePhoto.
type CreatePagePhotoRequest struct {
	PageId               string  `json:"-" path:"pageId"`
	Url                  *string `json:"-" query:"url"`
	Message              *string `json:"-" query:"message"`
	Published            *bool   `json:"-" query:"published"`
	ScheduledPublishTime *int64  `json:"-" query:"scheduled_publish_time"`
	Temporary            *bool   `json:"-" query:"temporary"`
}

// CreatePagePhoto calls POST /{version}/{pageId}/photos.
func (c *Client) CreatePagePhoto(ctx context.Context, req *CreatePagePhotoRequest) (*CreatePagePhotoResponse, error) {
	if req == nil {
		req = &CreatePagePhotoRequest{}
	}
	out := &CreatePagePhotoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{pageId}/photos",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreatePagePostRequest holds the parameters for CreatePagePost.
type CreatePagePostRequest struct {
	PageId               string  `json:"-" path:"pageId"`
	Message              *string `json:"-" query:"message"`
	Link                 *string `json:"-" query:"link"`
	Published            *bool   `json:"-" query:"published"`
	ScheduledPublishTime *int64  `json:"-" query:"scheduled_publish_time"`
}

// CreatePagePost calls POST /{version}/{pageId}/feed.
func (c *Client) CreatePagePost(ctx context.Context, req *CreatePagePostRequest) (*CreatePagePostResponse, error) {
	if req == nil {
		req = &CreatePagePostRequest{}
	}
	out := &CreatePagePostResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{pageId}/feed",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreatePageVideoRequest holds the parameters for CreatePageVideo.
type CreatePageVideoRequest struct {
	PageId               string  `json:"-" path:"pageId"`
	FileUrl              *string `json:"-" query:"file_url"`
	Title                *string `json:"-" query:"title"`
	Description          *string `json:"-" query:"description"`
	Published            *bool   `json:"-" query:"published"`
	ScheduledPublishTime *int64  `json:"-" query:"scheduled_publish_time"`
}

// CreatePageVideo calls POST /{version}/{pageId}/videos.
func (c *Client) CreatePageVideo(ctx context.Context, req *CreatePageVideoRequest) (*CreatePageVideoResponse, error) {
	if req == nil {
		req = &CreatePageVideoRequest{}
	}
	out := &CreatePageVideoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{pageId}/videos",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeletePostRequest holds the parameters for DeletePost.
type DeletePostRequest struct {
	FbPostId string `json:"-" path:"fbPostId"`
}

// DeletePost calls DELETE /{version}/{fbPostId}.
func (c *Client) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	if req == nil {
		req = &DeletePostRequest{}
	}
	out := &DeletePostResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{fbPostId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPostRequest holds the parameters for GetPost.
type GetPostRequest struct {
	FbPostId string  `json:"-" path:"fbPostId"`
	Fields   *string `json:"-" query:"fields"`
}

// GetPostResponse is the response type of GetPost.
type GetPostResponse = Post

// GetPost calls GET /{version}/{fbPostId}.
func (c *Client) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	if req == nil {
		req = &GetPostRequest{}
	}
	out := &GetPostResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{fbPostId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListPagePostsRequest holds the parameters for ListPagePosts.
type ListPagePostsRequest struct {
	PageId string  `json:"-" path:"pageId"`
	Fields *string `json:"-" query:"fields"`
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
	Before *string `json:"-" query:"before"`
	Since  *int64  `json:"-" query:"since"`
	Until  *int64  `json:"-" query:"until"`
}

// ListPagePostsResponse is the response type of ListPagePosts.
type ListPagePostsResponse = PostList

// ListPagePosts calls GET /{version}/{pageId}/feed.
func (c *Client) ListPagePosts(ctx context.Context, req *ListPagePostsRequest) (*ListPagePostsResponse, error) {
	if req == nil {
		req = &ListPagePostsRequest{}
	}
	out := &ListPagePostsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{pageId}/feed",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdatePostRequest holds the parameters for UpdatePost.
type UpdatePostRequest struct {
	FbPostId string  `json:"-" path:"fbPostId"`
	Message  *string `json:"-" query:"message"`
	IsHidden *bool   `json:"-" query:"is_hidden"`
}

// UpdatePost calls POST /{version}/{fbPostId}.
func (c *Client) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	if req == nil {
		req = &UpdatePostRequest{}
	}
	out := &UpdatePostResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{fbPostId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
