// Code generated by connector-gen. DO NOT EDIT.

package facebook

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
	{
		name:   "CreateComment",
		method: "POST",
		path:   "/v23.0//comments",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateComment(ctx, &CreateCommentRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateComment(ctx, nil)
		},
	},
	{
		name:   "DeleteComment",
		method: "DELETE",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteComment(ctx, &DeleteCommentRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteComment(ctx, nil)
		},
	},
	{
		name:   "HideComment",
		method: "POST",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.HideComment(ctx, &HideCommentRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.HideComment(ctx, nil)
		},
	},
	{
		name:   "ListComments",
		method: "GET",
		path:   "/v23.0//comments",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListComments(ctx, &ListCommentsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListComments(ctx, nil)
		},
	},
	{
		name:   "GetPageInsights",
		method: "GET",
		path:   "/v23.0//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPageInsights(ctx, &GetPageInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPageInsights(ctx, nil)
		},
	},
	{
		name:   "GetPostInsights",
		method: "GET",
		path:   "/v23.0//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPostInsights(ctx, &GetPostInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPostInsights(ctx, nil)
		},
	},
	{
		name:   "GetPage",
		method: "GET",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPage(ctx, &GetPageRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPage(ctx, nil)
		},
	},
	{
		name:   "ListManagedPages",
		method: "GET",
		path:   "/v23.0/me/accounts",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListManagedPages(ctx, &ListManagedPagesRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListManagedPages(ctx, nil)
		},
	},
	{
		name:   "CreatePagePhoto",
		method: "POST",
		path:   "/v23.0//photos",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePagePhoto(ctx, &CreatePagePhotoRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePagePhoto(ctx, nil)
		},
	},
	{
		name:   "CreatePagePost",
		method: "POST",
		path:   "/v23.0//feed",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePagePost(ctx, &CreatePagePostRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePagePost(ctx, nil)
		},
	},
	{
		name:   "CreatePageVideo",
		method: "POST",
		path:   "/v23.0//videos",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePageVideo(ctx, &CreatePageVideoRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreatePageVideo(ctx, nil)
		},
	},
	{
		name:   "DeletePost",
		method: "DELETE",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeletePost(ctx, &DeletePostRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeletePost(ctx, nil)
		},
	},
	{
		name:   "GetPost",
		method: "GET",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPost(ctx, &GetPostRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetPost(ctx, nil)
		},
	},
	{
		name:   "ListPagePosts",
		method: "GET",
		path:   "/v23.0//feed",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListPagePosts(ctx, &ListPagePostsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListPagePosts(ctx, nil)
		},
	},
	{
		name:   "UpdatePost",
		method: "POST",
		path:   "/v23.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdatePost(ctx, &UpdatePostRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdatePost(ctx, nil)
		},
	},
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
