// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetAdAccountRequest holds the parameters for GetAdAccount.
type GetAdAccountRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Fields      *string `json:"-" query:"fields"`
}

// GetAdAccountResponse is the response type of GetAdAccount.
type GetAdAccountResponse = AdAccount

// GetAdAccount calls GET /{version}/{adAccountId}.
func (c *Client) GetAdAccount(ctx context.Context, req *GetAdAccountRequest) (*GetAdAccountResponse, error) {
	if req == nil {
		req = &GetAdAccountRequest{}
	}
	out := &GetAdAccountResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adAccountId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListAdAccountsRequest holds the parameters for ListAdAccounts.
type ListAdAccountsRequest struct {
	Fields *string `json:"-" query:"fields"`
	Limit  *int    `json:"-" query:"limit"`
	After  *string `json:"-" query:"after"`
}

// ListAdAccountsResponse is the response type of ListAdAccounts.
type ListAdAccountsResponse = AdAccountList

// ListAdAccounts calls GET /{version}/me/adaccounts.
func (c *Client) ListAdAccounts(ctx context.Context, req *ListAdAccountsRequest) (*ListAdAccountsResponse, error) {
	if req == nil {
		req = &ListAdAccountsRequest{}
	}
	out := &ListAdAccountsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/me/adaccounts",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
