// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"encoding/json"
	"github.com/pax-beehive/connector"
)

var connectorActionManifest = [...]connector.ActionDescriptor{
	{
		Provider:      "metaads",
		Method:        "GetAdAccount",
		HTTPMethod:    "GET",
		RequestType:   "GetAdAccountRequest",
		ResponseType:  "GetAdAccountResponse",
		RequiredScope: "actions:metaads:GetAdAccount",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "ListAdAccounts",
		HTTPMethod:    "GET",
		RequestType:   "ListAdAccountsRequest",
		ResponseType:  "ListAdAccountsResponse",
		RequiredScope: "actions:metaads:ListAdAccounts",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "CreateAdSet",
		HTTPMethod:    "POST",
		RequestType:   "CreateAdSetRequest",
		ResponseType:  "CreateAdSetResponse",
		RequiredScope: "actions:metaads:CreateAdSet",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "DeleteAdSet",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteAdSetRequest",
		ResponseType:  "DeleteAdSetResponse",
		RequiredScope: "actions:metaads:DeleteAdSet",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "metaads",
		Method:        "GetAdSet",
		HTTPMethod:    "GET",
		RequestType:   "GetAdSetRequest",
		ResponseType:  "GetAdSetResponse",
		RequiredScope: "actions:metaads:GetAdSet",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "ListAdSets",
		HTTPMethod:    "GET",
		RequestType:   "ListAdSetsRequest",
		ResponseType:  "ListAdSetsResponse",
		RequiredScope: "actions:metaads:ListAdSets",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "UpdateAdSet",
		HTTPMethod:    "POST",
		RequestType:   "UpdateAdSetRequest",
		ResponseType:  "UpdateAdSetResponse",
		RequiredScope: "actions:metaads:UpdateAdSet",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "CreateAd",
		HTTPMethod:    "POST",
		RequestType:   "CreateAdRequest",
		ResponseType:  "CreateAdResponse",
		RequiredScope: "actions:metaads:CreateAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "DeleteAd",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteAdRequest",
		ResponseType:  "DeleteAdResponse",
		RequiredScope: "actions:metaads:DeleteAd",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "metaads",
		Method:        "GetAd",
		HTTPMethod:    "GET",
		RequestType:   "GetAdRequest",
		ResponseType:  "GetAdResponse",
		RequiredScope: "actions:metaads:GetAd",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "ListAds",
		HTTPMethod:    "GET",
		RequestType:   "ListAdsRequest",
		ResponseType:  "ListAdsResponse",
		RequiredScope: "actions:metaads:ListAds",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "UpdateAd",
		HTTPMethod:    "POST",
		RequestType:   "UpdateAdRequest",
		ResponseType:  "UpdateAdResponse",
		RequiredScope: "actions:metaads:UpdateAd",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "CreateCampaign",
		HTTPMethod:    "POST",
		RequestType:   "CreateCampaignRequest",
		ResponseType:  "CreateCampaignResponse",
		RequiredScope: "actions:metaads:CreateCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "DeleteCampaign",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteCampaignRequest",
		ResponseType:  "DeleteCampaignResponse",
		RequiredScope: "actions:metaads:DeleteCampaign",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "metaads",
		Method:        "GetCampaign",
		HTTPMethod:    "GET",
		RequestType:   "GetCampaignRequest",
		ResponseType:  "GetCampaignResponse",
		RequiredScope: "actions:metaads:GetCampaign",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "ListCampaigns",
		HTTPMethod:    "GET",
		RequestType:   "ListCampaignsRequest",
		ResponseType:  "ListCampaignsResponse",
		RequiredScope: "actions:metaads:ListCampaigns",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "UpdateCampaign",
		HTTPMethod:    "POST",
		RequestType:   "UpdateCampaignRequest",
		ResponseType:  "UpdateCampaignResponse",
		RequiredScope: "actions:metaads:UpdateCampaign",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "CreateAdCreative",
		HTTPMethod:    "POST",
		RequestType:   "CreateAdCreativeRequest",
		ResponseType:  "CreateAdCreativeResponse",
		RequiredScope: "actions:metaads:CreateAdCreative",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "metaads",
		Method:        "DeleteAdCreative",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteAdCreativeRequest",
		ResponseType:  "DeleteAdCreativeResponse",
		RequiredScope: "actions:metaads:DeleteAdCreative",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "metaads",
		Method:        "GetAdCreative",
		HTTPMethod:    "GET",
		RequestType:   "GetAdCreativeRequest",
		ResponseType:  "GetAdCreativeResponse",
		RequiredScope: "actions:metaads:GetAdCreative",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "ListAdCreatives",
		HTTPMethod:    "GET",
		RequestType:   "ListAdCreativesRequest",
		ResponseType:  "ListAdCreativesResponse",
		RequiredScope: "actions:metaads:ListAdCreatives",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "metaads",
		Method:        "GetInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetInsightsRequest",
		ResponseType:  "GetInsightsResponse",
		RequiredScope: "actions:metaads:GetInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
	"GetAdAccount":     invokeGetAdAccountAction,
	"ListAdAccounts":   invokeListAdAccountsAction,
	"CreateAdSet":      invokeCreateAdSetAction,
	"DeleteAdSet":      invokeDeleteAdSetAction,
	"GetAdSet":         invokeGetAdSetAction,
	"ListAdSets":       invokeListAdSetsAction,
	"UpdateAdSet":      invokeUpdateAdSetAction,
	"CreateAd":         invokeCreateAdAction,
	"DeleteAd":         invokeDeleteAdAction,
	"GetAd":            invokeGetAdAction,
	"ListAds":          invokeListAdsAction,
	"UpdateAd":         invokeUpdateAdAction,
	"CreateCampaign":   invokeCreateCampaignAction,
	"DeleteCampaign":   invokeDeleteCampaignAction,
	"GetCampaign":      invokeGetCampaignAction,
	"ListCampaigns":    invokeListCampaignsAction,
	"UpdateCampaign":   invokeUpdateCampaignAction,
	"CreateAdCreative": invokeCreateAdCreativeAction,
	"DeleteAdCreative": invokeDeleteAdCreativeAction,
	"GetAdCreative":    invokeGetAdCreativeAction,
	"ListAdCreatives":  invokeListAdCreativesAction,
	"GetInsights":      invokeGetInsightsAction,
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "metaads" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}

func invokeGetAdAccountAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Fields      *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetAdAccount", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdAccount(ctx, &GetAdAccountRequest{
		AdAccountId: wire.AdAccountId,
		Fields:      wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdAccountsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		Fields *string `json:"fields,omitempty"`
		Limit  *int    `json:"limit,omitempty"`
		After  *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "ListAdAccounts", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAdAccounts(ctx, &ListAdAccountsRequest{
		Fields: wire.Fields,
		Limit:  wire.Limit,
		After:  wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateAdSetAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId      string  `json:"adAccountId,omitempty"`
		Name             *string `json:"name,omitempty"`
		CampaignId       *string `json:"campaign_id,omitempty"`
		Status           *string `json:"status,omitempty"`
		BillingEvent     *string `json:"billing_event,omitempty"`
		OptimizationGoal *string `json:"optimization_goal,omitempty"`
		BidAmount        *int64  `json:"bid_amount,omitempty"`
		DailyBudget      *int64  `json:"daily_budget,omitempty"`
		LifetimeBudget   *int64  `json:"lifetime_budget,omitempty"`
		Targeting        *string `json:"targeting,omitempty"`
		StartTime        *string `json:"start_time,omitempty"`
		EndTime          *string `json:"end_time,omitempty"`
		PromotedObject   *string `json:"promoted_object,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "CreateAdSet", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateAdSet(ctx, &CreateAdSetRequest{
		AdAccountId:      wire.AdAccountId,
		Name:             wire.Name,
		CampaignId:       wire.CampaignId,
		Status:           wire.Status,
		BillingEvent:     wire.BillingEvent,
		OptimizationGoal: wire.OptimizationGoal,
		BidAmount:        wire.BidAmount,
		DailyBudget:      wire.DailyBudget,
		LifetimeBudget:   wire.LifetimeBudget,
		Targeting:        wire.Targeting,
		StartTime:        wire.StartTime,
		EndTime:          wire.EndTime,
		PromotedObject:   wire.PromotedObject,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteAdSetAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdSetId string `json:"adSetId,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "DeleteAdSet", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteAdSet(ctx, &DeleteAdSetRequest{
		AdSetId: wire.AdSetId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdSetAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdSetId string  `json:"adSetId,omitempty"`
		Fields  *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetAdSet", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdSet(ctx, &GetAdSetRequest{
		AdSetId: wire.AdSetId,
		Fields:  wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdSetsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Fields      *string `json:"fields,omitempty"`
		Filtering   *string `json:"filtering,omitempty"`
		Limit       *int    `json:"limit,omitempty"`
		After       *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "ListAdSets", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAdSets(ctx, &ListAdSetsRequest{
		AdAccountId: wire.AdAccountId,
		Fields:      wire.Fields,
		Filtering:   wire.Filtering,
		Limit:       wire.Limit,
		After:       wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateAdSetAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdSetId        string  `json:"adSetId,omitempty"`
		Name           *string `json:"name,omitempty"`
		Status         *string `json:"status,omitempty"`
		DailyBudget    *int64  `json:"daily_budget,omitempty"`
		LifetimeBudget *int64  `json:"lifetime_budget,omitempty"`
		BidAmount      *int64  `json:"bid_amount,omitempty"`
		Targeting      *string `json:"targeting,omitempty"`
		EndTime        *string `json:"end_time,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "UpdateAdSet", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateAdSet(ctx, &UpdateAdSetRequest{
		AdSetId:        wire.AdSetId,
		Name:           wire.Name,
		Status:         wire.Status,
		DailyBudget:    wire.DailyBudget,
		LifetimeBudget: wire.LifetimeBudget,
		BidAmount:      wire.BidAmount,
		Targeting:      wire.Targeting,
		EndTime:        wire.EndTime,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Name        *string `json:"name,omitempty"`
		AdsetId     *string `json:"adset_id,omitempty"`
		Creative    *string `json:"creative,omitempty"`
		Status      *string `json:"status,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "CreateAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateAd(ctx, &CreateAdRequest{
		AdAccountId: wire.AdAccountId,
		Name:        wire.Name,
		AdsetId:     wire.AdsetId,
		Creative:    wire.Creative,
		Status:      wire.Status,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId string `json:"adId,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "DeleteAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteAd(ctx, &DeleteAdRequest{
		AdId: wire.AdId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId   string  `json:"adId,omitempty"`
		Fields *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAd(ctx, &GetAdRequest{
		AdId:   wire.AdId,
		Fields: wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Fields      *string `json:"fields,omitempty"`
		Filtering   *string `json:"filtering,omitempty"`
		Limit       *int    `json:"limit,omitempty"`
		After       *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "ListAds", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAds(ctx, &ListAdsRequest{
		AdAccountId: wire.AdAccountId,
		Fields:      wire.Fields,
		Filtering:   wire.Filtering,
		Limit:       wire.Limit,
		After:       wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateAdAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdId     string  `json:"adId,omitempty"`
		Name     *string `json:"name,omitempty"`
		Status   *string `json:"status,omitempty"`
		Creative *string `json:"creative,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "UpdateAd", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateAd(ctx, &UpdateAdRequest{
		AdId:     wire.AdId,
		Name:     wire.Name,
		Status:   wire.Status,
		Creative: wire.Creative,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId         string  `json:"adAccountId,omitempty"`
		Name                *string `json:"name,omitempty"`
		Objective           *string `json:"objective,omitempty"`
		Status              *string `json:"status,omitempty"`
		SpecialAdCategories *string `json:"special_ad_categories,omitempty"`
		DailyBudget         *int64  `json:"daily_budget,omitempty"`
		LifetimeBudget      *int64  `json:"lifetime_budget,omitempty"`
		BidStrategy         *string `json:"bid_strategy,omitempty"`
		BuyingType          *string `json:"buying_type,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "CreateCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateCampaign(ctx, &CreateCampaignRequest{
		AdAccountId:         wire.AdAccountId,
		Name:                wire.Name,
		Objective:           wire.Objective,
		Status:              wire.Status,
		SpecialAdCategories: wire.SpecialAdCategories,
		DailyBudget:         wire.DailyBudget,
		LifetimeBudget:      wire.LifetimeBudget,
		BidStrategy:         wire.BidStrategy,
		BuyingType:          wire.BuyingType,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string `json:"campaignId,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "DeleteCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteCampaign(ctx, &DeleteCampaignRequest{
		CampaignId: wire.CampaignId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId string  `json:"campaignId,omitempty"`
		Fields     *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetCampaign(ctx, &GetCampaignRequest{
		CampaignId: wire.CampaignId,
		Fields:     wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListCampaignsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Fields      *string `json:"fields,omitempty"`
		Filtering   *string `json:"filtering,omitempty"`
		Limit       *int    `json:"limit,omitempty"`
		After       *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "ListCampaigns", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListCampaigns(ctx, &ListCampaignsRequest{
		AdAccountId: wire.AdAccountId,
		Fields:      wire.Fields,
		Filtering:   wire.Filtering,
		Limit:       wire.Limit,
		After:       wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeUpdateCampaignAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CampaignId     string  `json:"campaignId,omitempty"`
		Name           *string `json:"name,omitempty"`
		Status         *string `json:"status,omitempty"`
		DailyBudget    *int64  `json:"daily_budget,omitempty"`
		LifetimeBudget *int64  `json:"lifetime_budget,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "UpdateCampaign", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.UpdateCampaign(ctx, &UpdateCampaignRequest{
		CampaignId:     wire.CampaignId,
		Name:           wire.Name,
		Status:         wire.Status,
		DailyBudget:    wire.DailyBudget,
		LifetimeBudget: wire.LifetimeBudget,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateAdCreativeAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId     string  `json:"adAccountId,omitempty"`
		Name            *string `json:"name,omitempty"`
		ObjectStorySpec *string `json:"object_story_spec,omitempty"`
		ObjectStoryId   *string `json:"object_story_id,omitempty"`
		InstagramUserId *string `json:"instagram_user_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "CreateAdCreative", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateAdCreative(ctx, &CreateAdCreativeRequest{
		AdAccountId:     wire.AdAccountId,
		Name:            wire.Name,
		ObjectStorySpec: wire.ObjectStorySpec,
		ObjectStoryId:   wire.ObjectStoryId,
		InstagramUserId: wire.InstagramUserId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteAdCreativeAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CreativeId string `json:"creativeId,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "DeleteAdCreative", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteAdCreative(ctx, &DeleteAdCreativeRequest{
		CreativeId: wire.CreativeId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetAdCreativeAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		CreativeId string  `json:"creativeId,omitempty"`
		Fields     *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetAdCreative", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetAdCreative(ctx, &GetAdCreativeRequest{
		CreativeId: wire.CreativeId,
		Fields:     wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListAdCreativesAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		AdAccountId string  `json:"adAccountId,omitempty"`
		Fields      *string `json:"fields,omitempty"`
		Limit       *int    `json:"limit,omitempty"`
		After       *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "ListAdCreatives", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListAdCreatives(ctx, &ListAdCreativesRequest{
		AdAccountId: wire.AdAccountId,
		Fields:      wire.Fields,
		Limit:       wire.Limit,
		After:       wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		ObjectId         string  `json:"objectId,omitempty"`
		Fields           *string `json:"fields,omitempty"`
		Level            *string `json:"level,omitempty"`
		DatePreset       *string `json:"date_preset,omitempty"`
		TimeRange        *string `json:"time_range,omitempty"`
		TimeIncrement    *string `json:"time_increment,omitempty"`
		Breakdowns       *string `json:"breakdowns,omitempty"`
		ActionBreakdowns *string `json:"action_breakdowns,omitempty"`
		Limit            *int    `json:"limit,omitempty"`
		After            *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("metaads", "GetInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetInsights(ctx, &GetInsightsRequest{
		ObjectId:         wire.ObjectId,
		Fields:           wire.Fields,
		Level:            wire.Level,
		DatePreset:       wire.DatePreset,
		TimeRange:        wire.TimeRange,
		TimeIncrement:    wire.TimeIncrement,
		Breakdowns:       wire.Breakdowns,
		ActionBreakdowns: wire.ActionBreakdowns,
		Limit:            wire.Limit,
		After:            wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
