// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateAdRequest holds the parameters for CreateAd.
type CreateAdRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Name        *string `json:"-" query:"name"`
	AdsetId     *string `json:"-" query:"adset_id"`
	Creative    *string `json:"-" query:"creative"`
	Status      *string `json:"-" query:"status"`
}

// CreateAd calls POST /{version}/{adAccountId}/ads.
func (c *Client) CreateAd(ctx context.Context, req *CreateAdRequest) (*CreateAdResponse, error) {
	if req == nil {
		req = &CreateAdRequest{}
	}
	out := &CreateAdResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adAccountId}/ads",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAdRequest holds the parameters for DeleteAd.
type DeleteAdRequest struct {
	AdId string `json:"-" path:"adId"`
}

// DeleteAd calls DELETE /{version}/{adId}.
func (c *Client) DeleteAd(ctx context.Context, req *DeleteAdRequest) (*DeleteAdResponse, error) {
	if req == nil {
		req = &DeleteAdRequest{}
	}
	out := &DeleteAdResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{adId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAdRequest holds the parameters for GetAd.
type GetAdRequest struct {
	AdId   string  `json:"-" path:"adId"`
	Fields *string `json:"-" query:"fields"`
}

// GetAdResponse is the response type of GetAd.
type GetAdResponse = Ad

// GetAd calls GET /{version}/{adId}.
func (c *Client) GetAd(ctx context.Context, req *GetAdRequest) (*GetAdResponse, error) {
	if req == nil {
		req = &GetAdRequest{}
	}
	out := &GetAdResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListAdsRequest holds the parameters for ListAds.
type ListAdsRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Fields      *string `json:"-" query:"fields"`
	Filtering   *string `json:"-" query:"filtering"`
	Limit       *int    `json:"-" query:"limit"`
	After       *string `json:"-" query:"after"`
}

// ListAdsResponse is the response type of ListAds.
type ListAdsResponse = AdList

// ListAds calls GET /{version}/{adAccountId}/ads.
func (c *Client) ListAds(ctx context.Context, req *ListAdsRequest) (*ListAdsResponse, error) {
	if req == nil {
		req = &ListAdsRequest{}
	}
	out := &ListAdsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adAccountId}/ads",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAdRequest holds the parameters for UpdateAd.
type UpdateAdRequest struct {
	AdId     string  `json:"-" path:"adId"`
	Name     *string `json:"-" query:"name"`
	Status   *string `json:"-" query:"status"`
	Creative *string `json:"-" query:"creative"`
}

// UpdateAd calls POST /{version}/{adId}.
func (c *Client) UpdateAd(ctx context.Context, req *UpdateAdRequest) (*UpdateAdResponse, error) {
	if req == nil {
		req = &UpdateAdRequest{}
	}
	out := &UpdateAdResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
