// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateAdSetRequest holds the parameters for CreateAdSet.
type CreateAdSetRequest struct {
	AdAccountId      string  `json:"-" path:"adAccountId"`
	Name             *string `json:"-" query:"name"`
	CampaignId       *string `json:"-" query:"campaign_id"`
	Status           *string `json:"-" query:"status"`
	BillingEvent     *string `json:"-" query:"billing_event"`
	OptimizationGoal *string `json:"-" query:"optimization_goal"`
	BidAmount        *int64  `json:"-" query:"bid_amount"`
	DailyBudget      *int64  `json:"-" query:"daily_budget"`
	LifetimeBudget   *int64  `json:"-" query:"lifetime_budget"`
	Targeting        *string `json:"-" query:"targeting"`
	StartTime        *string `json:"-" query:"start_time"`
	EndTime          *string `json:"-" query:"end_time"`
	PromotedObject   *string `json:"-" query:"promoted_object"`
}

// CreateAdSet calls POST /{version}/{adAccountId}/adsets.
func (c *Client) CreateAdSet(ctx context.Context, req *CreateAdSetRequest) (*CreateAdSetResponse, error) {
	if req == nil {
		req = &CreateAdSetRequest{}
	}
	out := &CreateAdSetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adAccountId}/adsets",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAdSetRequest holds the parameters for DeleteAdSet.
type DeleteAdSetRequest struct {
	AdSetId string `json:"-" path:"adSetId"`
}

// DeleteAdSet calls DELETE /{version}/{adSetId}.
func (c *Client) DeleteAdSet(ctx context.Context, req *DeleteAdSetRequest) (*DeleteAdSetResponse, error) {
	if req == nil {
		req = &DeleteAdSetRequest{}
	}
	out := &DeleteAdSetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{adSetId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAdSetRequest holds the parameters for GetAdSet.
type GetAdSetRequest struct {
	AdSetId string  `json:"-" path:"adSetId"`
	Fields  *string `json:"-" query:"fields"`
}

// GetAdSetResponse is the response type of GetAdSet.
type GetAdSetResponse = AdSet

// GetAdSet calls GET /{version}/{adSetId}.
func (c *Client) GetAdSet(ctx context.Context, req *GetAdSetRequest) (*GetAdSetResponse, error) {
	if req == nil {
		req = &GetAdSetRequest{}
	}
	out := &GetAdSetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adSetId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListAdSetsRequest holds the parameters for ListAdSets.
type ListAdSetsRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Fields      *string `json:"-" query:"fields"`
	Filtering   *string `json:"-" query:"filtering"`
	Limit       *int    `json:"-" query:"limit"`
	After       *string `json:"-" query:"after"`
}

// ListAdSetsResponse is the response type of ListAdSets.
type ListAdSetsResponse = AdSetList

// ListAdSets calls GET /{version}/{adAccountId}/adsets.
func (c *Client) ListAdSets(ctx context.Context, req *ListAdSetsRequest) (*ListAdSetsResponse, error) {
	if req == nil {
		req = &ListAdSetsRequest{}
	}
	out := &ListAdSetsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adAccountId}/adsets",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAdSetRequest holds the parameters for UpdateAdSet.
type UpdateAdSetRequest struct {
	AdSetId        string  `json:"-" path:"adSetId"`
	Name           *string `json:"-" query:"name"`
	Status         *string `json:"-" query:"status"`
	DailyBudget    *int64  `json:"-" query:"daily_budget"`
	LifetimeBudget *int64  `json:"-" query:"lifetime_budget"`
	BidAmount      *int64  `json:"-" query:"bid_amount"`
	Targeting      *string `json:"-" query:"targeting"`
	EndTime        *string `json:"-" query:"end_time"`
}

// UpdateAdSet calls POST /{version}/{adSetId}.
func (c *Client) UpdateAdSet(ctx context.Context, req *UpdateAdSetRequest) (*UpdateAdSetResponse, error) {
	if req == nil {
		req = &UpdateAdSetRequest{}
	}
	out := &UpdateAdSetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adSetId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
