// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateCampaignRequest holds the parameters for CreateCampaign.
type CreateCampaignRequest struct {
	AdAccountId         string  `json:"-" path:"adAccountId"`
	Name                *string `json:"-" query:"name"`
	Objective           *string `json:"-" query:"objective"`
	Status              *string `json:"-" query:"status"`
	SpecialAdCategories *string `json:"-" query:"special_ad_categories"`
	DailyBudget         *int64  `json:"-" query:"daily_budget"`
	LifetimeBudget      *int64  `json:"-" query:"lifetime_budget"`
	BidStrategy         *string `json:"-" query:"bid_strategy"`
	BuyingType          *string `json:"-" query:"buying_type"`
}

// CreateCampaign calls POST /{version}/{adAccountId}/campaigns.
func (c *Client) CreateCampaign(ctx context.Context, req *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	if req == nil {
		req = &CreateCampaignRequest{}
	}
	out := &CreateCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adAccountId}/campaigns",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteCampaignRequest holds the parameters for DeleteCampaign.
type DeleteCampaignRequest struct {
	CampaignId string `json:"-" path:"campaignId"`
}

// DeleteCampaign calls DELETE /{version}/{campaignId}.
func (c *Client) DeleteCampaign(ctx context.Context, req *DeleteCampaignRequest) (*DeleteCampaignResponse, error) {
	if req == nil {
		req = &DeleteCampaignRequest{}
	}
	out := &DeleteCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{campaignId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCampaignRequest holds the parameters for GetCampaign.
type GetCampaignRequest struct {
	CampaignId string  `json:"-" path:"campaignId"`
	Fields     *string `json:"-" query:"fields"`
}

// GetCampaignResponse is the response type of GetCampaign.
type GetCampaignResponse = Campaign

// GetCampaign calls GET /{version}/{campaignId}.
func (c *Client) GetCampaign(ctx context.Context, req *GetCampaignRequest) (*GetCampaignResponse, error) {
	if req == nil {
		req = &GetCampaignRequest{}
	}
	out := &GetCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{campaignId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListCampaignsRequest holds the parameters for ListCampaigns.
type ListCampaignsRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Fields      *string `json:"-" query:"fields"`
	Filtering   *string `json:"-" query:"filtering"`
	Limit       *int    `json:"-" query:"limit"`
	After       *string `json:"-" query:"after"`
}

// ListCampaignsResponse is the response type of ListCampaigns.
type ListCampaignsResponse = CampaignList

// ListCampaigns calls GET /{version}/{adAccountId}/campaigns.
func (c *Client) ListCampaigns(ctx context.Context, req *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	if req == nil {
		req = &ListCampaignsRequest{}
	}
	out := &ListCampaignsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adAccountId}/campaigns",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateCampaignRequest holds the parameters for UpdateCampaign.
type UpdateCampaignRequest struct {
	CampaignId     string  `json:"-" path:"campaignId"`
	Name           *string `json:"-" query:"name"`
	Status         *string `json:"-" query:"status"`
	DailyBudget    *int64  `json:"-" query:"daily_budget"`
	LifetimeBudget *int64  `json:"-" query:"lifetime_budget"`
}

// UpdateCampaign calls POST /{version}/{campaignId}.
func (c *Client) UpdateCampaign(ctx context.Context, req *UpdateCampaignRequest) (*UpdateCampaignResponse, error) {
	if req == nil {
		req = &UpdateCampaignRequest{}
	}
	out := &UpdateCampaignResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{campaignId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
