// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateAdCreativeRequest holds the parameters for CreateAdCreative.
type CreateAdCreativeRequest struct {
	AdAccountId     string  `json:"-" path:"adAccountId"`
	Name            *string `json:"-" query:"name"`
	ObjectStorySpec *string `json:"-" query:"object_story_spec"`
	ObjectStoryId   *string `json:"-" query:"object_story_id"`
	InstagramUserId *string `json:"-" query:"instagram_user_id"`
}

// CreateAdCreative calls POST /{version}/{adAccountId}/adcreatives.
func (c *Client) CreateAdCreative(ctx context.Context, req *CreateAdCreativeRequest) (*CreateAdCreativeResponse, error) {
	if req == nil {
		req = &CreateAdCreativeRequest{}
	}
	out := &CreateAdCreativeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{adAccountId}/adcreatives",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAdCreativeRequest holds the parameters for DeleteAdCreative.
type DeleteAdCreativeRequest struct {
	CreativeId string `json:"-" path:"creativeId"`
}

// DeleteAdCreative calls DELETE /{version}/{creativeId}.
func (c *Client) DeleteAdCreative(ctx context.Context, req *DeleteAdCreativeRequest) (*DeleteAdCreativeResponse, error) {
	if req == nil {
		req = &DeleteAdCreativeRequest{}
	}
	out := &DeleteAdCreativeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/{version}/{creativeId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAdCreativeRequest holds the parameters for GetAdCreative.
type GetAdCreativeRequest struct {
	CreativeId string  `json:"-" path:"creativeId"`
	Fields     *string `json:"-" query:"fields"`
}

// GetAdCreativeResponse is the response type of GetAdCreative.
type GetAdCreativeResponse = AdCreative

// GetAdCreative calls GET /{version}/{creativeId}.
func (c *Client) GetAdCreative(ctx context.Context, req *GetAdCreativeRequest) (*GetAdCreativeResponse, error) {
	if req == nil {
		req = &GetAdCreativeRequest{}
	}
	out := &GetAdCreativeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{creativeId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListAdCreativesRequest holds the parameters for ListAdCreatives.
type ListAdCreativesRequest struct {
	AdAccountId string  `json:"-" path:"adAccountId"`
	Fields      *string `json:"-" query:"fields"`
	Limit       *int    `json:"-" query:"limit"`
	After       *string `json:"-" query:"after"`
}

// ListAdCreativesResponse is the response type of ListAdCreatives.
type ListAdCreativesResponse = AdCreativeList

// ListAdCreatives calls GET /{version}/{adAccountId}/adcreatives.
func (c *Client) ListAdCreatives(ctx context.Context, req *ListAdCreativesRequest) (*ListAdCreativesResponse, error) {
	if req == nil {
		req = &ListAdCreativesRequest{}
	}
	out := &ListAdCreativesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{adAccountId}/adcreatives",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
