// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
	{
		name:   "GetAdAccount",
		method: "GET",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccount(ctx, &GetAdAccountRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdAccount(ctx, nil)
		},
	},
	{
		name:   "ListAdAccounts",
		method: "GET",
		path:   "/v26.0/me/adaccounts",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdAccounts(ctx, &ListAdAccountsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdAccounts(ctx, nil)
		},
	},
	{
		name:   "CreateAdSet",
		method: "POST",
		path:   "/v26.0//adsets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdSet(ctx, &CreateAdSetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdSet(ctx, nil)
		},
	},
	{
		name:   "DeleteAdSet",
		method: "DELETE",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAdSet(ctx, &DeleteAdSetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAdSet(ctx, nil)
		},
	},
	{
		name:   "GetAdSet",
		method: "GET",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdSet(ctx, &GetAdSetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdSet(ctx, nil)
		},
	},
	{
		name:   "ListAdSets",
		method: "GET",
		path:   "/v26.0//adsets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdSets(ctx, &ListAdSetsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdSets(ctx, nil)
		},
	},
	{
		name:   "UpdateAdSet",
		method: "POST",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdSet(ctx, &UpdateAdSetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAdSet(ctx, nil)
		},
	},
	{
		name:   "CreateAd",
		method: "POST",
		path:   "/v26.0//ads",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAd(ctx, &CreateAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAd(ctx, nil)
		},
	},
	{
		name:   "DeleteAd",
		method: "DELETE",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAd(ctx, &DeleteAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAd(ctx, nil)
		},
	},
	{
		name:   "GetAd",
		method: "GET",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAd(ctx, &GetAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAd(ctx, nil)
		},
	},
	{
		name:   "ListAds",
		method: "GET",
		path:   "/v26.0//ads",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAds(ctx, &ListAdsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAds(ctx, nil)
		},
	},
	{
		name:   "UpdateAd",
		method: "POST",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAd(ctx, &UpdateAdRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateAd(ctx, nil)
		},
	},
	{
		name:   "CreateCampaign",
		method: "POST",
		path:   "/v26.0//campaigns",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCampaign(ctx, &CreateCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateCampaign(ctx, nil)
		},
	},
	{
		name:   "DeleteCampaign",
		method: "DELETE",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteCampaign(ctx, &DeleteCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteCampaign(ctx, nil)
		},
	},
	{
		name:   "GetCampaign",
		method: "GET",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaign(ctx, &GetCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetCampaign(ctx, nil)
		},
	},
	{
		name:   "ListCampaigns",
		method: "GET",
		path:   "/v26.0//campaigns",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCampaigns(ctx, &ListCampaignsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListCampaigns(ctx, nil)
		},
	},
	{
		name:   "UpdateCampaign",
		method: "POST",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateCampaign(ctx, &UpdateCampaignRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UpdateCampaign(ctx, nil)
		},
	},
	{
		name:   "CreateAdCreative",
		method: "POST",
		path:   "/v26.0//adcreatives",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdCreative(ctx, &CreateAdCreativeRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateAdCreative(ctx, nil)
		},
	},
	{
		name:   "DeleteAdCreative",
		method: "DELETE",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAdCreative(ctx, &DeleteAdCreativeRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteAdCreative(ctx, nil)
		},
	},
	{
		name:   "GetAdCreative",
		method: "GET",
		path:   "/v26.0/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdCreative(ctx, &GetAdCreativeRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetAdCreative(ctx, nil)
		},
	},
	{
		name:   "ListAdCreatives",
		method: "GET",
		path:   "/v26.0//adcreatives",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdCreatives(ctx, &ListAdCreativesRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListAdCreatives(ctx, nil)
		},
	},
	{
		name:   "GetInsights",
		method: "GET",
		path:   "/v26.0//insights",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetInsights(ctx, &GetInsightsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetInsights(ctx, nil)
		},
	},
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
