// Code generated by connector-gen. DO NOT EDIT.

package metaads

import (
	"github.com/pax-beehive/connector"
)

// Ad is the Ad model.
type Ad struct {
	AdsetId         *string             `json:"adset_id,omitempty"`
	CampaignId      *string             `json:"campaign_id,omitempty"`
	CreatedTime     *connector.DateTime `json:"created_time,omitempty"`
	Creative        *AdCreativeRef      `json:"creative,omitempty"`
	EffectiveStatus *string             `json:"effective_status,omitempty"`
	Id              *string             `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	Status          *string             `json:"status,omitempty"`
}

// AdAccount is the AdAccount model.
type AdAccount struct {
	AccountId     *string `json:"account_id,omitempty"`
	AccountStatus *int    `json:"account_status,omitempty"`
	AmountSpent   *string `json:"amount_spent,omitempty"`
	Balance       *string `json:"balance,omitempty"`
	Currency      *string `json:"currency,omitempty"`
	Id            *string `json:"id,omitempty"`
	Name          *string `json:"name,omitempty"`
	TimezoneName  *string `json:"timezone_name,omitempty"`
}

// AdAccountList is the AdAccountList model.
type AdAccountList struct {
	Data   []AdAccount `json:"data,omitempty"`
	Paging *Paging     `json:"paging,omitempty"`
}

// AdCreative is the AdCreative model.
type AdCreative struct {
	Body                      *string        `json:"body,omitempty"`
	EffectiveInstagramMediaId *string        `json:"effective_instagram_media_id,omitempty"`
	Id                        *string        `json:"id,omitempty"`
	ImageUrl                  *string        `json:"image_url,omitempty"`
	Name                      *string        `json:"name,omitempty"`
	ObjectStoryId             *string        `json:"object_story_id,omitempty"`
	ObjectStorySpec           map[string]any `json:"object_story_spec,omitempty"`
	ThumbnailUrl              *string        `json:"thumbnail_url,omitempty"`
	Title                     *string        `json:"title,omitempty"`
}

// AdCreativeList is the AdCreativeList model.
type AdCreativeList struct {
	Data   []AdCreative `json:"data,omitempty"`
	Paging *Paging      `json:"paging,omitempty"`
}

// AdCreativeRef is the AdCreativeRef model.
type AdCreativeRef struct {
	Id *string `json:"id,omitempty"`
}

// AdList is the AdList model.
type AdList struct {
	Data   []Ad    `json:"data,omitempty"`
	Paging *Paging `json:"paging,omitempty"`
}

// AdSet is the AdSet model.
type AdSet struct {
	BidAmount        *int64              `json:"bid_amount,omitempty"`
	BillingEvent     *string             `json:"billing_event,omitempty"`
	CampaignId       *string             `json:"campaign_id,omitempty"`
	CreatedTime      *connector.DateTime `json:"created_time,omitempty"`
	DailyBudget      *string             `json:"daily_budget,omitempty"`
	EffectiveStatus  *string             `json:"effective_status,omitempty"`
	EndTime          *connector.DateTime `json:"end_time,omitempty"`
	Id               *string             `json:"id,omitempty"`
	LifetimeBudget   *string             `json:"lifetime_budget,omitempty"`
	Name             *string             `json:"name,omitempty"`
	OptimizationGoal *string             `json:"optimization_goal,omitempty"`
	PromotedObject   map[string]any      `json:"promoted_object,omitempty"`
	StartTime        *connector.DateTime `json:"start_time,omitempty"`
	Status           *string             `json:"status,omitempty"`
	Targeting        map[string]any      `json:"targeting,omitempty"`
}

// AdSetList is the AdSetList model.
type AdSetList struct {
	Data   []AdSet `json:"data,omitempty"`
	Paging *Paging `json:"paging,omitempty"`
}

// AdsActionStat is the AdsActionStat model.
type AdsActionStat struct {
	ActionType *string `json:"action_type,omitempty"`
	Value      *string `json:"value,omitempty"`
}

// AdsInsight is the AdsInsight model.
type AdsInsight struct {
	AccountId         *string         `json:"account_id,omitempty"`
	Actions           []AdsActionStat `json:"actions,omitempty"`
	AdId              *string         `json:"ad_id,omitempty"`
	AdName            *string         `json:"ad_name,omitempty"`
	AdsetId           *string         `json:"adset_id,omitempty"`
	AdsetName         *string         `json:"adset_name,omitempty"`
	Age               *string         `json:"age,omitempty"`
	CampaignId        *string         `json:"campaign_id,omitempty"`
	CampaignName      *string         `json:"campaign_name,omitempty"`
	Clicks            *string         `json:"clicks,omitempty"`
	Cpc               *string         `json:"cpc,omitempty"`
	Cpm               *string         `json:"cpm,omitempty"`
	Ctr               *string         `json:"ctr,omitempty"`
	DateStart         *string         `json:"date_start,omitempty"`
	DateStop          *string         `json:"date_stop,omitempty"`
	Frequency         *string         `json:"frequency,omitempty"`
	Gender            *string         `json:"gender,omitempty"`
	Impressions       *string         `json:"impressions,omitempty"`
	PublisherPlatform *string         `json:"publisher_platform,omitempty"`
	Reach             *string         `json:"reach,omitempty"`
	Spend             *string         `json:"spend,omitempty"`
}

// AdsInsightList is the AdsInsightList model.
type AdsInsightList struct {
	Data   []AdsInsight `json:"data,omitempty"`
	Paging *Paging      `json:"paging,omitempty"`
}

// Campaign is the Campaign model.
type Campaign struct {
	BidStrategy         *string             `json:"bid_strategy,omitempty"`
	BuyingType          *string             `json:"buying_type,omitempty"`
	CreatedTime         *connector.DateTime `json:"created_time,omitempty"`
	DailyBudget         *string             `json:"daily_budget,omitempty"`
	EffectiveStatus     *string             `json:"effective_status,omitempty"`
	Id                  *string             `json:"id,omitempty"`
	LifetimeBudget      *string             `json:"lifetime_budget,omitempty"`
	Name                *string             `json:"name,omitempty"`
	Objective           *string             `json:"objective,omitempty"`
	SpecialAdCategories []string            `json:"special_ad_categories,omitempty"`
	StartTime           *connector.DateTime `json:"start_time,omitempty"`
	Status              *string             `json:"status,omitempty"`
	StopTime            *connector.DateTime `json:"stop_time,omitempty"`
}

// CampaignList is the CampaignList model.
type CampaignList struct {
	Data   []Campaign `json:"data,omitempty"`
	Paging *Paging    `json:"paging,omitempty"`
}

// CreateAdCreativeResponse is the CreateAdCreativeResponse model.
type CreateAdCreativeResponse struct {
	Id *string `json:"id,omitempty"`
}

// CreateAdResponse is the CreateAdResponse model.
type CreateAdResponse struct {
	Id *string `json:"id,omitempty"`
}

// CreateAdSetResponse is the CreateAdSetResponse model.
type CreateAdSetResponse struct {
	Id *string `json:"id,omitempty"`
}

// CreateCampaignResponse is the CreateCampaignResponse model.
type CreateCampaignResponse struct {
	Id *string `json:"id,omitempty"`
}

// DeleteAdCreativeResponse is the DeleteAdCreativeResponse model.
type DeleteAdCreativeResponse struct {
	Success *bool `json:"success,omitempty"`
}

// DeleteAdResponse is the DeleteAdResponse model.
type DeleteAdResponse struct {
	Success *bool `json:"success,omitempty"`
}

// DeleteAdSetResponse is the DeleteAdSetResponse model.
type DeleteAdSetResponse struct {
	Success *bool `json:"success,omitempty"`
}

// DeleteCampaignResponse is the DeleteCampaignResponse model.
type DeleteCampaignResponse struct {
	Success *bool `json:"success,omitempty"`
}

// Paging is the Paging model.
type Paging struct {
	Cursors  *PagingCursors `json:"cursors,omitempty"`
	Next     *string        `json:"next,omitempty"`
	Previous *string        `json:"previous,omitempty"`
}

// PagingCursors is the PagingCursors model.
type PagingCursors struct {
	After  *string `json:"after,omitempty"`
	Before *string `json:"before,omitempty"`
}

// UpdateAdResponse is the UpdateAdResponse model.
type UpdateAdResponse struct {
	Success *bool `json:"success,omitempty"`
}

// UpdateAdSetResponse is the UpdateAdSetResponse model.
type UpdateAdSetResponse struct {
	Success *bool `json:"success,omitempty"`
}

// UpdateCampaignResponse is the UpdateCampaignResponse model.
type UpdateCampaignResponse struct {
	Success *bool `json:"success,omitempty"`
}
