// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"encoding/json"
	"github.com/pax-beehive/connector"
)

var connectorActionManifest = [...]connector.ActionDescriptor{
	{
		Provider:      "instagram",
		Method:        "RefreshAccessToken",
		HTTPMethod:    "GET",
		RequestType:   "RefreshAccessTokenRequest",
		ResponseType:  "RefreshAccessTokenResponse",
		RequiredScope: "actions:instagram:RefreshAccessToken",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "CreateComment",
		HTTPMethod:    "POST",
		RequestType:   "CreateCommentRequest",
		ResponseType:  "CreateCommentResponse",
		RequiredScope: "actions:instagram:CreateComment",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "instagram",
		Method:        "DeleteComment",
		HTTPMethod:    "DELETE",
		RequestType:   "DeleteCommentRequest",
		ResponseType:  "DeleteCommentResponse",
		RequiredScope: "actions:instagram:DeleteComment",
		Idempotency:   connector.ActionIdempotency("idempotent"),
	},
	{
		Provider:      "instagram",
		Method:        "HideComment",
		HTTPMethod:    "POST",
		RequestType:   "HideCommentRequest",
		ResponseType:  "HideCommentResponse",
		RequiredScope: "actions:instagram:HideComment",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "instagram",
		Method:        "ListComments",
		HTTPMethod:    "GET",
		RequestType:   "ListCommentsRequest",
		ResponseType:  "ListCommentsResponse",
		RequiredScope: "actions:instagram:ListComments",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "ReplyToComment",
		HTTPMethod:    "POST",
		RequestType:   "ReplyToCommentRequest",
		ResponseType:  "ReplyToCommentResponse",
		RequiredScope: "actions:instagram:ReplyToComment",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetMediaInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetMediaInsightsRequest",
		ResponseType:  "GetMediaInsightsResponse",
		RequiredScope: "actions:instagram:GetMediaInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetUserInsights",
		HTTPMethod:    "GET",
		RequestType:   "GetUserInsightsRequest",
		ResponseType:  "GetUserInsightsResponse",
		RequiredScope: "actions:instagram:GetUserInsights",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetMedia",
		HTTPMethod:    "GET",
		RequestType:   "GetMediaRequest",
		ResponseType:  "GetMediaResponse",
		RequiredScope: "actions:instagram:GetMedia",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "ListMedia",
		HTTPMethod:    "GET",
		RequestType:   "ListMediaRequest",
		ResponseType:  "ListMediaResponse",
		RequiredScope: "actions:instagram:ListMedia",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "ListStories",
		HTTPMethod:    "GET",
		RequestType:   "ListStoriesRequest",
		ResponseType:  "ListStoriesResponse",
		RequiredScope: "actions:instagram:ListStories",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetProfile",
		HTTPMethod:    "GET",
		RequestType:   "GetProfileRequest",
		ResponseType:  "GetProfileResponse",
		RequiredScope: "actions:instagram:GetProfile",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "CreateMediaContainer",
		HTTPMethod:    "POST",
		RequestType:   "CreateMediaContainerRequest",
		ResponseType:  "CreateMediaContainerResponse",
		RequiredScope: "actions:instagram:CreateMediaContainer",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetContainerStatus",
		HTTPMethod:    "GET",
		RequestType:   "GetContainerStatusRequest",
		ResponseType:  "GetContainerStatusResponse",
		RequiredScope: "actions:instagram:GetContainerStatus",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "GetPublishingLimit",
		HTTPMethod:    "GET",
		RequestType:   "GetPublishingLimitRequest",
		ResponseType:  "GetPublishingLimitResponse",
		RequiredScope: "actions:instagram:GetPublishingLimit",
		Idempotency:   connector.ActionIdempotency("safe"),
	},
	{
		Provider:      "instagram",
		Method:        "PublishMedia",
		HTTPMethod:    "POST",
		RequestType:   "PublishMediaRequest",
		ResponseType:  "PublishMediaResponse",
		RequiredScope: "actions:instagram:PublishMedia",
		Idempotency:   connector.ActionIdempotency("unsafe"),
	},
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
	"RefreshAccessToken":   invokeRefreshAccessTokenAction,
	"CreateComment":        invokeCreateCommentAction,
	"DeleteComment":        invokeDeleteCommentAction,
	"HideComment":          invokeHideCommentAction,
	"ListComments":         invokeListCommentsAction,
	"ReplyToComment":       invokeReplyToCommentAction,
	"GetMediaInsights":     invokeGetMediaInsightsAction,
	"GetUserInsights":      invokeGetUserInsightsAction,
	"GetMedia":             invokeGetMediaAction,
	"ListMedia":            invokeListMediaAction,
	"ListStories":          invokeListStoriesAction,
	"GetProfile":           invokeGetProfileAction,
	"CreateMediaContainer": invokeCreateMediaContainerAction,
	"GetContainerStatus":   invokeGetContainerStatusAction,
	"GetPublishingLimit":   invokeGetPublishingLimitAction,
	"PublishMedia":         invokePublishMediaAction,
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "instagram" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}

func invokeRefreshAccessTokenAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		GrantType *string `json:"grant_type,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "RefreshAccessToken", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.RefreshAccessToken(ctx, &RefreshAccessTokenRequest{
		GrantType: wire.GrantType,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgMediaId string  `json:"igMediaId,omitempty"`
		Message   *string `json:"message,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "CreateComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateComment(ctx, &CreateCommentRequest{
		IgMediaId: wire.IgMediaId,
		Message:   wire.Message,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeDeleteCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgCommentId string `json:"igCommentId,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "DeleteComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.DeleteComment(ctx, &DeleteCommentRequest{
		IgCommentId: wire.IgCommentId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeHideCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgCommentId string `json:"igCommentId,omitempty"`
		Hide        *bool  `json:"hide,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "HideComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.HideComment(ctx, &HideCommentRequest{
		IgCommentId: wire.IgCommentId,
		Hide:        wire.Hide,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListCommentsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgMediaId string  `json:"igMediaId,omitempty"`
		Fields    *string `json:"fields,omitempty"`
		Limit     *int    `json:"limit,omitempty"`
		After     *string `json:"after,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "ListComments", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListComments(ctx, &ListCommentsRequest{
		IgMediaId: wire.IgMediaId,
		Fields:    wire.Fields,
		Limit:     wire.Limit,
		After:     wire.After,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeReplyToCommentAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgCommentId string  `json:"igCommentId,omitempty"`
		Message     *string `json:"message,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "ReplyToComment", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ReplyToComment(ctx, &ReplyToCommentRequest{
		IgCommentId: wire.IgCommentId,
		Message:     wire.Message,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetMediaInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgMediaId string  `json:"igMediaId,omitempty"`
		Metric    *string `json:"metric,omitempty"`
		Breakdown *string `json:"breakdown,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetMediaInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetMediaInsights(ctx, &GetMediaInsightsRequest{
		IgMediaId: wire.IgMediaId,
		Metric:    wire.Metric,
		Breakdown: wire.Breakdown,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetUserInsightsAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId   string  `json:"igUserId,omitempty"`
		Metric     *string `json:"metric,omitempty"`
		Period     *string `json:"period,omitempty"`
		MetricType *string `json:"metric_type,omitempty"`
		Breakdown  *string `json:"breakdown,omitempty"`
		Timeframe  *string `json:"timeframe,omitempty"`
		Since      *int64  `json:"since,omitempty"`
		Until      *int64  `json:"until,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetUserInsights", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetUserInsights(ctx, &GetUserInsightsRequest{
		IgUserId:   wire.IgUserId,
		Metric:     wire.Metric,
		Period:     wire.Period,
		MetricType: wire.MetricType,
		Breakdown:  wire.Breakdown,
		Timeframe:  wire.Timeframe,
		Since:      wire.Since,
		Until:      wire.Until,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetMediaAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgMediaId string  `json:"igMediaId,omitempty"`
		Fields    *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetMedia", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetMedia(ctx, &GetMediaRequest{
		IgMediaId: wire.IgMediaId,
		Fields:    wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListMediaAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId string  `json:"igUserId,omitempty"`
		Fields   *string `json:"fields,omitempty"`
		Limit    *int    `json:"limit,omitempty"`
		After    *string `json:"after,omitempty"`
		Before   *string `json:"before,omitempty"`
		Since    *int64  `json:"since,omitempty"`
		Until    *int64  `json:"until,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "ListMedia", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListMedia(ctx, &ListMediaRequest{
		IgUserId: wire.IgUserId,
		Fields:   wire.Fields,
		Limit:    wire.Limit,
		After:    wire.After,
		Before:   wire.Before,
		Since:    wire.Since,
		Until:    wire.Until,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeListStoriesAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId string  `json:"igUserId,omitempty"`
		Fields   *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "ListStories", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.ListStories(ctx, &ListStoriesRequest{
		IgUserId: wire.IgUserId,
		Fields:   wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetProfileAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgProfileUserId string  `json:"igProfileUserId,omitempty"`
		Fields          *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetProfile", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetProfile(ctx, &GetProfileRequest{
		IgProfileUserId: wire.IgProfileUserId,
		Fields:          wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeCreateMediaContainerAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId       string  `json:"igUserId,omitempty"`
		ImageUrl       *string `json:"image_url,omitempty"`
		VideoUrl       *string `json:"video_url,omitempty"`
		MediaType      *string `json:"media_type,omitempty"`
		Caption        *string `json:"caption,omitempty"`
		IsCarouselItem *bool   `json:"is_carousel_item,omitempty"`
		Children       *string `json:"children,omitempty"`
		CoverUrl       *string `json:"cover_url,omitempty"`
		ThumbOffset    *int64  `json:"thumb_offset,omitempty"`
		ShareToFeed    *bool   `json:"share_to_feed,omitempty"`
		LocationId     *string `json:"location_id,omitempty"`
		UserTags       *string `json:"user_tags,omitempty"`
		ProductTags    *string `json:"product_tags,omitempty"`
		Collaborators  *string `json:"collaborators,omitempty"`
		AltText        *string `json:"alt_text,omitempty"`
		AudioName      *string `json:"audio_name,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "CreateMediaContainer", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.CreateMediaContainer(ctx, &CreateMediaContainerRequest{
		IgUserId:       wire.IgUserId,
		ImageUrl:       wire.ImageUrl,
		VideoUrl:       wire.VideoUrl,
		MediaType:      wire.MediaType,
		Caption:        wire.Caption,
		IsCarouselItem: wire.IsCarouselItem,
		Children:       wire.Children,
		CoverUrl:       wire.CoverUrl,
		ThumbOffset:    wire.ThumbOffset,
		ShareToFeed:    wire.ShareToFeed,
		LocationId:     wire.LocationId,
		UserTags:       wire.UserTags,
		ProductTags:    wire.ProductTags,
		Collaborators:  wire.Collaborators,
		AltText:        wire.AltText,
		AudioName:      wire.AudioName,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetContainerStatusAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgContainerId string  `json:"igContainerId,omitempty"`
		Fields        *string `json:"fields,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetContainerStatus", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetContainerStatus(ctx, &GetContainerStatusRequest{
		IgContainerId: wire.IgContainerId,
		Fields:        wire.Fields,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokeGetPublishingLimitAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId string  `json:"igUserId,omitempty"`
		Fields   *string `json:"fields,omitempty"`
		Since    *int64  `json:"since,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "GetPublishingLimit", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.GetPublishingLimit(ctx, &GetPublishingLimitRequest{
		IgUserId: wire.IgUserId,
		Fields:   wire.Fields,
		Since:    wire.Since,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}

func invokePublishMediaAction(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
		IgUserId   string  `json:"igUserId,omitempty"`
		CreationId *string `json:"creation_id,omitempty"`
	}
	if err := connector.DecodeActionRequest("instagram", "PublishMedia", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.PublishMedia(ctx, &PublishMediaRequest{
		IgUserId:   wire.IgUserId,
		CreationId: wire.CreationId,
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
