// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/pax-beehive/connector"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

func TestGeneratedActionManifest(t *testing.T) {
	actions := ConnectorActions()
	if len(actions) != len(roundtripCases) {
		t.Fatalf("manifest entries = %d, operations = %d", len(actions), len(roundtripCases))
	}
	seen := make(map[string]bool, len(actions))
	for _, action := range actions {
		if action.Provider != "instagram" {
			t.Errorf("provider = %q", action.Provider)
		}
		if action.Method == "" || action.HTTPMethod == "" || action.RequestType == "" || action.ResponseType == "" || action.RequiredScope == "" || action.Idempotency == "" {
			t.Errorf("incomplete descriptor: %+v", action)
		}
		if seen[action.Method] {
			t.Errorf("duplicate action %q", action.Method)
		}
		seen[action.Method] = true
	}
	if len(actions) > 0 {
		actions[0].Method = "mutated"
		if ConnectorActions()[0].Method == "mutated" {
			t.Fatal("ConnectorActions exposed mutable manifest storage")
		}
	}
}

func TestGeneratedActionDispatch(t *testing.T) {
	actions := ConnectorActions()
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	var nextStatus int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextStatus != 0 {
			w.WriteHeader(nextStatus)
			nextStatus = 0
		}
		if nextResp != "" {
			_, _ = w.Write([]byte(nextResp))
		}
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}

	for i, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			action := actions[i]
			if action.Method != tc.name {
				t.Fatalf("manifest method = %q, operation = %q", action.Method, tc.name)
			}
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := c.InvokeAction(context.Background(), connector.ActionCall{
				Provider: action.Provider,
				Method:   action.Method,
				Request:  json.RawMessage(`{}`),
			})
			if err != nil {
				t.Fatal(err)
			}
			if !json.Valid(out) {
				t.Fatalf("invalid JSON response: %s", out)
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method || gotPath != tc.path {
				t.Errorf("request = %s %s, want %s %s", gotMethod, gotPath, tc.method, tc.path)
			}
		})
	}
}

func TestGeneratedActionDispatchErrors(t *testing.T) {
	if len(roundtripCases) == 0 {
		t.Skip("connector has no actions")
	}
	var mu sync.Mutex
	nextStatus := http.StatusOK
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		w.WriteHeader(nextStatus)
		_, _ = w.Write([]byte(roundtripCases[0].resp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	first := roundtripCases[0]

	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "wrong", Method: first.name})
	var providerErr *connector.UnknownProviderError
	if !errors.As(err, &providerErr) {
		t.Fatalf("wrong provider error = %T, want *connector.UnknownProviderError", err)
	}

	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "instagram", Method: "Missing"})
	var actionErr *connector.UnknownActionError
	if !errors.As(err, &actionErr) {
		t.Fatalf("unknown method error = %T, want *connector.UnknownActionError", err)
	}

	_, err = c.InvokeAction(ctx, connector.ActionCall{
		Provider: "instagram",
		Method:   first.name,
		Request:  json.RawMessage(`{`),
	})
	var requestErr *connector.InvalidActionRequestError
	if !errors.As(err, &requestErr) {
		t.Fatalf("malformed request error = %T, want *connector.InvalidActionRequestError", err)
	}

	mu.Lock()
	nextStatus = http.StatusTooManyRequests
	mu.Unlock()
	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "instagram", Method: first.name})
	if _, ok := connector.AsAPIError(err); !ok {
		t.Fatalf("provider error = %T, want *connector.APIError", err)
	}
}
