// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"github.com/pax-beehive/connector"
)

// RefreshAccessTokenRequest holds the parameters for RefreshAccessToken.
type RefreshAccessTokenRequest struct {
	GrantType *string `json:"-" query:"grant_type"`
}

// RefreshAccessToken calls GET /{version}/refresh_access_token.
func (c *Client) RefreshAccessToken(ctx context.Context, req *RefreshAccessTokenRequest) (*RefreshAccessTokenResponse, error) {
	if req == nil {
		req = &RefreshAccessTokenRequest{}
	}
	out := &RefreshAccessTokenResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/refresh_access_token",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
