// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetMediaInsightsRequest holds the parameters for GetMediaInsights.
type GetMediaInsightsRequest struct {
	IgMediaId string  `json:"-" path:"igMediaId"`
	Metric    *string `json:"-" query:"metric"`
	Breakdown *string `json:"-" query:"breakdown"`
}

// GetMediaInsightsResponse is the response type of GetMediaInsights.
type GetMediaInsightsResponse = InsightList

// GetMediaInsights calls GET /{version}/{igMediaId}/insights.
func (c *Client) GetMediaInsights(ctx context.Context, req *GetMediaInsightsRequest) (*GetMediaInsightsResponse, error) {
	if req == nil {
		req = &GetMediaInsightsRequest{}
	}
	out := &GetMediaInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igMediaId}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserInsightsRequest holds the parameters for GetUserInsights.
type GetUserInsightsRequest struct {
	IgUserId   string  `json:"-" path:"igUserId"`
	Metric     *string `json:"-" query:"metric"`
	Period     *string `json:"-" query:"period"`
	MetricType *string `json:"-" query:"metric_type"`
	Breakdown  *string `json:"-" query:"breakdown"`
	Timeframe  *string `json:"-" query:"timeframe"`
	Since      *int64  `json:"-" query:"since"`
	Until      *int64  `json:"-" query:"until"`
}

// GetUserInsightsResponse is the response type of GetUserInsights.
type GetUserInsightsResponse = InsightList

// GetUserInsights calls GET /{version}/{igUserId}/insights.
func (c *Client) GetUserInsights(ctx context.Context, req *GetUserInsightsRequest) (*GetUserInsightsResponse, error) {
	if req == nil {
		req = &GetUserInsightsRequest{}
	}
	out := &GetUserInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igUserId}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
