// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetMediaRequest holds the parameters for GetMedia.
type GetMediaRequest struct {
	IgMediaId string  `json:"-" path:"igMediaId"`
	Fields    *string `json:"-" query:"fields"`
}

// GetMediaResponse is the response type of GetMedia.
type GetMediaResponse = Media

// GetMedia calls GET /{version}/{igMediaId}.
func (c *Client) GetMedia(ctx context.Context, req *GetMediaRequest) (*GetMediaResponse, error) {
	if req == nil {
		req = &GetMediaRequest{}
	}
	out := &GetMediaResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igMediaId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListMediaRequest holds the parameters for ListMedia.
type ListMediaRequest struct {
	IgUserId string  `json:"-" path:"igUserId"`
	Fields   *string `json:"-" query:"fields"`
	Limit    *int    `json:"-" query:"limit"`
	After    *string `json:"-" query:"after"`
	Before   *string `json:"-" query:"before"`
	Since    *int64  `json:"-" query:"since"`
	Until    *int64  `json:"-" query:"until"`
}

// ListMediaResponse is the response type of ListMedia.
type ListMediaResponse = MediaList

// ListMedia calls GET /{version}/{igUserId}/media.
func (c *Client) ListMedia(ctx context.Context, req *ListMediaRequest) (*ListMediaResponse, error) {
	if req == nil {
		req = &ListMediaRequest{}
	}
	out := &ListMediaResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igUserId}/media",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListStoriesRequest holds the parameters for ListStories.
type ListStoriesRequest struct {
	IgUserId string  `json:"-" path:"igUserId"`
	Fields   *string `json:"-" query:"fields"`
}

// ListStoriesResponse is the response type of ListStories.
type ListStoriesResponse = MediaList

// ListStories calls GET /{version}/{igUserId}/stories.
func (c *Client) ListStories(ctx context.Context, req *ListStoriesRequest) (*ListStoriesResponse, error) {
	if req == nil {
		req = &ListStoriesRequest{}
	}
	out := &ListStoriesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igUserId}/stories",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
