// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateMediaContainerRequest holds the parameters for CreateMediaContainer.
type CreateMediaContainerRequest struct {
	IgUserId       string  `json:"-" path:"igUserId"`
	ImageUrl       *string `json:"-" query:"image_url"`
	VideoUrl       *string `json:"-" query:"video_url"`
	MediaType      *string `json:"-" query:"media_type"`
	Caption        *string `json:"-" query:"caption"`
	IsCarouselItem *bool   `json:"-" query:"is_carousel_item"`
	Children       *string `json:"-" query:"children"`
	CoverUrl       *string `json:"-" query:"cover_url"`
	ThumbOffset    *int64  `json:"-" query:"thumb_offset"`
	ShareToFeed    *bool   `json:"-" query:"share_to_feed"`
	LocationId     *string `json:"-" query:"location_id"`
	UserTags       *string `json:"-" query:"user_tags"`
	ProductTags    *string `json:"-" query:"product_tags"`
	Collaborators  *string `json:"-" query:"collaborators"`
	AltText        *string `json:"-" query:"alt_text"`
	AudioName      *string `json:"-" query:"audio_name"`
}

// CreateMediaContainer calls POST /{version}/{igUserId}/media.
func (c *Client) CreateMediaContainer(ctx context.Context, req *CreateMediaContainerRequest) (*CreateMediaContainerResponse, error) {
	if req == nil {
		req = &CreateMediaContainerRequest{}
	}
	out := &CreateMediaContainerResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{igUserId}/media",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetContainerStatusRequest holds the parameters for GetContainerStatus.
type GetContainerStatusRequest struct {
	IgContainerId string  `json:"-" path:"igContainerId"`
	Fields        *string `json:"-" query:"fields"`
}

// GetContainerStatus calls GET /{version}/{igContainerId}.
func (c *Client) GetContainerStatus(ctx context.Context, req *GetContainerStatusRequest) (*GetContainerStatusResponse, error) {
	if req == nil {
		req = &GetContainerStatusRequest{}
	}
	out := &GetContainerStatusResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igContainerId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPublishingLimitRequest holds the parameters for GetPublishingLimit.
type GetPublishingLimitRequest struct {
	IgUserId string  `json:"-" path:"igUserId"`
	Fields   *string `json:"-" query:"fields"`
	Since    *int64  `json:"-" query:"since"`
}

// GetPublishingLimit calls GET /{version}/{igUserId}/content_publishing_limit.
func (c *Client) GetPublishingLimit(ctx context.Context, req *GetPublishingLimitRequest) (*GetPublishingLimitResponse, error) {
	if req == nil {
		req = &GetPublishingLimitRequest{}
	}
	out := &GetPublishingLimitResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{igUserId}/content_publishing_limit",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishMediaRequest holds the parameters for PublishMedia.
type PublishMediaRequest struct {
	IgUserId   string  `json:"-" path:"igUserId"`
	CreationId *string `json:"-" query:"creation_id"`
}

// PublishMedia calls POST /{version}/{igUserId}/media_publish.
func (c *Client) PublishMedia(ctx context.Context, req *PublishMediaRequest) (*PublishMediaResponse, error) {
	if req == nil {
		req = &PublishMediaRequest{}
	}
	out := &PublishMediaResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{igUserId}/media_publish",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
