// Code generated by connector-gen. DO NOT EDIT.

package instagram

import (
	"github.com/pax-beehive/connector"
)

// Comment is the Comment model.
type Comment struct {
	From      *CommentFrom        `json:"from,omitempty"`
	Hidden    *bool               `json:"hidden,omitempty"`
	Id        *string             `json:"id,omitempty"`
	LikeCount *int                `json:"like_count,omitempty"`
	Replies   *CommentList        `json:"replies,omitempty"`
	Text      *string             `json:"text,omitempty"`
	Timestamp *connector.DateTime `json:"timestamp,omitempty"`
	Username  *string             `json:"username,omitempty"`
}

// CommentFrom is the CommentFrom model.
type CommentFrom struct {
	Id       *string `json:"id,omitempty"`
	Username *string `json:"username,omitempty"`
}

// CommentList is the CommentList model.
type CommentList struct {
	Data   []Comment `json:"data,omitempty"`
	Paging *Paging   `json:"paging,omitempty"`
}

// CreateCommentResponse is the CreateCommentResponse model.
type CreateCommentResponse struct {
	Id *string `json:"id,omitempty"`
}

// CreateMediaContainerResponse is the CreateMediaContainerResponse model.
type CreateMediaContainerResponse struct {
	Id *string `json:"id,omitempty"`
}

// DeleteCommentResponse is the DeleteCommentResponse model.
type DeleteCommentResponse struct {
	Success *bool `json:"success,omitempty"`
}

// GetContainerStatusResponse is the GetContainerStatusResponse model.
type GetContainerStatusResponse struct {
	Id         *string `json:"id,omitempty"`
	Status     *string `json:"status,omitempty"`
	StatusCode *string `json:"status_code,omitempty"`
}

// GetPublishingLimitResponse is the GetPublishingLimitResponse model.
type GetPublishingLimitResponse struct {
	Data []PublishingLimit `json:"data,omitempty"`
}

// HideCommentResponse is the HideCommentResponse model.
type HideCommentResponse struct {
	Success *bool `json:"success,omitempty"`
}

// IGUser is the IGUser model.
type IGUser struct {
	Biography         *string `json:"biography,omitempty"`
	FollowersCount    *int    `json:"followers_count,omitempty"`
	FollowsCount      *int    `json:"follows_count,omitempty"`
	Id                *string `json:"id,omitempty"`
	MediaCount        *int    `json:"media_count,omitempty"`
	Name              *string `json:"name,omitempty"`
	ProfilePictureUrl *string `json:"profile_picture_url,omitempty"`
	Username          *string `json:"username,omitempty"`
	Website           *string `json:"website,omitempty"`
}

// Insight is the Insight model.
type Insight struct {
	Description *string            `json:"description,omitempty"`
	Id          *string            `json:"id,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Period      *string            `json:"period,omitempty"`
	Title       *string            `json:"title,omitempty"`
	TotalValue  *InsightTotalValue `json:"total_value,omitempty"`
	Values      []InsightValue     `json:"values,omitempty"`
}

// InsightList is the InsightList model.
type InsightList struct {
	Data   []Insight `json:"data,omitempty"`
	Paging *Paging   `json:"paging,omitempty"`
}

// InsightTotalValue is the InsightTotalValue model.
type InsightTotalValue struct {
	Value *int64 `json:"value,omitempty"`
}

// InsightValue is the InsightValue model.
type InsightValue struct {
	EndTime *connector.DateTime `json:"end_time,omitempty"`
	Value   any                 `json:"value,omitempty"`
}

// Media is the Media model.
type Media struct {
	AltText          *string             `json:"alt_text,omitempty"`
	Caption          *string             `json:"caption,omitempty"`
	Children         *MediaList          `json:"children,omitempty"`
	CommentsCount    *int                `json:"comments_count,omitempty"`
	Id               *string             `json:"id,omitempty"`
	IsCommentEnabled *bool               `json:"is_comment_enabled,omitempty"`
	IsSharedToFeed   *bool               `json:"is_shared_to_feed,omitempty"`
	LikeCount        *int                `json:"like_count,omitempty"`
	MediaProductType *string             `json:"media_product_type,omitempty"`
	MediaType        *string             `json:"media_type,omitempty"`
	MediaUrl         *string             `json:"media_url,omitempty"`
	Permalink        *string             `json:"permalink,omitempty"`
	Shortcode        *string             `json:"shortcode,omitempty"`
	ThumbnailUrl     *string             `json:"thumbnail_url,omitempty"`
	Timestamp        *connector.DateTime `json:"timestamp,omitempty"`
	Username         *string             `json:"username,omitempty"`
}

// MediaList is the MediaList model.
type MediaList struct {
	Data   []Media `json:"data,omitempty"`
	Paging *Paging `json:"paging,omitempty"`
}

// Paging is the Paging model.
type Paging struct {
	Cursors  *PagingCursors `json:"cursors,omitempty"`
	Next     *string        `json:"next,omitempty"`
	Previous *string        `json:"previous,omitempty"`
}

// PagingCursors is the PagingCursors model.
type PagingCursors struct {
	After  *string `json:"after,omitempty"`
	Before *string `json:"before,omitempty"`
}

// PublishMediaResponse is the PublishMediaResponse model.
type PublishMediaResponse struct {
	Id *string `json:"id,omitempty"`
}

// PublishingLimit is the PublishingLimit model.
type PublishingLimit struct {
	Config     *PublishingLimitConfig `json:"config,omitempty"`
	QuotaUsage *int                   `json:"quota_usage,omitempty"`
}

// PublishingLimitConfig is the PublishingLimitConfig model.
type PublishingLimitConfig struct {
	QuotaDuration *int `json:"quota_duration,omitempty"`
	QuotaTotal    *int `json:"quota_total,omitempty"`
}

// RefreshAccessTokenResponse is the RefreshAccessTokenResponse model.
type RefreshAccessTokenResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int64  `json:"expires_in,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// ReplyToCommentResponse is the ReplyToCommentResponse model.
type ReplyToCommentResponse struct {
	Id *string `json:"id,omitempty"`
}
