// Code generated by connector-gen. DO NOT EDIT.

package threads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetMediaInsightsRequest holds the parameters for GetMediaInsights.
type GetMediaInsightsRequest struct {
	InsightsMediaId string  `json:"-" path:"insightsMediaId"`
	Metric          *string `json:"-" query:"metric"`
}

// GetMediaInsightsResponse is the response type of GetMediaInsights.
type GetMediaInsightsResponse = InsightList

// GetMediaInsights calls GET /{version}/{insightsMediaId}/insights.
func (c *Client) GetMediaInsights(ctx context.Context, req *GetMediaInsightsRequest) (*GetMediaInsightsResponse, error) {
	if req == nil {
		req = &GetMediaInsightsRequest{}
	}
	out := &GetMediaInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{insightsMediaId}/insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserInsightsRequest holds the parameters for GetUserInsights.
type GetUserInsightsRequest struct {
	InsightsUserId string  `json:"-" path:"insightsUserId"`
	Metric         *string `json:"-" query:"metric"`
	Since          *int64  `json:"-" query:"since"`
	Until          *int64  `json:"-" query:"until"`
}

// GetUserInsightsResponse is the response type of GetUserInsights.
type GetUserInsightsResponse = InsightList

// GetUserInsights calls GET /{version}/{insightsUserId}/threads_insights.
func (c *Client) GetUserInsights(ctx context.Context, req *GetUserInsightsRequest) (*GetUserInsightsResponse, error) {
	if req == nil {
		req = &GetUserInsightsRequest{}
	}
	out := &GetUserInsightsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{insightsUserId}/threads_insights",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
