// Code generated by connector-gen. DO NOT EDIT.

package threads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetProfileRequest holds the parameters for GetProfile.
type GetProfileRequest struct {
	ProfileUserId string  `json:"-" path:"profileUserId"`
	Fields        *string `json:"-" query:"fields"`
}

// GetProfileResponse is the response type of GetProfile.
type GetProfileResponse = ThreadsProfile

// GetProfile calls GET /{version}/{profileUserId}.
func (c *Client) GetProfile(ctx context.Context, req *GetProfileRequest) (*GetProfileResponse, error) {
	if req == nil {
		req = &GetProfileRequest{}
	}
	out := &GetProfileResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{profileUserId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
