// Code generated by connector-gen. DO NOT EDIT.

package threads

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateThreadsContainerRequest holds the parameters for CreateThreadsContainer.
type CreateThreadsContainerRequest struct {
	ThreadsUserId  string  `json:"-" path:"threadsUserId"`
	MediaType      *string `json:"-" query:"media_type"`
	Text           *string `json:"-" query:"text"`
	ImageUrl       *string `json:"-" query:"image_url"`
	VideoUrl       *string `json:"-" query:"video_url"`
	IsCarouselItem *bool   `json:"-" query:"is_carousel_item"`
	Children       *string `json:"-" query:"children"`
	ReplyToId      *string `json:"-" query:"reply_to_id"`
	QuotePostId    *string `json:"-" query:"quote_post_id"`
	ReplyControl   *string `json:"-" query:"reply_control"`
	LinkAttachment *string `json:"-" query:"link_attachment"`
	AltText        *string `json:"-" query:"alt_text"`
}

// CreateThreadsContainer calls POST /{version}/{threadsUserId}/threads.
func (c *Client) CreateThreadsContainer(ctx context.Context, req *CreateThreadsContainerRequest) (*CreateThreadsContainerResponse, error) {
	if req == nil {
		req = &CreateThreadsContainerRequest{}
	}
	out := &CreateThreadsContainerResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{threadsUserId}/threads",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetContainerStatusRequest holds the parameters for GetContainerStatus.
type GetContainerStatusRequest struct {
	ContainerId string  `json:"-" path:"containerId"`
	Fields      *string `json:"-" query:"fields"`
}

// GetContainerStatus calls GET /{version}/{containerId}.
func (c *Client) GetContainerStatus(ctx context.Context, req *GetContainerStatusRequest) (*GetContainerStatusResponse, error) {
	if req == nil {
		req = &GetContainerStatusRequest{}
	}
	out := &GetContainerStatusResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{containerId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPublishingLimitRequest holds the parameters for GetPublishingLimit.
type GetPublishingLimitRequest struct {
	ThreadsUserId string  `json:"-" path:"threadsUserId"`
	Fields        *string `json:"-" query:"fields"`
}

// GetPublishingLimit calls GET /{version}/{threadsUserId}/threads_publishing_limit.
func (c *Client) GetPublishingLimit(ctx context.Context, req *GetPublishingLimitRequest) (*GetPublishingLimitResponse, error) {
	if req == nil {
		req = &GetPublishingLimitRequest{}
	}
	out := &GetPublishingLimitResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/{version}/{threadsUserId}/threads_publishing_limit",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishThreadRequest holds the parameters for PublishThread.
type PublishThreadRequest struct {
	ThreadsUserId string  `json:"-" path:"threadsUserId"`
	CreationId    *string `json:"-" query:"creation_id"`
}

// PublishThread calls POST /{version}/{threadsUserId}/threads_publish.
func (c *Client) PublishThread(ctx context.Context, req *PublishThreadRequest) (*PublishThreadResponse, error) {
	if req == nil {
		req = &PublishThreadRequest{}
	}
	out := &PublishThreadResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/{version}/{threadsUserId}/threads_publish",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
