// Code generated by connector-gen. DO NOT EDIT.

package threads

import (
	"github.com/pax-beehive/connector"
)

// CreateThreadsContainerResponse is the CreateThreadsContainerResponse model.
type CreateThreadsContainerResponse struct {
	Id *string `json:"id,omitempty"`
}

// ExchangeAccessTokenResponse is the ExchangeAccessTokenResponse model.
type ExchangeAccessTokenResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int64  `json:"expires_in,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// GetContainerStatusResponse is the GetContainerStatusResponse model.
type GetContainerStatusResponse struct {
	ErrorMessage *string `json:"error_message,omitempty"`
	Id           *string `json:"id,omitempty"`
	Status       *string `json:"status,omitempty"`
}

// GetPublishingLimitResponse is the GetPublishingLimitResponse model.
type GetPublishingLimitResponse struct {
	Data []PublishingLimitData `json:"data,omitempty"`
}

// HideReplyResponse is the HideReplyResponse model.
type HideReplyResponse struct {
	Success *bool `json:"success,omitempty"`
}

// Insight is the Insight model.
type Insight struct {
	Description *string            `json:"description,omitempty"`
	Id          *string            `json:"id,omitempty"`
	Name        *string            `json:"name,omitempty"`
	Period      *string            `json:"period,omitempty"`
	Title       *string            `json:"title,omitempty"`
	TotalValue  *InsightTotalValue `json:"total_value,omitempty"`
	Values      []InsightValue     `json:"values,omitempty"`
}

// InsightList is the InsightList model.
type InsightList struct {
	Data   []Insight `json:"data,omitempty"`
	Paging *Paging   `json:"paging,omitempty"`
}

// InsightTotalValue is the InsightTotalValue model.
type InsightTotalValue struct {
	Value *int64 `json:"value,omitempty"`
}

// InsightValue is the InsightValue model.
type InsightValue struct {
	EndTime *connector.DateTime `json:"end_time,omitempty"`
	Value   any                 `json:"value,omitempty"`
}

// Paging is the Paging model.
type Paging struct {
	Cursors  *PagingCursors `json:"cursors,omitempty"`
	Next     *string        `json:"next,omitempty"`
	Previous *string        `json:"previous,omitempty"`
}

// PagingCursors is the PagingCursors model.
type PagingCursors struct {
	After  *string `json:"after,omitempty"`
	Before *string `json:"before,omitempty"`
}

// PublishThreadResponse is the PublishThreadResponse model.
type PublishThreadResponse struct {
	Id *string `json:"id,omitempty"`
}

// PublishingLimitData is the PublishingLimitData model.
type PublishingLimitData struct {
	Config          *QuotaConfig `json:"config,omitempty"`
	QuotaUsage      *int         `json:"quota_usage,omitempty"`
	ReplyConfig     *QuotaConfig `json:"reply_config,omitempty"`
	ReplyQuotaUsage *int         `json:"reply_quota_usage,omitempty"`
}

// QuotaConfig is the QuotaConfig model.
type QuotaConfig struct {
	QuotaDuration *int64 `json:"quota_duration,omitempty"`
	QuotaTotal    *int64 `json:"quota_total,omitempty"`
}

// RefreshAccessTokenResponse is the RefreshAccessTokenResponse model.
type RefreshAccessTokenResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int64  `json:"expires_in,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// ThreadMedia is the ThreadMedia model.
type ThreadMedia struct {
	AltText          *string             `json:"alt_text,omitempty"`
	Children         *ThreadMediaList    `json:"children,omitempty"`
	HasReplies       *bool               `json:"has_replies,omitempty"`
	Id               *string             `json:"id,omitempty"`
	IsQuotePost      *bool               `json:"is_quote_post,omitempty"`
	MediaProductType *string             `json:"media_product_type,omitempty"`
	MediaType        *string             `json:"media_type,omitempty"`
	MediaUrl         *string             `json:"media_url,omitempty"`
	Owner            *ThreadsOwner       `json:"owner,omitempty"`
	Permalink        *string             `json:"permalink,omitempty"`
	ReplyAudience    *string             `json:"reply_audience,omitempty"`
	Shortcode        *string             `json:"shortcode,omitempty"`
	Text             *string             `json:"text,omitempty"`
	ThumbnailUrl     *string             `json:"thumbnail_url,omitempty"`
	Timestamp        *connector.DateTime `json:"timestamp,omitempty"`
	Username         *string             `json:"username,omitempty"`
}

// ThreadMediaList is the ThreadMediaList model.
type ThreadMediaList struct {
	Data   []ThreadMedia `json:"data,omitempty"`
	Paging *Paging       `json:"paging,omitempty"`
}

// ThreadsOwner is the ThreadsOwner model.
type ThreadsOwner struct {
	Id *string `json:"id,omitempty"`
}

// ThreadsProfile is the ThreadsProfile model.
type ThreadsProfile struct {
	Id                       *string `json:"id,omitempty"`
	Name                     *string `json:"name,omitempty"`
	ThreadsBiography         *string `json:"threads_biography,omitempty"`
	ThreadsProfilePictureUrl *string `json:"threads_profile_picture_url,omitempty"`
	Username                 *string `json:"username,omitempty"`
}
