// Code generated by connector-gen. DO NOT EDIT.

package x

import (
	"context"
	"github.com/pax-beehive/connector"
)

// LikeTweetRequest holds the parameters for LikeTweet.
type LikeTweetRequest struct {
	Id      string  `json:"-" path:"id"`
	TweetId *string `json:"tweet_id,omitempty"`
}

// LikeTweet calls POST /2/users/{id}/likes.
func (c *Client) LikeTweet(ctx context.Context, req *LikeTweetRequest) (*LikeTweetResponse, error) {
	if req == nil {
		req = &LikeTweetRequest{}
	}
	out := &LikeTweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/2/users/{id}/likes",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetweetRequest holds the parameters for Retweet.
type RetweetRequest struct {
	Id      string  `json:"-" path:"id"`
	TweetId *string `json:"tweet_id,omitempty"`
}

// Retweet calls POST /2/users/{id}/retweets.
func (c *Client) Retweet(ctx context.Context, req *RetweetRequest) (*RetweetResponse, error) {
	if req == nil {
		req = &RetweetRequest{}
	}
	out := &RetweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/2/users/{id}/retweets",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnlikeTweetRequest holds the parameters for UnlikeTweet.
type UnlikeTweetRequest struct {
	Id      string `json:"-" path:"id"`
	TweetId string `json:"-" path:"tweet_id"`
}

// UnlikeTweetResponse is the response type of UnlikeTweet.
type UnlikeTweetResponse = LikeTweetResponse

// UnlikeTweet calls DELETE /2/users/{id}/likes/{tweet_id}.
func (c *Client) UnlikeTweet(ctx context.Context, req *UnlikeTweetRequest) (*UnlikeTweetResponse, error) {
	if req == nil {
		req = &UnlikeTweetRequest{}
	}
	out := &UnlikeTweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/2/users/{id}/likes/{tweet_id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnretweetRequest holds the parameters for Unretweet.
type UnretweetRequest struct {
	Id            string `json:"-" path:"id"`
	SourceTweetId string `json:"-" path:"source_tweet_id"`
}

// UnretweetResponse is the response type of Unretweet.
type UnretweetResponse = RetweetResponse

// Unretweet calls DELETE /2/users/{id}/retweets/{source_tweet_id}.
func (c *Client) Unretweet(ctx context.Context, req *UnretweetRequest) (*UnretweetResponse, error) {
	if req == nil {
		req = &UnretweetRequest{}
	}
	out := &UnretweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/2/users/{id}/retweets/{source_tweet_id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
