// Code generated by connector-gen. DO NOT EDIT.

package x

import (
	"context"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
)

type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
	{
		name:   "LikeTweet",
		method: "POST",
		path:   "/2/users//likes",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.LikeTweet(ctx, &LikeTweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.LikeTweet(ctx, nil)
		},
	},
	{
		name:   "Retweet",
		method: "POST",
		path:   "/2/users//retweets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Retweet(ctx, &RetweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.Retweet(ctx, nil)
		},
	},
	{
		name:   "UnlikeTweet",
		method: "DELETE",
		path:   "/2/users//likes/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.UnlikeTweet(ctx, &UnlikeTweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.UnlikeTweet(ctx, nil)
		},
	},
	{
		name:   "Unretweet",
		method: "DELETE",
		path:   "/2/users//retweets/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.Unretweet(ctx, &UnretweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.Unretweet(ctx, nil)
		},
	},
	{
		name:   "SearchRecentTweets",
		method: "GET",
		path:   "/2/tweets/search/recent",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchRecentTweets(ctx, &SearchRecentTweetsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.SearchRecentTweets(ctx, nil)
		},
	},
	{
		name:   "CreateTweet",
		method: "POST",
		path:   "/2/tweets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateTweet(ctx, &CreateTweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.CreateTweet(ctx, nil)
		},
	},
	{
		name:   "DeleteTweet",
		method: "DELETE",
		path:   "/2/tweets/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteTweet(ctx, &DeleteTweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.DeleteTweet(ctx, nil)
		},
	},
	{
		name:   "GetTweet",
		method: "GET",
		path:   "/2/tweets/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetTweet(ctx, &GetTweetRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetTweet(ctx, nil)
		},
	},
	{
		name:   "GetTweets",
		method: "GET",
		path:   "/2/tweets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetTweets(ctx, &GetTweetsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetTweets(ctx, nil)
		},
	},
	{
		name:   "GetMe",
		method: "GET",
		path:   "/2/users/me",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetMe(ctx, &GetMeRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetMe(ctx, nil)
		},
	},
	{
		name:   "GetUserByUsername",
		method: "GET",
		path:   "/2/users/by/username/",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.GetUserByUsername(ctx, &GetUserByUsernameRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.GetUserByUsername(ctx, nil)
		},
	},
	{
		name:   "ListUserMentions",
		method: "GET",
		path:   "/2/users//mentions",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListUserMentions(ctx, &ListUserMentionsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListUserMentions(ctx, nil)
		},
	},
	{
		name:   "ListUserTweets",
		method: "GET",
		path:   "/2/users//tweets",
		resp:   "{}",
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.ListUserTweets(ctx, &ListUserTweetsRequest{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.ListUserTweets(ctx, nil)
		},
	},
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{AccessToken: "t", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
