// Code generated by connector-gen. DO NOT EDIT.

package x

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateTweetRequest holds the parameters for CreateTweet.
type CreateTweetRequest struct {
	ForSuperFollowersOnly *bool       `json:"for_super_followers_only,omitempty"`
	Geo                   *TweetGeo   `json:"geo,omitempty"`
	Media                 *TweetMedia `json:"media,omitempty"`
	Poll                  *TweetPoll  `json:"poll,omitempty"`
	QuoteTweetId          *string     `json:"quote_tweet_id,omitempty"`
	Reply                 *TweetReply `json:"reply,omitempty"`
	ReplySettings         *string     `json:"reply_settings,omitempty"`
	Text                  *string     `json:"text,omitempty"`
}

// CreateTweet calls POST /2/tweets.
func (c *Client) CreateTweet(ctx context.Context, req *CreateTweetRequest) (*CreateTweetResponse, error) {
	if req == nil {
		req = &CreateTweetRequest{}
	}
	out := &CreateTweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/2/tweets",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteTweetRequest holds the parameters for DeleteTweet.
type DeleteTweetRequest struct {
	Id string `json:"-" path:"id"`
}

// DeleteTweet calls DELETE /2/tweets/{id}.
func (c *Client) DeleteTweet(ctx context.Context, req *DeleteTweetRequest) (*DeleteTweetResponse, error) {
	if req == nil {
		req = &DeleteTweetRequest{}
	}
	out := &DeleteTweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/2/tweets/{id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTweetRequest holds the parameters for GetTweet.
type GetTweetRequest struct {
	Id          string  `json:"-" path:"id"`
	TweetFields *string `json:"-" query:"tweet.fields"`
	Expansions  *string `json:"-" query:"expansions"`
	UserFields  *string `json:"-" query:"user.fields"`
	MediaFields *string `json:"-" query:"media.fields"`
}

// GetTweet calls GET /2/tweets/{id}.
func (c *Client) GetTweet(ctx context.Context, req *GetTweetRequest) (*GetTweetResponse, error) {
	if req == nil {
		req = &GetTweetRequest{}
	}
	out := &GetTweetResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/tweets/{id}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTweetsRequest holds the parameters for GetTweets.
type GetTweetsRequest struct {
	Ids         *string `json:"-" query:"ids"`
	TweetFields *string `json:"-" query:"tweet.fields"`
	Expansions  *string `json:"-" query:"expansions"`
	UserFields  *string `json:"-" query:"user.fields"`
	MediaFields *string `json:"-" query:"media.fields"`
}

// GetTweets calls GET /2/tweets.
func (c *Client) GetTweets(ctx context.Context, req *GetTweetsRequest) (*GetTweetsResponse, error) {
	if req == nil {
		req = &GetTweetsRequest{}
	}
	out := &GetTweetsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/tweets",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
