// Code generated by connector-gen. DO NOT EDIT.

package x

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetMeRequest holds the parameters for GetMe.
type GetMeRequest struct {
	UserFields *string `json:"-" query:"user.fields"`
}

// GetMe calls GET /2/users/me.
func (c *Client) GetMe(ctx context.Context, req *GetMeRequest) (*GetMeResponse, error) {
	if req == nil {
		req = &GetMeRequest{}
	}
	out := &GetMeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/users/me",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserByUsernameRequest holds the parameters for GetUserByUsername.
type GetUserByUsernameRequest struct {
	Username   string  `json:"-" path:"username"`
	UserFields *string `json:"-" query:"user.fields"`
}

// GetUserByUsername calls GET /2/users/by/username/{username}.
func (c *Client) GetUserByUsername(ctx context.Context, req *GetUserByUsernameRequest) (*GetUserByUsernameResponse, error) {
	if req == nil {
		req = &GetUserByUsernameRequest{}
	}
	out := &GetUserByUsernameResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/users/by/username/{username}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListUserMentionsRequest holds the parameters for ListUserMentions.
type ListUserMentionsRequest struct {
	Id              string  `json:"-" path:"id"`
	MaxResults      *int    `json:"-" query:"max_results"`
	PaginationToken *string `json:"-" query:"pagination_token"`
	SinceId         *string `json:"-" query:"since_id"`
	UntilId         *string `json:"-" query:"until_id"`
	StartTime       *string `json:"-" query:"start_time"`
	EndTime         *string `json:"-" query:"end_time"`
	TweetFields     *string `json:"-" query:"tweet.fields"`
	Expansions      *string `json:"-" query:"expansions"`
	UserFields      *string `json:"-" query:"user.fields"`
}

// ListUserMentionsResponse is the response type of ListUserMentions.
type ListUserMentionsResponse = TweetList

// ListUserMentions calls GET /2/users/{id}/mentions.
func (c *Client) ListUserMentions(ctx context.Context, req *ListUserMentionsRequest) (*ListUserMentionsResponse, error) {
	if req == nil {
		req = &ListUserMentionsRequest{}
	}
	out := &ListUserMentionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/users/{id}/mentions",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListUserTweetsRequest holds the parameters for ListUserTweets.
type ListUserTweetsRequest struct {
	Id              string  `json:"-" path:"id"`
	MaxResults      *int    `json:"-" query:"max_results"`
	PaginationToken *string `json:"-" query:"pagination_token"`
	SinceId         *string `json:"-" query:"since_id"`
	UntilId         *string `json:"-" query:"until_id"`
	Exclude         *string `json:"-" query:"exclude"`
	StartTime       *string `json:"-" query:"start_time"`
	EndTime         *string `json:"-" query:"end_time"`
	TweetFields     *string `json:"-" query:"tweet.fields"`
	Expansions      *string `json:"-" query:"expansions"`
	UserFields      *string `json:"-" query:"user.fields"`
	MediaFields     *string `json:"-" query:"media.fields"`
}

// ListUserTweetsResponse is the response type of ListUserTweets.
type ListUserTweetsResponse = TweetList

// ListUserTweets calls GET /2/users/{id}/tweets.
func (c *Client) ListUserTweets(ctx context.Context, req *ListUserTweetsRequest) (*ListUserTweetsResponse, error) {
	if req == nil {
		req = &ListUserTweetsRequest{}
	}
	out := &ListUserTweetsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/2/users/{id}/tweets",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
