// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// AddAppointmentRequest holds the parameters for AddAppointment.
type AddAppointmentRequest struct {
	AddAppointmentRequestId *int                    `json:"AddAppointmentRequestId,omitempty"`
	ApplyPayment            *bool                   `json:"ApplyPayment,omitempty"`
	ClientId                *string                 `json:"ClientId,omitempty"`
	Duration                *int                    `json:"Duration,omitempty"`
	EndDateTime             *connector.DateTime     `json:"EndDateTime,omitempty"`
	GenderPreference        *string                 `json:"GenderPreference,omitempty"`
	IsWaitlist              *bool                   `json:"IsWaitlist,omitempty"`
	ItineraryEvents         []ItineraryEventRequest `json:"ItineraryEvents,omitempty"`
	LocationId              *int                    `json:"LocationId,omitempty"`
	Notes                   *string                 `json:"Notes,omitempty"`
	PartnerExternalId       *string                 `json:"PartnerExternalId,omitempty"`
	ProviderId              *string                 `json:"ProviderId,omitempty"`
	ResourceIds             []int                   `json:"ResourceIds,omitempty"`
	SendEmail               *bool                   `json:"SendEmail,omitempty"`
	SessionTypeId           *int                    `json:"SessionTypeId,omitempty"`
	StaffId                 *int64                  `json:"StaffId,omitempty"`
	StaffRequested          *bool                   `json:"StaffRequested,omitempty"`
	StartDateTime           *connector.DateTime     `json:"StartDateTime,omitempty"`
	Test                    *bool                   `json:"Test,omitempty"`
}

// AddAppointment calls POST /public/v{version}/appointment/addappointment.
func (c *Client) AddAppointment(ctx context.Context, req *AddAppointmentRequest) (*AddAppointmentResponse, error) {
	if req == nil {
		req = &AddAppointmentRequest{}
	}
	out := &AddAppointmentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/appointment/addappointment",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddAppointmentAddOnRequest holds the parameters for AddAppointmentAddOn.
type AddAppointmentAddOnRequest struct {
	ApplyPayment  *bool  `json:"ApplyPayment,omitempty"`
	AppointmentId *int64 `json:"AppointmentId,omitempty"`
	SessionTypeId *int   `json:"SessionTypeId,omitempty"`
	StaffId       *int64 `json:"StaffId,omitempty"`
	Test          *bool  `json:"Test,omitempty"`
}

// AddAppointmentAddOn calls POST /public/v{version}/appointment/addappointmentaddon.
func (c *Client) AddAppointmentAddOn(ctx context.Context, req *AddAppointmentAddOnRequest) (*AddAppointmentAddOnResponse, error) {
	if req == nil {
		req = &AddAppointmentAddOnRequest{}
	}
	out := &AddAppointmentAddOnResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/appointment/addappointmentaddon",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddAvailabilitiesRequest holds the parameters for AddAvailabilities.
type AddAvailabilitiesRequest struct {
	DaysOfWeek             []string            `json:"DaysOfWeek,omitempty"`
	EndDateTime            *connector.DateTime `json:"EndDateTime,omitempty"`
	IsUnavailable          *bool               `json:"IsUnavailable,omitempty"`
	LocationID             *int                `json:"LocationID,omitempty"`
	ProgramIDs             []int               `json:"ProgramIDs,omitempty"`
	PublicDisplay          *string             `json:"PublicDisplay,omitempty"`
	StaffIDs               []int64             `json:"StaffIDs,omitempty"`
	StartDateTime          *connector.DateTime `json:"StartDateTime,omitempty"`
	Test                   *bool               `json:"Test,omitempty"`
	UnavailableDescription *string             `json:"UnavailableDescription,omitempty"`
}

// AddAvailabilities calls POST /public/v{version}/appointment/availabilities.
func (c *Client) AddAvailabilities(ctx context.Context, req *AddAvailabilitiesRequest) (*AddAvailabilitiesResponse, error) {
	if req == nil {
		req = &AddAvailabilitiesRequest{}
	}
	out := &AddAvailabilitiesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/appointment/availabilities",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddMultipleAppointmentsRequest holds the parameters for AddMultipleAppointments.
type AddMultipleAppointmentsRequest struct {
	AddAppointmentRequests []AppointmentControllerAddAppointmentRequest `json:"AddAppointmentRequests,omitempty"`
}

// AddMultipleAppointments calls POST /public/v{version}/appointment/addmultipleappointments.
func (c *Client) AddMultipleAppointments(ctx context.Context, req *AddMultipleAppointmentsRequest) (*AddMultipleAppointmentsResponse, error) {
	if req == nil {
		req = &AddMultipleAppointmentsRequest{}
	}
	out := &AddMultipleAppointmentsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/appointment/addmultipleappointments",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAppointmentAddOnRequest holds the parameters for DeleteAppointmentAddOn.
type DeleteAppointmentAddOnRequest struct {
	Id *int64 `json:"-" query:"id"`
}

// DeleteAppointmentAddOnResponse is the (empty) response type of DeleteAppointmentAddOn.
type DeleteAppointmentAddOnResponse struct{}

// DeleteAppointmentAddOn calls DELETE /public/v{version}/appointment/deleteappointmentaddon.
func (c *Client) DeleteAppointmentAddOn(ctx context.Context, req *DeleteAppointmentAddOnRequest) (*DeleteAppointmentAddOnResponse, error) {
	if req == nil {
		req = &DeleteAppointmentAddOnRequest{}
	}
	out := &DeleteAppointmentAddOnResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/appointment/deleteappointmentaddon",
		Req:    req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteAvailabilityRequest holds the parameters for DeleteAvailability.
type DeleteAvailabilityRequest struct {
	DeleteAvailabilityRequestAvailabilityId *int  `json:"-" query:"deleteAvailabilityRequest.availabilityId"`
	DeleteAvailabilityRequestTest           *bool `json:"-" query:"deleteAvailabilityRequest.test"`
}

// DeleteAvailabilityResponse is the (empty) response type of DeleteAvailability.
type DeleteAvailabilityResponse struct{}

// DeleteAvailability calls DELETE /public/v{version}/appointment/availability.
func (c *Client) DeleteAvailability(ctx context.Context, req *DeleteAvailabilityRequest) (*DeleteAvailabilityResponse, error) {
	if req == nil {
		req = &DeleteAvailabilityRequest{}
	}
	out := &DeleteAvailabilityResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/appointment/availability",
		Req:    req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetActiveSessionTimesRequest holds the parameters for GetActiveSessionTimes.
type GetActiveSessionTimesRequest struct {
	EndTime        *connector.DateTime `json:"-" query:"request.endTime"`
	Limit          *int                `json:"-" query:"request.limit"`
	Offset         *int                `json:"-" query:"request.offset"`
	ScheduleType   *string             `json:"-" query:"request.scheduleType"`
	SessionTypeIds []int               `json:"-" query:"request.sessionTypeIds"`
	StartTime      *connector.DateTime `json:"-" query:"request.startTime"`
}

// GetActiveSessionTimes calls GET /public/v{version}/appointment/activesessiontimes.
func (c *Client) GetActiveSessionTimes(ctx context.Context, req *GetActiveSessionTimesRequest) (*GetActiveSessionTimesResponse, error) {
	if req == nil {
		req = &GetActiveSessionTimesRequest{}
	}
	out := &GetActiveSessionTimesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/activesessiontimes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAddOnsRequest holds the parameters for GetAddOns.
type GetAddOnsRequest struct {
	Limit   *int `json:"-" query:"request.limit"`
	Offset  *int `json:"-" query:"request.offset"`
	StaffId *int `json:"-" query:"request.staffId"`
}

// GetAddOns calls GET /public/v{version}/appointment/addons.
func (c *Client) GetAddOns(ctx context.Context, req *GetAddOnsRequest) (*GetAddOnsResponse, error) {
	if req == nil {
		req = &GetAddOnsRequest{}
	}
	out := &GetAddOnsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/addons",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAppointmentOptionsRequest holds the parameters for GetAppointmentOptions.
type GetAppointmentOptionsRequest struct {
}

// GetAppointmentOptions calls GET /public/v{version}/appointment/appointmentoptions.
func (c *Client) GetAppointmentOptions(ctx context.Context, req *GetAppointmentOptionsRequest) (*GetAppointmentOptionsResponse, error) {
	if req == nil {
		req = &GetAppointmentOptionsRequest{}
	}
	out := &GetAppointmentOptionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/appointmentoptions",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAvailableDatesRequest holds the parameters for GetAvailableDates.
type GetAvailableDatesRequest struct {
	EndDate       *connector.DateTime `json:"-" query:"request.endDate"`
	LocationId    *int                `json:"-" query:"request.locationId"`
	StaffId       *int64              `json:"-" query:"request.staffId"`
	StartDate     *connector.DateTime `json:"-" query:"request.startDate"`
	SessionTypeId *int                `json:"-" query:"request.sessionTypeId"`
}

// GetAvailableDates calls GET /public/v{version}/appointment/availabledates.
func (c *Client) GetAvailableDates(ctx context.Context, req *GetAvailableDatesRequest) (*GetAvailableDatesResponse, error) {
	if req == nil {
		req = &GetAvailableDatesRequest{}
	}
	out := &GetAvailableDatesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/availabledates",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetBookableItemsRequest holds the parameters for GetBookableItems.
type GetBookableItemsRequest struct {
	AppointmentId               *int64              `json:"-" query:"request.appointmentId"`
	EndDate                     *connector.DateTime `json:"-" query:"request.endDate"`
	IgnoreDefaultSessionLength  *bool               `json:"-" query:"request.ignoreDefaultSessionLength"`
	IncludeResourceAvailability *bool               `json:"-" query:"request.includeResourceAvailability"`
	Limit                       *int                `json:"-" query:"request.limit"`
	LocationIds                 []int               `json:"-" query:"request.locationIds"`
	Offset                      *int                `json:"-" query:"request.offset"`
	StaffIds                    []int64             `json:"-" query:"request.staffIds"`
	StartDate                   *connector.DateTime `json:"-" query:"request.startDate"`
	SessionTypeIds              []int               `json:"-" query:"request.sessionTypeIds"`
}

// GetBookableItems calls GET /public/v{version}/appointment/bookableitems.
func (c *Client) GetBookableItems(ctx context.Context, req *GetBookableItemsRequest) (*GetBookableItemsResponse, error) {
	if req == nil {
		req = &GetBookableItemsRequest{}
	}
	out := &GetBookableItemsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/bookableitems",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetScheduleItemsRequest holds the parameters for GetScheduleItems.
type GetScheduleItemsRequest struct {
	EndDate               *connector.DateTime `json:"-" query:"request.endDate"`
	IgnorePrepFinishTimes *bool               `json:"-" query:"request.ignorePrepFinishTimes"`
	Limit                 *int                `json:"-" query:"request.limit"`
	LocationIds           []int               `json:"-" query:"request.locationIds"`
	Offset                *int                `json:"-" query:"request.offset"`
	StaffIds              []int64             `json:"-" query:"request.staffIds"`
	StartDate             *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetScheduleItems calls GET /public/v{version}/appointment/scheduleitems.
func (c *Client) GetScheduleItems(ctx context.Context, req *GetScheduleItemsRequest) (*GetScheduleItemsResponse, error) {
	if req == nil {
		req = &GetScheduleItemsRequest{}
	}
	out := &GetScheduleItemsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/scheduleitems",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStaffAppointmentsRequest holds the parameters for GetStaffAppointments.
type GetStaffAppointmentsRequest struct {
	AppointmentIds           []int               `json:"-" query:"request.appointmentIds"`
	ClientId                 *string             `json:"-" query:"request.clientId"`
	EndDate                  *connector.DateTime `json:"-" query:"request.endDate"`
	Limit                    *int                `json:"-" query:"request.limit"`
	LocationIds              []int               `json:"-" query:"request.locationIds"`
	Offset                   *int                `json:"-" query:"request.offset"`
	StaffIds                 []int64             `json:"-" query:"request.staffIds"`
	StartDate                *connector.DateTime `json:"-" query:"request.startDate"`
	UseSiteSettingsStaffName *bool               `json:"-" query:"request.useSiteSettingsStaffName"`
}

// GetStaffAppointments calls GET /public/v{version}/appointment/staffappointments.
func (c *Client) GetStaffAppointments(ctx context.Context, req *GetStaffAppointmentsRequest) (*GetStaffAppointmentsResponse, error) {
	if req == nil {
		req = &GetStaffAppointmentsRequest{}
	}
	out := &GetStaffAppointmentsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/staffappointments",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUnavailabilitiesRequest holds the parameters for GetUnavailabilities.
type GetUnavailabilitiesRequest struct {
	EndDate   *connector.DateTime `json:"-" query:"request.endDate"`
	Limit     *int                `json:"-" query:"request.limit"`
	Offset    *int                `json:"-" query:"request.offset"`
	StaffIds  []int64             `json:"-" query:"request.staffIds"`
	StartDate *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetUnavailabilities calls GET /public/v{version}/appointment/unavailabilities.
func (c *Client) GetUnavailabilities(ctx context.Context, req *GetUnavailabilitiesRequest) (*GetUnavailabilitiesResponse, error) {
	if req == nil {
		req = &GetUnavailabilitiesRequest{}
	}
	out := &GetUnavailabilitiesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/appointment/unavailabilities",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveAppointmentFromWaitlistRequest holds the parameters for RemoveAppointmentFromWaitlist.
type RemoveAppointmentFromWaitlistRequest struct {
	WaitlistEntryIds []int `json:"-" query:"request.waitlistEntryIds"`
}

// RemoveAppointmentFromWaitlistResponse is the (empty) response type of RemoveAppointmentFromWaitlist.
type RemoveAppointmentFromWaitlistResponse struct{}

// RemoveAppointmentFromWaitlist calls DELETE /public/v{version}/appointment/appointmentfromwaitlist.
func (c *Client) RemoveAppointmentFromWaitlist(ctx context.Context, req *RemoveAppointmentFromWaitlistRequest) (*RemoveAppointmentFromWaitlistResponse, error) {
	if req == nil {
		req = &RemoveAppointmentFromWaitlistRequest{}
	}
	out := &RemoveAppointmentFromWaitlistResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/appointment/appointmentfromwaitlist",
		Req:    req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAppointmentRequest holds the parameters for UpdateAppointment.
type UpdateAppointmentRequest struct {
	ApplyPayment      *bool               `json:"ApplyPayment,omitempty"`
	AppointmentId     *int64              `json:"AppointmentId,omitempty"`
	EndDateTime       *connector.DateTime `json:"EndDateTime,omitempty"`
	Execute           *string             `json:"Execute,omitempty"`
	GenderPreference  *string             `json:"GenderPreference,omitempty"`
	Notes             *string             `json:"Notes,omitempty"`
	PartnerExternalId *string             `json:"PartnerExternalId,omitempty"`
	ProviderId        *string             `json:"ProviderId,omitempty"`
	ResourceIds       []int               `json:"ResourceIds,omitempty"`
	SendEmail         *bool               `json:"SendEmail,omitempty"`
	SessionTypeId     *int                `json:"SessionTypeId,omitempty"`
	StaffId           *int64              `json:"StaffId,omitempty"`
	StartDateTime     *connector.DateTime `json:"StartDateTime,omitempty"`
	Test              *bool               `json:"Test,omitempty"`
}

// UpdateAppointment calls POST /public/v{version}/appointment/updateappointment.
func (c *Client) UpdateAppointment(ctx context.Context, req *UpdateAppointmentRequest) (*UpdateAppointmentResponse, error) {
	if req == nil {
		req = &UpdateAppointmentRequest{}
	}
	out := &UpdateAppointmentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/appointment/updateappointment",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAvailabilityRequest holds the parameters for UpdateAvailability.
type UpdateAvailabilityRequest struct {
	AvailabilityIds        []int               `json:"AvailabilityIds,omitempty"`
	DaysOfWeek             []string            `json:"DaysOfWeek,omitempty"`
	EndDateTime            *connector.DateTime `json:"EndDateTime,omitempty"`
	LocationId             *int                `json:"LocationId,omitempty"`
	ProgramIds             []int               `json:"ProgramIds,omitempty"`
	PublicDisplay          *string             `json:"PublicDisplay,omitempty"`
	StartDateTime          *connector.DateTime `json:"StartDateTime,omitempty"`
	Test                   *bool               `json:"Test,omitempty"`
	UnavailableDescription *string             `json:"UnavailableDescription,omitempty"`
}

// UpdateAvailability calls PUT /public/v{version}/appointment/availabilities.
func (c *Client) UpdateAvailability(ctx context.Context, req *UpdateAvailabilityRequest) (*UpdateAvailabilityResponse, error) {
	if req == nil {
		req = &UpdateAvailabilityRequest{}
	}
	out := &UpdateAvailabilityResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "PUT",
		Path:   "/public/v{version}/appointment/availabilities",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
