// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// AddClassScheduleRequest holds the parameters for AddClassSchedule.
type AddClassScheduleRequest struct {
	AllowDateForwardEnrollment *bool               `json:"AllowDateForwardEnrollment,omitempty"`
	AllowOpenEnrollment        *bool               `json:"AllowOpenEnrollment,omitempty"`
	BookingStatus              *string             `json:"BookingStatus,omitempty"`
	ClassDescriptionId         *int                `json:"ClassDescriptionId,omitempty"`
	DayFriday                  *bool               `json:"DayFriday,omitempty"`
	DayMonday                  *bool               `json:"DayMonday,omitempty"`
	DaySaturday                *bool               `json:"DaySaturday,omitempty"`
	DaySunday                  *bool               `json:"DaySunday,omitempty"`
	DayThursday                *bool               `json:"DayThursday,omitempty"`
	DayTuesday                 *bool               `json:"DayTuesday,omitempty"`
	DayWednesday               *bool               `json:"DayWednesday,omitempty"`
	EndDate                    *connector.DateTime `json:"EndDate,omitempty"`
	EndTime                    *connector.DateTime `json:"EndTime,omitempty"`
	LocationId                 *int                `json:"LocationId,omitempty"`
	MaxCapacity                *int                `json:"MaxCapacity,omitempty"`
	PricingOptionsProductIds   []int               `json:"PricingOptionsProductIds,omitempty"`
	ResourceId                 *int                `json:"ResourceId,omitempty"`
	ShowToPublic               *bool               `json:"ShowToPublic,omitempty"`
	StaffId                    *int64              `json:"StaffId,omitempty"`
	StaffPayRate               *int                `json:"StaffPayRate,omitempty"`
	StartDate                  *connector.DateTime `json:"StartDate,omitempty"`
	StartTime                  *connector.DateTime `json:"StartTime,omitempty"`
	WaitlistCapacity           *int                `json:"WaitlistCapacity,omitempty"`
	WebCapacity                *int                `json:"WebCapacity,omitempty"`
}

// AddClassScheduleResponse is the response type of AddClassSchedule.
type AddClassScheduleResponse = WrittenClassSchedulesInfo

// AddClassSchedule calls POST /public/v{version}/class/addclassschedule.
func (c *Client) AddClassSchedule(ctx context.Context, req *AddClassScheduleRequest) (*AddClassScheduleResponse, error) {
	if req == nil {
		req = &AddClassScheduleRequest{}
	}
	out := &AddClassScheduleResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/addclassschedule",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddClientToClassRequest holds the parameters for AddClientToClass.
type AddClientToClassRequest struct {
	AutoAssignSpot                          *bool   `json:"AutoAssignSpot,omitempty"`
	ClassId                                 *int    `json:"ClassId,omitempty"`
	ClientId                                *string `json:"ClientId,omitempty"`
	ClientServiceId                         *int    `json:"ClientServiceId,omitempty"`
	CrossRegionalBooking                    *bool   `json:"CrossRegionalBooking,omitempty"`
	CrossRegionalBookingClientServiceSiteId *int    `json:"CrossRegionalBookingClientServiceSiteId,omitempty"`
	RequirePayment                          *bool   `json:"RequirePayment,omitempty"`
	SendEmail                               *bool   `json:"SendEmail,omitempty"`
	Test                                    *bool   `json:"Test,omitempty"`
	UniqueId                                *int64  `json:"UniqueId,omitempty"`
	Waitlist                                *bool   `json:"Waitlist,omitempty"`
	WaitlistEntryId                         *int    `json:"WaitlistEntryId,omitempty"`
}

// AddClientToClass calls POST /public/v{version}/class/addclienttoclass.
func (c *Client) AddClientToClass(ctx context.Context, req *AddClientToClassRequest) (*AddClientToClassResponse, error) {
	if req == nil {
		req = &AddClientToClassRequest{}
	}
	out := &AddClientToClassResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/addclienttoclass",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CancelSingleClassRequest holds the parameters for CancelSingleClass.
type CancelSingleClassRequest struct {
	ClassID         *int64 `json:"ClassID,omitempty"`
	HideCancel      *bool  `json:"HideCancel,omitempty"`
	SendClientEmail *bool  `json:"SendClientEmail,omitempty"`
	SendStaffEmail  *bool  `json:"SendStaffEmail,omitempty"`
}

// CancelSingleClass calls POST /public/v{version}/class/cancelsingleclass.
func (c *Client) CancelSingleClass(ctx context.Context, req *CancelSingleClassRequest) (*CancelSingleClassResponse, error) {
	if req == nil {
		req = &CancelSingleClassRequest{}
	}
	out := &CancelSingleClassResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/cancelsingleclass",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassDescriptionsRequest holds the parameters for GetClassDescriptions.
type GetClassDescriptionsRequest struct {
	ClassDescriptionId *int                `json:"-" query:"request.classDescriptionId"`
	EndClassDateTime   *connector.DateTime `json:"-" query:"request.endClassDateTime"`
	IncludeInactive    *bool               `json:"-" query:"request.includeInactive"`
	Limit              *int                `json:"-" query:"request.limit"`
	LocationId         *int                `json:"-" query:"request.locationId"`
	Offset             *int                `json:"-" query:"request.offset"`
	ProgramIds         []int               `json:"-" query:"request.programIds"`
	StaffId            *int64              `json:"-" query:"request.staffId"`
	StartClassDateTime *connector.DateTime `json:"-" query:"request.startClassDateTime"`
}

// GetClassDescriptions calls GET /public/v{version}/class/classdescriptions.
func (c *Client) GetClassDescriptions(ctx context.Context, req *GetClassDescriptionsRequest) (*GetClassDescriptionsResponse, error) {
	if req == nil {
		req = &GetClassDescriptionsRequest{}
	}
	out := &GetClassDescriptionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/classdescriptions",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassSchedulesRequest holds the parameters for GetClassSchedules.
type GetClassSchedulesRequest struct {
	ClassScheduleIds []int               `json:"-" query:"request.classScheduleIds"`
	EndDate          *connector.DateTime `json:"-" query:"request.endDate"`
	Limit            *int                `json:"-" query:"request.limit"`
	LocationIds      []int               `json:"-" query:"request.locationIds"`
	Offset           *int                `json:"-" query:"request.offset"`
	ProgramIds       []int               `json:"-" query:"request.programIds"`
	SessionTypeIds   []int               `json:"-" query:"request.sessionTypeIds"`
	StaffIds         []int64             `json:"-" query:"request.staffIds"`
	StartDate        *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetClassSchedules calls GET /public/v{version}/class/classschedules.
func (c *Client) GetClassSchedules(ctx context.Context, req *GetClassSchedulesRequest) (*GetClassSchedulesResponse, error) {
	if req == nil {
		req = &GetClassSchedulesRequest{}
	}
	out := &GetClassSchedulesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/classschedules",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassVisitsRequest holds the parameters for GetClassVisits.
type GetClassVisitsRequest struct {
	LastModifiedDate         *connector.DateTime `json:"-" query:"request.lastModifiedDate"`
	UseSiteSettingsStaffName *bool               `json:"-" query:"request.useSiteSettingsStaffName"`
	ClassID                  *int64              `json:"-" query:"request.classID"`
}

// GetClassVisits calls GET /public/v{version}/class/classvisits.
func (c *Client) GetClassVisits(ctx context.Context, req *GetClassVisitsRequest) (*GetClassVisitsResponse, error) {
	if req == nil {
		req = &GetClassVisitsRequest{}
	}
	out := &GetClassVisitsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/classvisits",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassesRequest holds the parameters for GetClasses.
type GetClassesRequest struct {
	ClassDescriptionIds []int               `json:"-" query:"request.classDescriptionIds"`
	ClassIds            []int               `json:"-" query:"request.classIds"`
	ClassScheduleIds    []int               `json:"-" query:"request.classScheduleIds"`
	ClientId            *string             `json:"-" query:"request.clientId"`
	EndDateTime         *connector.DateTime `json:"-" query:"request.endDateTime"`
	HideCanceledClasses *bool               `json:"-" query:"request.hideCanceledClasses"`
	LastModifiedDate    *connector.DateTime `json:"-" query:"request.lastModifiedDate"`
	Limit               *int                `json:"-" query:"request.limit"`
	LocationIds         []int               `json:"-" query:"request.locationIds"`
	Offset              *int                `json:"-" query:"request.offset"`
	ProgramIds          []int               `json:"-" query:"request.programIds"`
	SchedulingWindow    *bool               `json:"-" query:"request.schedulingWindow"`
	SemesterIds         []int               `json:"-" query:"request.semesterIds"`
	SessionTypeIds      []int               `json:"-" query:"request.sessionTypeIds"`
	StaffIds            []int64             `json:"-" query:"request.staffIds"`
	StartDateTime       *connector.DateTime `json:"-" query:"request.startDateTime"`
	UniqueClientId      *int64              `json:"-" query:"request.uniqueClientId"`
}

// GetClasses calls GET /public/v{version}/class/classes.
func (c *Client) GetClasses(ctx context.Context, req *GetClassesRequest) (*GetClassesResponse, error) {
	if req == nil {
		req = &GetClassesRequest{}
	}
	out := &GetClassesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/classes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCoursesRequest holds the parameters for GetCourses.
type GetCoursesRequest struct {
	GetCoursesRequestCourseIDs   []int64             `json:"-" query:"getCoursesRequest.courseIDs"`
	GetCoursesRequestEndDate     *connector.DateTime `json:"-" query:"getCoursesRequest.endDate"`
	GetCoursesRequestLimit       *int                `json:"-" query:"getCoursesRequest.limit"`
	GetCoursesRequestLocationIDs []int               `json:"-" query:"getCoursesRequest.locationIDs"`
	GetCoursesRequestOffset      *int                `json:"-" query:"getCoursesRequest.offset"`
	GetCoursesRequestProgramIDs  []int               `json:"-" query:"getCoursesRequest.programIDs"`
	GetCoursesRequestSemesterIDs []int               `json:"-" query:"getCoursesRequest.semesterIDs"`
	GetCoursesRequestStaffIDs    []int64             `json:"-" query:"getCoursesRequest.staffIDs"`
	GetCoursesRequestStartDate   *connector.DateTime `json:"-" query:"getCoursesRequest.startDate"`
}

// GetCoursesResponse is the response type of GetCourses.
type GetCoursesResponse = GetCoursesReponse

// GetCourses calls GET /public/v{version}/class/courses.
func (c *Client) GetCourses(ctx context.Context, req *GetCoursesRequest) (*GetCoursesResponse, error) {
	if req == nil {
		req = &GetCoursesRequest{}
	}
	out := &GetCoursesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/courses",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSemestersRequest holds the parameters for GetSemesters.
type GetSemestersRequest struct {
	Active      *bool               `json:"-" query:"request.active"`
	EndDate     *connector.DateTime `json:"-" query:"request.endDate"`
	Limit       *int                `json:"-" query:"request.limit"`
	Offset      *int                `json:"-" query:"request.offset"`
	SemesterIDs []int               `json:"-" query:"request.semesterIDs"`
	StartDate   *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetSemesters calls GET /public/v{version}/class/semesters.
func (c *Client) GetSemesters(ctx context.Context, req *GetSemestersRequest) (*GetSemestersResponse, error) {
	if req == nil {
		req = &GetSemestersRequest{}
	}
	out := &GetSemestersResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/semesters",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetWaitlistEntriesRequest holds the parameters for GetWaitlistEntries.
type GetWaitlistEntriesRequest struct {
	ClassIds         []int    `json:"-" query:"request.classIds"`
	ClassScheduleIds []int    `json:"-" query:"request.classScheduleIds"`
	ClientIds        []string `json:"-" query:"request.clientIds"`
	HidePastEntries  *bool    `json:"-" query:"request.hidePastEntries"`
	Limit            *int     `json:"-" query:"request.limit"`
	Offset           *int     `json:"-" query:"request.offset"`
	WaitlistEntryIds []int    `json:"-" query:"request.waitlistEntryIds"`
}

// GetWaitlistEntries calls GET /public/v{version}/class/waitlistentries.
func (c *Client) GetWaitlistEntries(ctx context.Context, req *GetWaitlistEntriesRequest) (*GetWaitlistEntriesResponse, error) {
	if req == nil {
		req = &GetWaitlistEntriesRequest{}
	}
	out := &GetWaitlistEntriesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/class/waitlistentries",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveClientFromClassRequest holds the parameters for RemoveClientFromClass.
type RemoveClientFromClassRequest struct {
	ClassId        *int    `json:"ClassId,omitempty"`
	ClientId       *string `json:"ClientId,omitempty"`
	LateCancel     *bool   `json:"LateCancel,omitempty"`
	SendEmail      *bool   `json:"SendEmail,omitempty"`
	Test           *bool   `json:"Test,omitempty"`
	UniqueClientId *int64  `json:"UniqueClientId,omitempty"`
	VisitId        *int    `json:"VisitId,omitempty"`
}

// RemoveClientFromClass calls POST /public/v{version}/class/removeclientfromclass.
func (c *Client) RemoveClientFromClass(ctx context.Context, req *RemoveClientFromClassRequest) (*RemoveClientFromClassResponse, error) {
	if req == nil {
		req = &RemoveClientFromClassRequest{}
	}
	out := &RemoveClientFromClassResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/removeclientfromclass",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveClientsFromClassesRequest holds the parameters for RemoveClientsFromClasses.
type RemoveClientsFromClassesRequest struct {
	Details    []ClassClientDetail `json:"Details,omitempty"`
	LateCancel *bool               `json:"LateCancel,omitempty"`
	Limit      *int                `json:"Limit,omitempty"`
	Offset     *int                `json:"Offset,omitempty"`
	SendEmail  *bool               `json:"SendEmail,omitempty"`
	Test       *bool               `json:"Test,omitempty"`
}

// RemoveClientsFromClasses calls POST /public/v{version}/class/removeclientsfromclasses.
func (c *Client) RemoveClientsFromClasses(ctx context.Context, req *RemoveClientsFromClassesRequest) (*RemoveClientsFromClassesResponse, error) {
	if req == nil {
		req = &RemoveClientsFromClassesRequest{}
	}
	out := &RemoveClientsFromClassesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/removeclientsfromclasses",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveFromWaitlistRequest holds the parameters for RemoveFromWaitlist.
type RemoveFromWaitlistRequest struct {
	WaitlistEntryIds []int `json:"-" query:"request.waitlistEntryIds"`
}

// RemoveFromWaitlist calls POST /public/v{version}/class/removefromwaitlist.
func (c *Client) RemoveFromWaitlist(ctx context.Context, req *RemoveFromWaitlistRequest) (*RemoveFromWaitlistResponse, error) {
	if req == nil {
		req = &RemoveFromWaitlistRequest{}
	}
	out := &RemoveFromWaitlistResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/removefromwaitlist",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubstituteClassTeacherRequest holds the parameters for SubstituteClassTeacher.
type SubstituteClassTeacherRequest struct {
	ClassId                    *int   `json:"ClassId,omitempty"`
	OverrideConflicts          *bool  `json:"OverrideConflicts,omitempty"`
	SendClientEmail            *bool  `json:"SendClientEmail,omitempty"`
	SendOriginalTeacherEmail   *bool  `json:"SendOriginalTeacherEmail,omitempty"`
	SendSubstituteTeacherEmail *bool  `json:"SendSubstituteTeacherEmail,omitempty"`
	StaffId                    *int64 `json:"StaffId,omitempty"`
}

// SubstituteClassTeacher calls POST /public/v{version}/class/substituteclassteacher.
func (c *Client) SubstituteClassTeacher(ctx context.Context, req *SubstituteClassTeacherRequest) (*SubstituteClassTeacherResponse, error) {
	if req == nil {
		req = &SubstituteClassTeacherRequest{}
	}
	out := &SubstituteClassTeacherResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/substituteclassteacher",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClassRequest holds the parameters for UpdateClass.
type UpdateClassRequest struct {
	ClassId   *int    `json:"ClassId,omitempty"`
	ThemeName *string `json:"ThemeName,omitempty"`
}

// UpdateClassResponse is the (empty) response type of UpdateClass.
type UpdateClassResponse struct{}

// UpdateClass calls POST /public/v{version}/class/updateclass.
func (c *Client) UpdateClass(ctx context.Context, req *UpdateClassRequest) (*UpdateClassResponse, error) {
	if req == nil {
		req = &UpdateClassRequest{}
	}
	out := &UpdateClassResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/updateclass",
		Req:    req,
		Body:   req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClassScheduleRequest holds the parameters for UpdateClassSchedule.
type UpdateClassScheduleRequest struct {
	AllowDateForwardEnrollment *bool               `json:"AllowDateForwardEnrollment,omitempty"`
	AllowOpenEnrollment        *bool               `json:"AllowOpenEnrollment,omitempty"`
	BookingStatus              *string             `json:"BookingStatus,omitempty"`
	ClassDescriptionId         *int                `json:"ClassDescriptionId,omitempty"`
	ClassId                    *int                `json:"ClassId,omitempty"`
	DayFriday                  *bool               `json:"DayFriday,omitempty"`
	DayMonday                  *bool               `json:"DayMonday,omitempty"`
	DaySaturday                *bool               `json:"DaySaturday,omitempty"`
	DaySunday                  *bool               `json:"DaySunday,omitempty"`
	DayThursday                *bool               `json:"DayThursday,omitempty"`
	DayTuesday                 *bool               `json:"DayTuesday,omitempty"`
	DayWednesday               *bool               `json:"DayWednesday,omitempty"`
	EndDate                    *connector.DateTime `json:"EndDate,omitempty"`
	EndTime                    *connector.DateTime `json:"EndTime,omitempty"`
	LocationId                 *int                `json:"LocationId,omitempty"`
	MaxCapacity                *int                `json:"MaxCapacity,omitempty"`
	ResourceId                 *int                `json:"ResourceId,omitempty"`
	RetainScheduleChanges      *bool               `json:"RetainScheduleChanges,omitempty"`
	StaffId                    *int64              `json:"StaffId,omitempty"`
	StaffPayRate               *int                `json:"StaffPayRate,omitempty"`
	StartDate                  *connector.DateTime `json:"StartDate,omitempty"`
	StartTime                  *connector.DateTime `json:"StartTime,omitempty"`
	WaitlistCapacity           *int                `json:"WaitlistCapacity,omitempty"`
	WebCapacity                *int                `json:"WebCapacity,omitempty"`
}

// UpdateClassScheduleResponse is the response type of UpdateClassSchedule.
type UpdateClassScheduleResponse = WrittenClassSchedulesInfo

// UpdateClassSchedule calls POST /public/v{version}/class/updateclassschedule.
func (c *Client) UpdateClassSchedule(ctx context.Context, req *UpdateClassScheduleRequest) (*UpdateClassScheduleResponse, error) {
	if req == nil {
		req = &UpdateClassScheduleRequest{}
	}
	out := &UpdateClassScheduleResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/class/updateclassschedule",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClassScheduleNotesRequest holds the parameters for UpdateClassScheduleNotes.
type UpdateClassScheduleNotesRequest struct {
	ClassScheduleId int     `json:"-" path:"classScheduleId"`
	Notes           *string `json:"Notes,omitempty"`
}

// UpdateClassScheduleNotesResponse is the (empty) response type of UpdateClassScheduleNotes.
type UpdateClassScheduleNotesResponse struct{}

// UpdateClassScheduleNotes calls PATCH /public/v{version}/class/updateclassschedulenotes/{classScheduleId}.
func (c *Client) UpdateClassScheduleNotes(ctx context.Context, req *UpdateClassScheduleNotesRequest) (*UpdateClassScheduleNotesResponse, error) {
	if req == nil {
		req = &UpdateClassScheduleNotesRequest{}
	}
	out := &UpdateClassScheduleNotesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "PATCH",
		Path:   "/public/v{version}/class/updateclassschedulenotes/{classScheduleId}",
		Req:    req,
		Body:   req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
