// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// AddArrivalRequest holds the parameters for AddArrival.
type AddArrivalRequest struct {
	ArrivalTypeId *int    `json:"ArrivalTypeId,omitempty"`
	ClientId      *string `json:"ClientId,omitempty"`
	LeadChannelId *int    `json:"LeadChannelId,omitempty"`
	LocationId    *int    `json:"LocationId,omitempty"`
	Test          *bool   `json:"Test,omitempty"`
}

// AddArrival calls POST /public/v{version}/client/addarrival.
func (c *Client) AddArrival(ctx context.Context, req *AddArrivalRequest) (*AddArrivalResponse, error) {
	if req == nil {
		req = &AddArrivalRequest{}
	}
	out := &AddArrivalResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/addarrival",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddClientRequest holds the parameters for AddClient.
type AddClientRequest struct {
	AccountBalance                   *float64                 `json:"AccountBalance,omitempty"`
	Action                           *string                  `json:"Action,omitempty"`
	Active                           *bool                    `json:"Active,omitempty"`
	AddressLine1                     *string                  `json:"AddressLine1,omitempty"`
	AddressLine2                     *string                  `json:"AddressLine2,omitempty"`
	ApptGenderPrefMale               *bool                    `json:"ApptGenderPrefMale,omitempty"`
	BirthDate                        *connector.DateTime      `json:"BirthDate,omitempty"`
	City                             *string                  `json:"City,omitempty"`
	ClientCreditCard                 *ClientCreditCard        `json:"ClientCreditCard,omitempty"`
	ClientIndexes                    []AssignedClientIndex    `json:"ClientIndexes,omitempty"`
	ClientRelationships              []ClientRelationship     `json:"ClientRelationships,omitempty"`
	Country                          *string                  `json:"Country,omitempty"`
	CreationDate                     *connector.DateTime      `json:"CreationDate,omitempty"`
	CustomClientFields               []CustomClientFieldValue `json:"CustomClientFields,omitempty"`
	Email                            *string                  `json:"Email,omitempty"`
	EmergencyContactInfoEmail        *string                  `json:"EmergencyContactInfoEmail,omitempty"`
	EmergencyContactInfoName         *string                  `json:"EmergencyContactInfoName,omitempty"`
	EmergencyContactInfoPhone        *string                  `json:"EmergencyContactInfoPhone,omitempty"`
	EmergencyContactInfoRelationship *string                  `json:"EmergencyContactInfoRelationship,omitempty"`
	FirstAppointmentDate             *connector.DateTime      `json:"FirstAppointmentDate,omitempty"`
	FirstName                        *string                  `json:"FirstName,omitempty"`
	Gender                           *string                  `json:"Gender,omitempty"`
	HomeLocation                     *Location                `json:"HomeLocation,omitempty"`
	HomePhone                        *string                  `json:"HomePhone,omitempty"`
	IsCompany                        *bool                    `json:"IsCompany,omitempty"`
	IsProspect                       *bool                    `json:"IsProspect,omitempty"`
	LastFormulaNotes                 *string                  `json:"LastFormulaNotes,omitempty"`
	LastModifiedDateTime             *connector.DateTime      `json:"LastModifiedDateTime,omitempty"`
	LastName                         *string                  `json:"LastName,omitempty"`
	LeadChannelId                    *int                     `json:"LeadChannelId,omitempty"`
	Liability                        *Liability               `json:"Liability,omitempty"`
	LiabilityRelease                 *bool                    `json:"LiabilityRelease,omitempty"`
	LockerNumber                     *string                  `json:"LockerNumber,omitempty"`
	MembershipIcon                   *int                     `json:"MembershipIcon,omitempty"`
	MiddleName                       *string                  `json:"MiddleName,omitempty"`
	MobilePhone                      *string                  `json:"MobilePhone,omitempty"`
	MobileProvider                   *int                     `json:"MobileProvider,omitempty"`
	NewId                            *string                  `json:"NewId,omitempty"`
	Notes                            *string                  `json:"Notes,omitempty"`
	PhotoUrl                         *string                  `json:"PhotoUrl,omitempty"`
	PostalCode                       *string                  `json:"PostalCode,omitempty"`
	ProspectStage                    *ProspectStage           `json:"ProspectStage,omitempty"`
	ReactivateInactiveClient         *bool                    `json:"ReactivateInactiveClient,omitempty"`
	RedAlert                         *string                  `json:"RedAlert,omitempty"`
	ReferredBy                       *string                  `json:"ReferredBy,omitempty"`
	SalesReps                        []SalesRep               `json:"SalesReps,omitempty"`
	SendAccountEmails                *bool                    `json:"SendAccountEmails,omitempty"`
	SendAccountTexts                 *bool                    `json:"SendAccountTexts,omitempty"`
	SendPromotionalEmails            *bool                    `json:"SendPromotionalEmails,omitempty"`
	SendPromotionalTexts             *bool                    `json:"SendPromotionalTexts,omitempty"`
	SendScheduleEmails               *bool                    `json:"SendScheduleEmails,omitempty"`
	SendScheduleTexts                *bool                    `json:"SendScheduleTexts,omitempty"`
	SiteId                           *int                     `json:"SiteId,omitempty"`
	State                            *string                  `json:"State,omitempty"`
	Status                           *string                  `json:"Status,omitempty"`
	Test                             *bool                    `json:"Test,omitempty"`
	UniqueId                         *int64                   `json:"UniqueId,omitempty"`
	WorkExtension                    *string                  `json:"WorkExtension,omitempty"`
	WorkPhone                        *string                  `json:"WorkPhone,omitempty"`
	YellowAlert                      *string                  `json:"YellowAlert,omitempty"`
}

// AddClient calls POST /public/v{version}/client/addclient.
func (c *Client) AddClient(ctx context.Context, req *AddClientRequest) (*AddClientResponse, error) {
	if req == nil {
		req = &AddClientRequest{}
	}
	out := &AddClientResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/addclient",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddClientDirectDebitInfoRequest holds the parameters for AddClientDirectDebitInfo.
type AddClientDirectDebitInfoRequest struct {
	AccountNumber *string `json:"AccountNumber,omitempty"`
	AccountType   *string `json:"AccountType,omitempty"`
	ClientId      *string `json:"ClientId,omitempty"`
	NameOnAccount *string `json:"NameOnAccount,omitempty"`
	RoutingNumber *string `json:"RoutingNumber,omitempty"`
	Test          *bool   `json:"Test,omitempty"`
}

// AddClientDirectDebitInfo calls POST /public/v{version}/client/addclientdirectdebitinfo.
func (c *Client) AddClientDirectDebitInfo(ctx context.Context, req *AddClientDirectDebitInfoRequest) (*AddClientDirectDebitInfoResponse, error) {
	if req == nil {
		req = &AddClientDirectDebitInfoRequest{}
	}
	out := &AddClientDirectDebitInfoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/addclientdirectdebitinfo",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddContactLogRequest holds the parameters for AddContactLog.
type AddContactLogRequest struct {
	AssignedToStaffId *int64              `json:"AssignedToStaffId,omitempty"`
	ClientId          *string             `json:"ClientId,omitempty"`
	Comments          []string            `json:"Comments,omitempty"`
	ContactMethod     *string             `json:"ContactMethod,omitempty"`
	ContactName       *string             `json:"ContactName,omitempty"`
	FollowupByDate    *connector.DateTime `json:"FollowupByDate,omitempty"`
	IsComplete        *bool               `json:"IsComplete,omitempty"`
	Test              *bool               `json:"Test,omitempty"`
	Text              *string             `json:"Text,omitempty"`
	Types             []AddContactLogType `json:"Types,omitempty"`
}

// AddContactLogResponse is the response type of AddContactLog.
type AddContactLogResponse = ContactLog

// AddContactLog calls POST /public/v{version}/client/addcontactlog.
func (c *Client) AddContactLog(ctx context.Context, req *AddContactLogRequest) (*AddContactLogResponse, error) {
	if req == nil {
		req = &AddContactLogRequest{}
	}
	out := &AddContactLogResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/addcontactlog",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddFormulaNoteRequest holds the parameters for AddFormulaNote.
type AddFormulaNoteRequest struct {
	AppointmentId *int64  `json:"AppointmentId,omitempty"`
	ClientId      *string `json:"ClientId,omitempty"`
	Note          *string `json:"Note,omitempty"`
}

// AddFormulaNoteResponse is the response type of AddFormulaNote.
type AddFormulaNoteResponse = FormulaNoteResponse

// AddFormulaNote calls POST /public/v{version}/client/addclientformulanote.
func (c *Client) AddFormulaNote(ctx context.Context, req *AddFormulaNoteRequest) (*AddFormulaNoteResponse, error) {
	if req == nil {
		req = &AddFormulaNoteRequest{}
	}
	out := &AddFormulaNoteResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/addclientformulanote",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteClientFormulaNoteRequest holds the parameters for DeleteClientFormulaNote.
type DeleteClientFormulaNoteRequest struct {
	Limit         *int    `json:"-" query:"request.limit"`
	Offset        *int    `json:"-" query:"request.offset"`
	ClientId      *string `json:"-" query:"request.clientId"`
	FormulaNoteId *int64  `json:"-" query:"request.formulaNoteId"`
}

// DeleteClientFormulaNoteResponse is the (empty) response type of DeleteClientFormulaNote.
type DeleteClientFormulaNoteResponse struct{}

// DeleteClientFormulaNote calls DELETE /public/v{version}/client/clientformulanote.
func (c *Client) DeleteClientFormulaNote(ctx context.Context, req *DeleteClientFormulaNoteRequest) (*DeleteClientFormulaNoteResponse, error) {
	if req == nil {
		req = &DeleteClientFormulaNoteRequest{}
	}
	out := &DeleteClientFormulaNoteResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/client/clientformulanote",
		Req:    req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteContactLogRequest holds the parameters for DeleteContactLog.
type DeleteContactLogRequest struct {
	Test         *bool   `json:"-" query:"request.test"`
	ClientId     *string `json:"-" query:"request.clientId"`
	ContactLogId *int64  `json:"-" query:"request.contactLogId"`
}

// DeleteContactLogResponse is the response type of DeleteContactLog.
type DeleteContactLogResponse = map[string]any

// DeleteContactLog calls DELETE /public/v{version}/client/deletecontactlog.
func (c *Client) DeleteContactLog(ctx context.Context, req *DeleteContactLogRequest) (*DeleteContactLogResponse, error) {
	if req == nil {
		req = &DeleteContactLogRequest{}
	}
	out := &DeleteContactLogResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/client/deletecontactlog",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteDirectDebitInfoRequest holds the parameters for DeleteDirectDebitInfo.
type DeleteDirectDebitInfoRequest struct {
	ClientId *string `json:"-" query:"clientId"`
}

// DeleteDirectDebitInfoResponse is the response type of DeleteDirectDebitInfo.
type DeleteDirectDebitInfoResponse = map[string]any

// DeleteDirectDebitInfo calls DELETE /public/v{version}/client/clientdirectdebitinfo.
func (c *Client) DeleteDirectDebitInfo(ctx context.Context, req *DeleteDirectDebitInfoRequest) (*DeleteDirectDebitInfoResponse, error) {
	if req == nil {
		req = &DeleteDirectDebitInfoRequest{}
	}
	out := &DeleteDirectDebitInfoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/client/clientdirectdebitinfo",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetActiveClientMembershipsRequest holds the parameters for GetActiveClientMemberships.
type GetActiveClientMembershipsRequest struct {
	ClientAssociatedSitesOffset *int    `json:"-" query:"request.clientAssociatedSitesOffset"`
	CrossRegionalLookup         *bool   `json:"-" query:"request.crossRegionalLookup"`
	Limit                       *int    `json:"-" query:"request.limit"`
	LocationId                  *int    `json:"-" query:"request.locationId"`
	Offset                      *int    `json:"-" query:"request.offset"`
	UniqueClientId              *int64  `json:"-" query:"request.uniqueClientId"`
	ClientId                    *string `json:"-" query:"request.clientId"`
}

// GetActiveClientMemberships calls GET /public/v{version}/client/activeclientmemberships.
func (c *Client) GetActiveClientMemberships(ctx context.Context, req *GetActiveClientMembershipsRequest) (*GetActiveClientMembershipsResponse, error) {
	if req == nil {
		req = &GetActiveClientMembershipsRequest{}
	}
	out := &GetActiveClientMembershipsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/activeclientmemberships",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetActiveClientsMembershipsRequest holds the parameters for GetActiveClientsMemberships.
type GetActiveClientsMembershipsRequest struct {
	ClientAssociatedSitesOffset *int     `json:"-" query:"request.clientAssociatedSitesOffset"`
	CrossRegionalLookup         *bool    `json:"-" query:"request.crossRegionalLookup"`
	Limit                       *int     `json:"-" query:"request.limit"`
	LocationId                  *int     `json:"-" query:"request.locationId"`
	Offset                      *int     `json:"-" query:"request.offset"`
	ClientIds                   []string `json:"-" query:"request.clientIds"`
}

// GetActiveClientsMemberships calls GET /public/v{version}/client/activeclientsmemberships.
func (c *Client) GetActiveClientsMemberships(ctx context.Context, req *GetActiveClientsMembershipsRequest) (*GetActiveClientsMembershipsResponse, error) {
	if req == nil {
		req = &GetActiveClientsMembershipsRequest{}
	}
	out := &GetActiveClientsMembershipsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/activeclientsmemberships",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientAccountBalancesRequest holds the parameters for GetClientAccountBalances.
type GetClientAccountBalancesRequest struct {
	BalanceDate *connector.DateTime `json:"-" query:"request.balanceDate"`
	ClassId     *int                `json:"-" query:"request.classId"`
	Limit       *int                `json:"-" query:"request.limit"`
	Offset      *int                `json:"-" query:"request.offset"`
	ClientIds   []string            `json:"-" query:"request.clientIds"`
}

// GetClientAccountBalances calls GET /public/v{version}/client/clientaccountbalances.
func (c *Client) GetClientAccountBalances(ctx context.Context, req *GetClientAccountBalancesRequest) (*GetClientAccountBalancesResponse, error) {
	if req == nil {
		req = &GetClientAccountBalancesRequest{}
	}
	out := &GetClientAccountBalancesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientaccountbalances",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientCompleteInfoRequest holds the parameters for GetClientCompleteInfo.
type GetClientCompleteInfoRequest struct {
	ClientAssociatedSitesOffset *int                `json:"-" query:"request.clientAssociatedSitesOffset"`
	CrossRegionalLookup         *bool               `json:"-" query:"request.crossRegionalLookup"`
	EndDate                     *connector.DateTime `json:"-" query:"request.endDate"`
	ExcludeInactiveSites        *bool               `json:"-" query:"request.excludeInactiveSites"`
	RequiredClientData          []string            `json:"-" query:"request.requiredClientData"`
	ShowActiveOnly              *bool               `json:"-" query:"request.showActiveOnly"`
	StartDate                   *connector.DateTime `json:"-" query:"request.startDate"`
	UniqueClientId              *int64              `json:"-" query:"request.uniqueClientId"`
	UseActivateDate             *bool               `json:"-" query:"request.useActivateDate"`
	ClientId                    *string             `json:"-" query:"request.clientId"`
	ConsumerIdentityToken       *string             `json:"-" header:"consumer-identity-token"`
}

// GetClientCompleteInfo calls GET /public/v{version}/client/clientcompleteinfo.
func (c *Client) GetClientCompleteInfo(ctx context.Context, req *GetClientCompleteInfoRequest) (*GetClientCompleteInfoResponse, error) {
	if req == nil {
		req = &GetClientCompleteInfoRequest{}
	}
	out := &GetClientCompleteInfoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientcompleteinfo",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientContractsRequest holds the parameters for GetClientContracts.
type GetClientContractsRequest struct {
	ClientAssociatedSitesOffset *int    `json:"-" query:"request.clientAssociatedSitesOffset"`
	CrossRegionalLookup         *bool   `json:"-" query:"request.crossRegionalLookup"`
	Limit                       *int    `json:"-" query:"request.limit"`
	Offset                      *int    `json:"-" query:"request.offset"`
	UniqueClientId              *int64  `json:"-" query:"request.uniqueClientId"`
	ClientId                    *string `json:"-" query:"request.clientId"`
}

// GetClientContracts calls GET /public/v{version}/client/clientcontracts.
func (c *Client) GetClientContracts(ctx context.Context, req *GetClientContractsRequest) (*GetClientContractsResponse, error) {
	if req == nil {
		req = &GetClientContractsRequest{}
	}
	out := &GetClientContractsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientcontracts",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientDuplicatesRequest holds the parameters for GetClientDuplicates.
type GetClientDuplicatesRequest struct {
	Email     *string `json:"-" query:"request.email"`
	FirstName *string `json:"-" query:"request.firstName"`
	LastName  *string `json:"-" query:"request.lastName"`
	Limit     *int    `json:"-" query:"request.limit"`
	Offset    *int    `json:"-" query:"request.offset"`
}

// GetClientDuplicates calls GET /public/v{version}/client/clientduplicates.
func (c *Client) GetClientDuplicates(ctx context.Context, req *GetClientDuplicatesRequest) (*GetClientDuplicatesResponse, error) {
	if req == nil {
		req = &GetClientDuplicatesRequest{}
	}
	out := &GetClientDuplicatesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientduplicates",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientFormulaNotesRequest holds the parameters for GetClientFormulaNotes.
type GetClientFormulaNotesRequest struct {
	AppointmentId *int64  `json:"-" query:"request.appointmentId"`
	ClientId      *string `json:"-" query:"request.clientId"`
	Limit         *int    `json:"-" query:"request.limit"`
	Offset        *int    `json:"-" query:"request.offset"`
}

// GetClientFormulaNotes calls GET /public/v{version}/client/clientformulanotes.
func (c *Client) GetClientFormulaNotes(ctx context.Context, req *GetClientFormulaNotesRequest) (*GetClientFormulaNotesResponse, error) {
	if req == nil {
		req = &GetClientFormulaNotesRequest{}
	}
	out := &GetClientFormulaNotesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientformulanotes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientIndexesRequest holds the parameters for GetClientIndexes.
type GetClientIndexesRequest struct {
	RequiredOnly *bool `json:"-" query:"request.requiredOnly"`
}

// GetClientIndexes calls GET /public/v{version}/client/clientindexes.
func (c *Client) GetClientIndexes(ctx context.Context, req *GetClientIndexesRequest) (*GetClientIndexesResponse, error) {
	if req == nil {
		req = &GetClientIndexesRequest{}
	}
	out := &GetClientIndexesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientindexes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientPurchasesRequest holds the parameters for GetClientPurchases.
type GetClientPurchasesRequest struct {
	EndDate        *connector.DateTime `json:"-" query:"request.endDate"`
	Limit          *int                `json:"-" query:"request.limit"`
	Offset         *int                `json:"-" query:"request.offset"`
	SaleId         *int                `json:"-" query:"request.saleId"`
	StartDate      *connector.DateTime `json:"-" query:"request.startDate"`
	UniqueClientId *int64              `json:"-" query:"request.uniqueClientId"`
	ClientId       *string             `json:"-" query:"request.clientId"`
}

// GetClientPurchases calls GET /public/v{version}/client/clientpurchases.
func (c *Client) GetClientPurchases(ctx context.Context, req *GetClientPurchasesRequest) (*GetClientPurchasesResponse, error) {
	if req == nil {
		req = &GetClientPurchasesRequest{}
	}
	out := &GetClientPurchasesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientpurchases",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientReferralTypesRequest holds the parameters for GetClientReferralTypes.
type GetClientReferralTypesRequest struct {
	IncludeInactive *bool `json:"-" query:"request.includeInactive"`
}

// GetClientReferralTypes calls GET /public/v{version}/client/clientreferraltypes.
func (c *Client) GetClientReferralTypes(ctx context.Context, req *GetClientReferralTypesRequest) (*GetClientReferralTypesResponse, error) {
	if req == nil {
		req = &GetClientReferralTypesRequest{}
	}
	out := &GetClientReferralTypesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientreferraltypes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientRewardsRequest holds the parameters for GetClientRewards.
type GetClientRewardsRequest struct {
	EndDate   *connector.DateTime `json:"-" query:"request.endDate"`
	Limit     *int                `json:"-" query:"request.limit"`
	Offset    *int                `json:"-" query:"request.offset"`
	StartDate *connector.DateTime `json:"-" query:"request.startDate"`
	ClientId  *string             `json:"-" query:"request.clientId"`
}

// GetClientRewards calls GET /public/v{version}/client/clientrewards.
func (c *Client) GetClientRewards(ctx context.Context, req *GetClientRewardsRequest) (*GetClientRewardsResponse, error) {
	if req == nil {
		req = &GetClientRewardsRequest{}
	}
	out := &GetClientRewardsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientrewards",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientScheduleRequest holds the parameters for GetClientSchedule.
type GetClientScheduleRequest struct {
	ClientAssociatedSitesOffset *int                `json:"-" query:"request.clientAssociatedSitesOffset"`
	ClientId                    *string             `json:"-" query:"request.clientId"`
	CrossRegionalLookup         *bool               `json:"-" query:"request.crossRegionalLookup"`
	EndDate                     *connector.DateTime `json:"-" query:"request.endDate"`
	IncludeWaitlistEntries      *bool               `json:"-" query:"request.includeWaitlistEntries"`
	Limit                       *int                `json:"-" query:"request.limit"`
	Offset                      *int                `json:"-" query:"request.offset"`
	StartDate                   *connector.DateTime `json:"-" query:"request.startDate"`
	UniqueClientId              *int64              `json:"-" query:"request.uniqueClientId"`
}

// GetClientSchedule calls GET /public/v{version}/client/clientschedule.
func (c *Client) GetClientSchedule(ctx context.Context, req *GetClientScheduleRequest) (*GetClientScheduleResponse, error) {
	if req == nil {
		req = &GetClientScheduleRequest{}
	}
	out := &GetClientScheduleResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientschedule",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientServicesRequest holds the parameters for GetClientServices.
type GetClientServicesRequest struct {
	ClassId                      *int                `json:"-" query:"request.classId"`
	ClassScheduleID              []int               `json:"-" query:"request.classScheduleID"`
	ClientAssociatedSitesOffset  *int                `json:"-" query:"request.clientAssociatedSitesOffset"`
	ClientId                     *string             `json:"-" query:"request.clientId"`
	ClientIds                    []string            `json:"-" query:"request.clientIds"`
	CrossRegionalLookup          *bool               `json:"-" query:"request.crossRegionalLookup"`
	EndDate                      *connector.DateTime `json:"-" query:"request.endDate"`
	ExcludeInactiveSites         *bool               `json:"-" query:"request.excludeInactiveSites"`
	IgnoreCrossRegionalSiteLimit *bool               `json:"-" query:"request.ignoreCrossRegionalSiteLimit"`
	Limit                        *int                `json:"-" query:"request.limit"`
	LocationIds                  []int               `json:"-" query:"request.locationIds"`
	Offset                       *int                `json:"-" query:"request.offset"`
	ProgramIds                   []int               `json:"-" query:"request.programIds"`
	SessionTypeId                *int                `json:"-" query:"request.sessionTypeId"`
	ShowActiveOnly               *bool               `json:"-" query:"request.showActiveOnly"`
	StartDate                    *connector.DateTime `json:"-" query:"request.startDate"`
	UniqueClientId               *int64              `json:"-" query:"request.uniqueClientId"`
	UniqueClientIds              []int64             `json:"-" query:"request.uniqueClientIds"`
	UseActivateDate              *bool               `json:"-" query:"request.useActivateDate"`
	VisitCount                   *int                `json:"-" query:"request.visitCount"`
}

// GetClientServices calls GET /public/v{version}/client/clientservices.
func (c *Client) GetClientServices(ctx context.Context, req *GetClientServicesRequest) (*GetClientServicesResponse, error) {
	if req == nil {
		req = &GetClientServicesRequest{}
	}
	out := &GetClientServicesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientservices",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientVisitsRequest holds the parameters for GetClientVisits.
type GetClientVisitsRequest struct {
	ClientAssociatedSitesOffset  *int                `json:"-" query:"request.clientAssociatedSitesOffset"`
	ClientId                     *string             `json:"-" query:"request.clientId"`
	CrossRegionalLookup          *bool               `json:"-" query:"request.crossRegionalLookup"`
	EndDate                      *connector.DateTime `json:"-" query:"request.endDate"`
	ExcludeTypeTakenDescriptions []string            `json:"-" query:"request.excludeTypeTakenDescriptions"`
	Limit                        *int                `json:"-" query:"request.limit"`
	Offset                       *int                `json:"-" query:"request.offset"`
	Order                        *string             `json:"-" query:"request.order"`
	StartDate                    *connector.DateTime `json:"-" query:"request.startDate"`
	UniqueClientId               *int64              `json:"-" query:"request.uniqueClientId"`
	UnpaidsOnly                  *bool               `json:"-" query:"request.unpaidsOnly"`
}

// GetClientVisits calls GET /public/v{version}/client/clientvisits.
func (c *Client) GetClientVisits(ctx context.Context, req *GetClientVisitsRequest) (*GetClientVisitsResponse, error) {
	if req == nil {
		req = &GetClientVisitsRequest{}
	}
	out := &GetClientVisitsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientvisits",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClientsRequest holds the parameters for GetClients.
type GetClientsRequest struct {
	ClientIDs        []string            `json:"-" query:"request.clientIDs"`
	IncludeInactive  *bool               `json:"-" query:"request.includeInactive"`
	IsProspect       *bool               `json:"-" query:"request.isProspect"`
	LastModifiedDate *connector.DateTime `json:"-" query:"request.lastModifiedDate"`
	Limit            *int                `json:"-" query:"request.limit"`
	Offset           *int                `json:"-" query:"request.offset"`
	SearchText       *string             `json:"-" query:"request.searchText"`
	UniqueIds        []int64             `json:"-" query:"request.uniqueIds"`
}

// GetClients calls GET /public/v{version}/client/clients.
func (c *Client) GetClients(ctx context.Context, req *GetClientsRequest) (*GetClientsResponse, error) {
	if req == nil {
		req = &GetClientsRequest{}
	}
	out := &GetClientsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clients",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetContactLogTypesRequest holds the parameters for GetContactLogTypes.
type GetContactLogTypesRequest struct {
	ContactLogTypeId *int `json:"-" query:"request.contactLogTypeId"`
	Limit            *int `json:"-" query:"request.limit"`
	Offset           *int `json:"-" query:"request.offset"`
}

// GetContactLogTypes calls GET /public/v{version}/client/contactlogtypes.
func (c *Client) GetContactLogTypes(ctx context.Context, req *GetContactLogTypesRequest) (*GetContactLogTypesResponse, error) {
	if req == nil {
		req = &GetContactLogTypesRequest{}
	}
	out := &GetContactLogTypesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/contactlogtypes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetContactLogsRequest holds the parameters for GetContactLogs.
type GetContactLogsRequest struct {
	EndDate             *connector.DateTime `json:"-" query:"request.endDate"`
	Limit               *int                `json:"-" query:"request.limit"`
	Offset              *int                `json:"-" query:"request.offset"`
	ShowSystemGenerated *bool               `json:"-" query:"request.showSystemGenerated"`
	StaffIds            []int64             `json:"-" query:"request.staffIds"`
	StartDate           *connector.DateTime `json:"-" query:"request.startDate"`
	SubtypeIds          []int               `json:"-" query:"request.subtypeIds"`
	TypeIds             []int               `json:"-" query:"request.typeIds"`
	ClientId            *string             `json:"-" query:"request.clientId"`
}

// GetContactLogs calls GET /public/v{version}/client/contactlogs.
func (c *Client) GetContactLogs(ctx context.Context, req *GetContactLogsRequest) (*GetContactLogsResponse, error) {
	if req == nil {
		req = &GetContactLogsRequest{}
	}
	out := &GetContactLogsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/contactlogs",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCrossRegionalClientAssociationsRequest holds the parameters for GetCrossRegionalClientAssociations.
type GetCrossRegionalClientAssociationsRequest struct {
	ClientId             *string `json:"-" query:"request.clientId"`
	Email                *string `json:"-" query:"request.email"`
	ExcludeInactiveSites *bool   `json:"-" query:"request.excludeInactiveSites"`
	FirstName            *string `json:"-" query:"request.firstName"`
	LastName             *string `json:"-" query:"request.lastName"`
	Limit                *int    `json:"-" query:"request.limit"`
	Offset               *int    `json:"-" query:"request.offset"`
	UniqueClientId       *int64  `json:"-" query:"request.uniqueClientId"`
	V2                   *bool   `json:"-" query:"request.v2"`
}

// GetCrossRegionalClientAssociations calls GET /public/v{version}/client/crossregionalclientassociations.
func (c *Client) GetCrossRegionalClientAssociations(ctx context.Context, req *GetCrossRegionalClientAssociationsRequest) (*GetCrossRegionalClientAssociationsResponse, error) {
	if req == nil {
		req = &GetCrossRegionalClientAssociationsRequest{}
	}
	out := &GetCrossRegionalClientAssociationsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/crossregionalclientassociations",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCustomClientFieldsRequest holds the parameters for GetCustomClientFields.
type GetCustomClientFieldsRequest struct {
	Limit  *int `json:"-" query:"request.limit"`
	Offset *int `json:"-" query:"request.offset"`
}

// GetCustomClientFields calls GET /public/v{version}/client/customclientfields.
func (c *Client) GetCustomClientFields(ctx context.Context, req *GetCustomClientFieldsRequest) (*GetCustomClientFieldsResponse, error) {
	if req == nil {
		req = &GetCustomClientFieldsRequest{}
	}
	out := &GetCustomClientFieldsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/customclientfields",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetDirectDebitInfoRequest holds the parameters for GetDirectDebitInfo.
type GetDirectDebitInfoRequest struct {
	ClientId *string `json:"-" query:"clientId"`
}

// GetDirectDebitInfoResponse is the response type of GetDirectDebitInfo.
type GetDirectDebitInfoResponse = DirectDebitInfo

// GetDirectDebitInfo calls GET /public/v{version}/client/clientdirectdebitinfo.
func (c *Client) GetDirectDebitInfo(ctx context.Context, req *GetDirectDebitInfoRequest) (*GetDirectDebitInfoResponse, error) {
	if req == nil {
		req = &GetDirectDebitInfoRequest{}
	}
	out := &GetDirectDebitInfoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/clientdirectdebitinfo",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRequiredClientFieldsRequest holds the parameters for GetRequiredClientFields.
type GetRequiredClientFieldsRequest struct {
}

// GetRequiredClientFields calls GET /public/v{version}/client/requiredclientfields.
func (c *Client) GetRequiredClientFields(ctx context.Context, req *GetRequiredClientFieldsRequest) (*GetRequiredClientFieldsResponse, error) {
	if req == nil {
		req = &GetRequiredClientFieldsRequest{}
	}
	out := &GetRequiredClientFieldsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/client/requiredclientfields",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergeClientRequest holds the parameters for MergeClient.
type MergeClientRequest struct {
	SourceClientId *int64 `json:"SourceClientId,omitempty"`
	TargetClientId *int64 `json:"TargetClientId,omitempty"`
}

// MergeClientResponse is the response type of MergeClient.
type MergeClientResponse = map[string]any

// MergeClient calls POST /public/v{version}/client/mergeclients.
func (c *Client) MergeClient(ctx context.Context, req *MergeClientRequest) (*MergeClientResponse, error) {
	if req == nil {
		req = &MergeClientRequest{}
	}
	out := &MergeClientResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/mergeclients",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendAutoEmailRequest holds the parameters for SendAutoEmail.
type SendAutoEmailRequest struct {
	ClientId  *string `json:"ClientId,omitempty"`
	EmailType *string `json:"EmailType,omitempty"`
}

// SendAutoEmailResponse is the response type of SendAutoEmail.
type SendAutoEmailResponse = map[string]any

// SendAutoEmail calls POST /public/v{version}/client/sendautoemail.
func (c *Client) SendAutoEmail(ctx context.Context, req *SendAutoEmailRequest) (*SendAutoEmailResponse, error) {
	if req == nil {
		req = &SendAutoEmailRequest{}
	}
	out := &SendAutoEmailResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/sendautoemail",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendPasswordResetEmailRequest holds the parameters for SendPasswordResetEmail.
type SendPasswordResetEmailRequest struct {
	UserEmail     *string `json:"UserEmail,omitempty"`
	UserFirstName *string `json:"UserFirstName,omitempty"`
	UserLastName  *string `json:"UserLastName,omitempty"`
}

// SendPasswordResetEmailResponse is the response type of SendPasswordResetEmail.
type SendPasswordResetEmailResponse = map[string]any

// SendPasswordResetEmail calls POST /public/v{version}/client/sendpasswordresetemail.
func (c *Client) SendPasswordResetEmail(ctx context.Context, req *SendPasswordResetEmailRequest) (*SendPasswordResetEmailResponse, error) {
	if req == nil {
		req = &SendPasswordResetEmailRequest{}
	}
	out := &SendPasswordResetEmailResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/sendpasswordresetemail",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuspendContractRequest holds the parameters for SuspendContract.
type SuspendContractRequest struct {
	ClientContractId *int                `json:"ClientContractId,omitempty"`
	ClientId         *string             `json:"ClientId,omitempty"`
	Duration         *int                `json:"Duration,omitempty"`
	DurationUnit     *int                `json:"DurationUnit,omitempty"`
	OpenEnded        *bool               `json:"OpenEnded,omitempty"`
	SuspensionFee    *float64            `json:"SuspensionFee,omitempty"`
	SuspensionNotes  *string             `json:"SuspensionNotes,omitempty"`
	SuspensionStart  *connector.DateTime `json:"SuspensionStart,omitempty"`
	SuspensionType   *string             `json:"SuspensionType,omitempty"`
}

// SuspendContract calls POST /public/v{version}/client/suspendcontract.
func (c *Client) SuspendContract(ctx context.Context, req *SuspendContractRequest) (*SuspendContractResponse, error) {
	if req == nil {
		req = &SuspendContractRequest{}
	}
	out := &SuspendContractResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/suspendcontract",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminateContractRequest holds the parameters for TerminateContract.
type TerminateContractRequest struct {
	ClientContractId    *int                `json:"ClientContractId,omitempty"`
	ClientId            *string             `json:"ClientId,omitempty"`
	TerminationCode     *string             `json:"TerminationCode,omitempty"`
	TerminationComments *string             `json:"TerminationComments,omitempty"`
	TerminationDate     *connector.DateTime `json:"TerminationDate,omitempty"`
}

// TerminateContract calls POST /public/v{version}/client/terminatecontract.
func (c *Client) TerminateContract(ctx context.Context, req *TerminateContractRequest) (*TerminateContractResponse, error) {
	if req == nil {
		req = &TerminateContractRequest{}
	}
	out := &TerminateContractResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/terminatecontract",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientRequest holds the parameters for UpdateClient.
type UpdateClientRequest struct {
	Client              *ClientWithSuspensionInfo `json:"Client,omitempty"`
	CrossRegionalUpdate *bool                     `json:"CrossRegionalUpdate,omitempty"`
	LeadChannelId       *int                      `json:"LeadChannelId,omitempty"`
	NewId               *string                   `json:"NewId,omitempty"`
	Test                *bool                     `json:"Test,omitempty"`
}

// UpdateClient calls POST /public/v{version}/client/updateclient.
func (c *Client) UpdateClient(ctx context.Context, req *UpdateClientRequest) (*UpdateClientResponse, error) {
	if req == nil {
		req = &UpdateClientRequest{}
	}
	out := &UpdateClientResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/updateclient",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientContractAutopaysRequest holds the parameters for UpdateClientContractAutopays.
type UpdateClientContractAutopaysRequest struct {
	Amount                 *float64            `json:"Amount,omitempty"`
	AutopayEndDate         *connector.DateTime `json:"AutopayEndDate,omitempty"`
	AutopayStartDate       *connector.DateTime `json:"AutopayStartDate,omitempty"`
	ClientContractId       *int                `json:"ClientContractId,omitempty"`
	OverwriteAllProductIDs *bool               `json:"OverwriteAllProductIDs,omitempty"`
	ProductId              *int                `json:"ProductId,omitempty"`
	ReplaceWithProductId   *int                `json:"ReplaceWithProductId,omitempty"`
}

// UpdateClientContractAutopaysResponse is the response type of UpdateClientContractAutopays.
type UpdateClientContractAutopaysResponse = Contract

// UpdateClientContractAutopays calls POST /public/v{version}/client/updateclientcontractautopays.
func (c *Client) UpdateClientContractAutopays(ctx context.Context, req *UpdateClientContractAutopaysRequest) (*UpdateClientContractAutopaysResponse, error) {
	if req == nil {
		req = &UpdateClientContractAutopaysRequest{}
	}
	out := &UpdateClientContractAutopaysResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/updateclientcontractautopays",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientRewardsRequest holds the parameters for UpdateClientRewards.
type UpdateClientRewardsRequest struct {
	Action         *string             `json:"Action,omitempty"`
	ActionDateTime *connector.DateTime `json:"ActionDateTime,omitempty"`
	ClientId       *string             `json:"ClientId,omitempty"`
	Points         *int64              `json:"Points,omitempty"`
	Source         *string             `json:"Source,omitempty"`
	SourceId       *int64              `json:"SourceId,omitempty"`
}

// UpdateClientRewardsResponse is the response type of UpdateClientRewards.
type UpdateClientRewardsResponse = GetClientRewardsResponse

// UpdateClientRewards calls POST /public/v{version}/client/clientrewards.
func (c *Client) UpdateClientRewards(ctx context.Context, req *UpdateClientRewardsRequest) (*UpdateClientRewardsResponse, error) {
	if req == nil {
		req = &UpdateClientRewardsRequest{}
	}
	out := &UpdateClientRewardsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/clientrewards",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientServiceRequest holds the parameters for UpdateClientService.
type UpdateClientServiceRequest struct {
	ActiveDate     *connector.DateTime `json:"ActiveDate,omitempty"`
	Count          *int                `json:"Count,omitempty"`
	ExpirationDate *connector.DateTime `json:"ExpirationDate,omitempty"`
	ServiceId      *int                `json:"ServiceId,omitempty"`
	Test           *bool               `json:"Test,omitempty"`
}

// UpdateClientService calls POST /public/v{version}/client/updateclientservice.
func (c *Client) UpdateClientService(ctx context.Context, req *UpdateClientServiceRequest) (*UpdateClientServiceResponse, error) {
	if req == nil {
		req = &UpdateClientServiceRequest{}
	}
	out := &UpdateClientServiceResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/updateclientservice",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientVisitRequest holds the parameters for UpdateClientVisit.
type UpdateClientVisitRequest struct {
	ClientServiceId *int    `json:"ClientServiceId,omitempty"`
	Execute         *string `json:"Execute,omitempty"`
	Makeup          *bool   `json:"Makeup,omitempty"`
	SendEmail       *bool   `json:"SendEmail,omitempty"`
	SignedIn        *bool   `json:"SignedIn,omitempty"`
	Test            *bool   `json:"Test,omitempty"`
	VisitId         *int    `json:"VisitId,omitempty"`
}

// UpdateClientVisit calls POST /public/v{version}/client/updateclientvisit.
func (c *Client) UpdateClientVisit(ctx context.Context, req *UpdateClientVisitRequest) (*UpdateClientVisitResponse, error) {
	if req == nil {
		req = &UpdateClientVisitRequest{}
	}
	out := &UpdateClientVisitResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/updateclientvisit",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateContactLogRequest holds the parameters for UpdateContactLog.
type UpdateContactLogRequest struct {
	AssignedToStaffId *int64                    `json:"AssignedToStaffId,omitempty"`
	Comments          []UpdateContactLogComment `json:"Comments,omitempty"`
	ContactMethod     *string                   `json:"ContactMethod,omitempty"`
	ContactName       *string                   `json:"ContactName,omitempty"`
	FollowupByDate    *connector.DateTime       `json:"FollowupByDate,omitempty"`
	Id                *int                      `json:"Id,omitempty"`
	IsComplete        *bool                     `json:"IsComplete,omitempty"`
	Test              *bool                     `json:"Test,omitempty"`
	Text              *string                   `json:"Text,omitempty"`
	Types             []UpdateContactLogType    `json:"Types,omitempty"`
}

// UpdateContactLogResponse is the response type of UpdateContactLog.
type UpdateContactLogResponse = ContactLog

// UpdateContactLog calls POST /public/v{version}/client/updatecontactlog.
func (c *Client) UpdateContactLog(ctx context.Context, req *UpdateContactLogRequest) (*UpdateContactLogResponse, error) {
	if req == nil {
		req = &UpdateContactLogRequest{}
	}
	out := &UpdateContactLogResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/updatecontactlog",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadClientDocumentRequest holds the parameters for UploadClientDocument.
type UploadClientDocumentRequest struct {
	ClientId *string         `json:"ClientId,omitempty"`
	File     *ClientDocument `json:"File,omitempty"`
}

// UploadClientDocument calls POST /public/v{version}/client/uploadclientdocument.
func (c *Client) UploadClientDocument(ctx context.Context, req *UploadClientDocumentRequest) (*UploadClientDocumentResponse, error) {
	if req == nil {
		req = &UploadClientDocumentRequest{}
	}
	out := &UploadClientDocumentResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/uploadclientdocument",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadClientPhotoRequest holds the parameters for UploadClientPhoto.
type UploadClientPhotoRequest struct {
	Bytes    []byte  `json:"Bytes,omitempty"`
	ClientId *string `json:"ClientId,omitempty"`
}

// UploadClientPhoto calls POST /public/v{version}/client/uploadclientphoto.
func (c *Client) UploadClientPhoto(ctx context.Context, req *UploadClientPhotoRequest) (*UploadClientPhotoResponse, error) {
	if req == nil {
		req = &UploadClientPhotoRequest{}
	}
	out := &UploadClientPhotoResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/client/uploadclientphoto",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
