// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CopyCreditCardRequest holds the parameters for CopyCreditCard.
type CopyCreditCardRequest struct {
	SourceClientId       *string `json:"SourceClientId,omitempty"`
	SourceSiteId         *int    `json:"SourceSiteId,omitempty"`
	SourceUniqueClientId *int64  `json:"SourceUniqueClientId,omitempty"`
	TargetClientId       *string `json:"TargetClientId,omitempty"`
	TargetSiteId         *int    `json:"TargetSiteId,omitempty"`
	TargetUniqueClientId *int64  `json:"TargetUniqueClientId,omitempty"`
}

// CopyCreditCard calls POST /public/v{version}/crossSite/copycreditcard.
func (c *Client) CopyCreditCard(ctx context.Context, req *CopyCreditCardRequest) (*CopyCreditCardResponse, error) {
	if req == nil {
		req = &CopyCreditCardRequest{}
	}
	out := &CopyCreditCardResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/crossSite/copycreditcard",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
