// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// GetCommissionsRequest holds the parameters for GetCommissions.
type GetCommissionsRequest struct {
	EndDateTime   *connector.DateTime `json:"-" query:"request.endDateTime"`
	Limit         *int                `json:"-" query:"request.limit"`
	LocationId    *int                `json:"-" query:"request.locationId"`
	Offset        *int                `json:"-" query:"request.offset"`
	StaffId       *int64              `json:"-" query:"request.staffId"`
	StartDateTime *connector.DateTime `json:"-" query:"request.startDateTime"`
}

// GetCommissions calls GET /public/v{version}/payroll/commissions.
func (c *Client) GetCommissions(ctx context.Context, req *GetCommissionsRequest) (*GetCommissionsResponse, error) {
	if req == nil {
		req = &GetCommissionsRequest{}
	}
	out := &GetCommissionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/payroll/commissions",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetScheduledServiceEarningsRequest holds the parameters for GetScheduledServiceEarnings.
type GetScheduledServiceEarningsRequest struct {
	EndDateTime          *connector.DateTime `json:"-" query:"request.endDateTime"`
	Limit                *int                `json:"-" query:"request.limit"`
	LocationId           *int                `json:"-" query:"request.locationId"`
	Offset               *int                `json:"-" query:"request.offset"`
	ScheduledServiceId   *int64              `json:"-" query:"request.scheduledServiceId"`
	ScheduledServiceType *string             `json:"-" query:"request.scheduledServiceType"`
	StaffId              *int64              `json:"-" query:"request.staffId"`
	StartDateTime        *connector.DateTime `json:"-" query:"request.startDateTime"`
}

// GetScheduledServiceEarnings calls GET /public/v{version}/payroll/scheduledserviceearnings.
func (c *Client) GetScheduledServiceEarnings(ctx context.Context, req *GetScheduledServiceEarningsRequest) (*GetScheduledServiceEarningsResponse, error) {
	if req == nil {
		req = &GetScheduledServiceEarningsRequest{}
	}
	out := &GetScheduledServiceEarningsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/payroll/scheduledserviceearnings",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTimeCardsRequest holds the parameters for GetTimeCards.
type GetTimeCardsRequest struct {
	EndDateTime   *connector.DateTime `json:"-" query:"request.endDateTime"`
	Limit         *int                `json:"-" query:"request.limit"`
	LocationId    *int                `json:"-" query:"request.locationId"`
	Offset        *int                `json:"-" query:"request.offset"`
	StaffId       *int64              `json:"-" query:"request.staffId"`
	StartDateTime *connector.DateTime `json:"-" query:"request.startDateTime"`
}

// GetTimeCards calls GET /public/v{version}/payroll/timecards.
func (c *Client) GetTimeCards(ctx context.Context, req *GetTimeCardsRequest) (*GetTimeCardsResponse, error) {
	if req == nil {
		req = &GetTimeCardsRequest{}
	}
	out := &GetTimeCardsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/payroll/timecards",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTipsRequest holds the parameters for GetTips.
type GetTipsRequest struct {
	EndDateTime   *connector.DateTime `json:"-" query:"request.endDateTime"`
	Limit         *int                `json:"-" query:"request.limit"`
	LocationId    *int                `json:"-" query:"request.locationId"`
	Offset        *int                `json:"-" query:"request.offset"`
	StaffId       *int64              `json:"-" query:"request.staffId"`
	StartDateTime *connector.DateTime `json:"-" query:"request.startDateTime"`
}

// GetTips calls GET /public/v{version}/payroll/tips.
func (c *Client) GetTips(ctx context.Context, req *GetTipsRequest) (*GetTipsResponse, error) {
	if req == nil {
		req = &GetTipsRequest{}
	}
	out := &GetTipsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/payroll/tips",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
