// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// CreateReservationRequest holds the parameters for CreateReservation.
type CreateReservationRequest struct {
	PathInfo string `json:"-" path:"pathInfo"`
}

// CreateReservation calls POST /public/v{version}/pickaspot/v1/reservation/{pathInfo}.
func (c *Client) CreateReservation(ctx context.Context, req *CreateReservationRequest) (*CreateReservationResponse, error) {
	out := &CreateReservationResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/pickaspot/v1/reservation/{pathInfo}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteReservationRequest holds the parameters for DeleteReservation.
type DeleteReservationRequest struct {
	PathInfo string `json:"-" path:"pathInfo"`
}

// DeleteReservationResponse is the response type of DeleteReservation.
type DeleteReservationResponse = HttpContent

// DeleteReservation calls DELETE /public/v{version}/pickaspot/v1/reservation/{pathInfo}.
func (c *Client) DeleteReservation(ctx context.Context, req *DeleteReservationRequest) (*DeleteReservationResponse, error) {
	out := &DeleteReservationResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/pickaspot/v1/reservation/{pathInfo}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassRequest holds the parameters for GetClass.
type GetClassRequest struct {
	ClassId string `json:"-" path:"classId"`
}

// GetClassResponse is the response type of GetClass.
type GetClassResponse = GetPickASpotClassResponse

// GetClass calls GET /public/v{version}/pickaspot/v1/class/{classId}.
func (c *Client) GetClass(ctx context.Context, req *GetClassRequest) (*GetClassResponse, error) {
	out := &GetClassResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/pickaspot/v1/class/{classId}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetClassListRequest holds the parameters for GetClassList.
type GetClassListRequest struct {
}

// GetClassListResponse is the response type of GetClassList.
type GetClassListResponse = GetPickASpotClassResponse

// GetClassList calls GET /public/v{version}/pickaspot/v1/class.
func (c *Client) GetClassList(ctx context.Context, req *GetClassListRequest) (*GetClassListResponse, error) {
	out := &GetClassListResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/pickaspot/v1/class",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetReservationRequest holds the parameters for GetReservation.
type GetReservationRequest struct {
	PathInfo string `json:"-" path:"pathInfo"`
}

// GetReservation calls GET /public/v{version}/pickaspot/v1/reservation/{pathInfo}.
func (c *Client) GetReservation(ctx context.Context, req *GetReservationRequest) (*GetReservationResponse, error) {
	out := &GetReservationResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/pickaspot/v1/reservation/{pathInfo}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateReservationRequest holds the parameters for UpdateReservation.
type UpdateReservationRequest struct {
	PathInfo string `json:"-" path:"pathInfo"`
}

// UpdateReservation calls PUT /public/v{version}/pickaspot/v1/reservation/{pathInfo}.
func (c *Client) UpdateReservation(ctx context.Context, req *UpdateReservationRequest) (*UpdateReservationResponse, error) {
	out := &UpdateReservationResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "PUT",
		Path:   "/public/v{version}/pickaspot/v1/reservation/{pathInfo}",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
