// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// AddClientIndexRequest holds the parameters for AddClientIndex.
type AddClientIndexRequest struct {
	Active                 *bool   `json:"Active,omitempty"`
	ClientIndexName        *string `json:"ClientIndexName,omitempty"`
	EditOnEnrollmentRoster *bool   `json:"EditOnEnrollmentRoster,omitempty"`
	RequiredBizMode        *bool   `json:"RequiredBizMode,omitempty"`
	RequiredConsumerMode   *bool   `json:"RequiredConsumerMode,omitempty"`
	ShowInConsumerMode     *bool   `json:"ShowInConsumerMode,omitempty"`
	ShowOnEnrollmentRoster *bool   `json:"ShowOnEnrollmentRoster,omitempty"`
	ShowOnNewClient        *bool   `json:"ShowOnNewClient,omitempty"`
	SortOrder              *int    `json:"SortOrder,omitempty"`
}

// AddClientIndexResponse is the response type of AddClientIndex.
type AddClientIndexResponse = AddSiteClientIndexResponse

// AddClientIndex calls POST /public/v{version}/site/addclientindex.
func (c *Client) AddClientIndex(ctx context.Context, req *AddClientIndexRequest) (*AddClientIndexResponse, error) {
	out := &AddClientIndexResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/site/addclientindex",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddPromoCodeRequest holds the parameters for AddPromoCode.
type AddPromoCodeRequest struct {
	ActivationDate     *connector.DateTime `json:"ActivationDate,omitempty"`
	Active             *bool               `json:"Active,omitempty"`
	AllowOnline        *bool               `json:"AllowOnline,omitempty"`
	ApplicableItems    []ApplicableItem    `json:"ApplicableItems,omitempty"`
	Code               *string             `json:"Code,omitempty"`
	DaysAfterCloseDate *int                `json:"DaysAfterCloseDate,omitempty"`
	DaysValid          []string            `json:"DaysValid,omitempty"`
	Discount           *Discount           `json:"Discount,omitempty"`
	ExpirationDate     *connector.DateTime `json:"ExpirationDate,omitempty"`
	MaxUses            *int                `json:"MaxUses,omitempty"`
	Name               *string             `json:"Name,omitempty"`
}

// AddPromoCode calls POST /public/v{version}/site/addpromocode.
func (c *Client) AddPromoCode(ctx context.Context, req *AddPromoCodeRequest) (*AddPromoCodeResponse, error) {
	out := &AddPromoCodeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/site/addpromocode",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeactivatePromoCodeRequest holds the parameters for DeactivatePromoCode.
type DeactivatePromoCodeRequest struct {
	PromotionId *int `json:"PromotionId,omitempty"`
}

// DeactivatePromoCodeResponse is the response type of DeactivatePromoCode.
type DeactivatePromoCodeResponse = map[string]any

// DeactivatePromoCode calls POST /public/v{version}/site/deactivatepromocode.
func (c *Client) DeactivatePromoCode(ctx context.Context, req *DeactivatePromoCodeRequest) (*DeactivatePromoCodeResponse, error) {
	out := &DeactivatePromoCodeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/site/deactivatepromocode",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetActivationCodeRequest holds the parameters for GetActivationCode.
type GetActivationCodeRequest struct {
}

// GetActivationCode calls GET /public/v{version}/site/activationcode.
func (c *Client) GetActivationCode(ctx context.Context, req *GetActivationCodeRequest) (*GetActivationCodeResponse, error) {
	out := &GetActivationCodeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/activationcode",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCategoriesRequest holds the parameters for GetCategories.
type GetCategoriesRequest struct {
	Active         *bool `json:"-" query:"request.active"`
	CategoryIds    []int `json:"-" query:"request.categoryIds"`
	Limit          *int  `json:"-" query:"request.limit"`
	Offset         *int  `json:"-" query:"request.offset"`
	Service        *bool `json:"-" query:"request.service"`
	SubCategoryIds []int `json:"-" query:"request.subCategoryIds"`
}

// GetCategories calls GET /public/v{version}/site/categories.
func (c *Client) GetCategories(ctx context.Context, req *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	out := &GetCategoriesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/categories",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetGendersRequest holds the parameters for GetGenders.
type GetGendersRequest struct {
}

// GetGenders calls GET /public/v{version}/site/genders.
func (c *Client) GetGenders(ctx context.Context, req *GetGendersRequest) (*GetGendersResponse, error) {
	out := &GetGendersResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/genders",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetLiabilityWaiverRequest holds the parameters for GetLiabilityWaiver.
type GetLiabilityWaiverRequest struct {
}

// GetLiabilityWaiver calls GET /public/v{version}/site/liabilitywaiver.
func (c *Client) GetLiabilityWaiver(ctx context.Context, req *GetLiabilityWaiverRequest) (*GetLiabilityWaiverResponse, error) {
	out := &GetLiabilityWaiverResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/liabilitywaiver",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetLocationsRequest holds the parameters for GetLocations.
type GetLocationsRequest struct {
	Limit  *int `json:"-" query:"request.limit"`
	Offset *int `json:"-" query:"request.offset"`
}

// GetLocations calls GET /public/v{version}/site/locations.
func (c *Client) GetLocations(ctx context.Context, req *GetLocationsRequest) (*GetLocationsResponse, error) {
	out := &GetLocationsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/locations",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMembershipsRequest holds the parameters for GetMemberships.
type GetMembershipsRequest struct {
	MembershipIds []int `json:"-" query:"request.membershipIds"`
}

// GetMemberships calls GET /public/v{version}/site/memberships.
func (c *Client) GetMemberships(ctx context.Context, req *GetMembershipsRequest) (*GetMembershipsResponse, error) {
	out := &GetMembershipsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/memberships",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMobileProvidersRequest holds the parameters for GetMobileProviders.
type GetMobileProvidersRequest struct {
	Active *bool `json:"-" query:"request.active"`
}

// GetMobileProviders calls GET /public/v{version}/site/mobileproviders.
func (c *Client) GetMobileProviders(ctx context.Context, req *GetMobileProvidersRequest) (*GetMobileProvidersResponse, error) {
	out := &GetMobileProvidersResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/mobileproviders",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPaymentTypesRequest holds the parameters for GetPaymentTypes.
type GetPaymentTypesRequest struct {
	Active *bool `json:"-" query:"request.active"`
}

// GetPaymentTypes calls GET /public/v{version}/site/paymenttypes.
func (c *Client) GetPaymentTypes(ctx context.Context, req *GetPaymentTypesRequest) (*GetPaymentTypesResponse, error) {
	out := &GetPaymentTypesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/paymenttypes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetProgramsRequest holds the parameters for GetPrograms.
type GetProgramsRequest struct {
	Limit        *int    `json:"-" query:"request.limit"`
	Offset       *int    `json:"-" query:"request.offset"`
	OnlineOnly   *bool   `json:"-" query:"request.onlineOnly"`
	ProgramIds   []int   `json:"-" query:"request.programIds"`
	ScheduleType *string `json:"-" query:"request.scheduleType"`
}

// GetPrograms calls GET /public/v{version}/site/programs.
func (c *Client) GetPrograms(ctx context.Context, req *GetProgramsRequest) (*GetProgramsResponse, error) {
	out := &GetProgramsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/programs",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPromoCodesRequest holds the parameters for GetPromoCodes.
type GetPromoCodesRequest struct {
	ActiveOnly       *bool               `json:"-" query:"request.activeOnly"`
	EndDate          *connector.DateTime `json:"-" query:"request.endDate"`
	LastModifiedDate *connector.DateTime `json:"-" query:"request.lastModifiedDate"`
	Limit            *int                `json:"-" query:"request.limit"`
	Offset           *int                `json:"-" query:"request.offset"`
	OnlineOnly       *bool               `json:"-" query:"request.onlineOnly"`
	StartDate        *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetPromoCodes calls GET /public/v{version}/site/promocodes.
func (c *Client) GetPromoCodes(ctx context.Context, req *GetPromoCodesRequest) (*GetPromoCodesResponse, error) {
	out := &GetPromoCodesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/promocodes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetProspectStagesRequest holds the parameters for GetProspectStages.
type GetProspectStagesRequest struct {
	Active *bool `json:"-" query:"request.active"`
}

// GetProspectStages calls GET /public/v{version}/site/prospectstages.
func (c *Client) GetProspectStages(ctx context.Context, req *GetProspectStagesRequest) (*GetProspectStagesResponse, error) {
	out := &GetProspectStagesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/prospectstages",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRelationshipsRequest holds the parameters for GetRelationships.
type GetRelationshipsRequest struct {
	Active *bool `json:"-" query:"request.active"`
	Limit  *int  `json:"-" query:"request.limit"`
	Offset *int  `json:"-" query:"request.offset"`
}

// GetRelationships calls GET /public/v{version}/site/relationships.
func (c *Client) GetRelationships(ctx context.Context, req *GetRelationshipsRequest) (*GetRelationshipsResponse, error) {
	out := &GetRelationshipsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/relationships",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetResourceAvailabilitiesRequest holds the parameters for GetResourceAvailabilities.
type GetResourceAvailabilitiesRequest struct {
	EndDate       *connector.DateTime `json:"-" query:"request.endDate"`
	Limit         *int                `json:"-" query:"request.limit"`
	LocationIds   []int               `json:"-" query:"request.locationIds"`
	Offset        *int                `json:"-" query:"request.offset"`
	ProgramIds    []int               `json:"-" query:"request.programIds"`
	ResourceIds   []int               `json:"-" query:"request.resourceIds"`
	ScheduleTypes []string            `json:"-" query:"request.scheduleTypes"`
	StartDate     *connector.DateTime `json:"-" query:"request.startDate"`
}

// GetResourceAvailabilities calls GET /public/v{version}/site/resourceavailabilities.
func (c *Client) GetResourceAvailabilities(ctx context.Context, req *GetResourceAvailabilitiesRequest) (*GetResourceAvailabilitiesResponse, error) {
	out := &GetResourceAvailabilitiesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/resourceavailabilities",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetResourcesRequest holds the parameters for GetResources.
type GetResourcesRequest struct {
	IncludeInactive *bool    `json:"-" query:"request.includeInactive"`
	Limit           *int     `json:"-" query:"request.limit"`
	LocationIds     []int    `json:"-" query:"request.locationIds"`
	Offset          *int     `json:"-" query:"request.offset"`
	ProgramIds      []int    `json:"-" query:"request.programIds"`
	ResourceIds     []int    `json:"-" query:"request.resourceIds"`
	ScheduleTypes   []string `json:"-" query:"request.scheduleTypes"`
}

// GetResourcesResponse is the response type of GetResources.
type GetResourcesResponse = map[string]any

// GetResources calls GET /public/v{version}/site/resources.
func (c *Client) GetResources(ctx context.Context, req *GetResourcesRequest) (*GetResourcesResponse, error) {
	out := &GetResourcesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/resources",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSessionTypesRequest holds the parameters for GetSessionTypes.
type GetSessionTypesRequest struct {
	Limit      *int  `json:"-" query:"request.limit"`
	Offset     *int  `json:"-" query:"request.offset"`
	OnlineOnly *bool `json:"-" query:"request.onlineOnly"`
	ProgramIDs []int `json:"-" query:"request.programIDs"`
}

// GetSessionTypes calls GET /public/v{version}/site/sessiontypes.
func (c *Client) GetSessionTypes(ctx context.Context, req *GetSessionTypesRequest) (*GetSessionTypesResponse, error) {
	out := &GetSessionTypesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/sessiontypes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSitesRequest holds the parameters for GetSites.
type GetSitesRequest struct {
	IncludeLeadChannels    *bool `json:"-" query:"request.includeLeadChannels"`
	IncludePerStaffPricing *bool `json:"-" query:"request.includePerStaffPricing"`
	Limit                  *int  `json:"-" query:"request.limit"`
	Offset                 *int  `json:"-" query:"request.offset"`
	SiteIds                []int `json:"-" query:"request.siteIds"`
}

// GetSites calls GET /public/v{version}/site/sites.
func (c *Client) GetSites(ctx context.Context, req *GetSitesRequest) (*GetSitesResponse, error) {
	out := &GetSitesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/site/sites",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateClientIndexRequest holds the parameters for UpdateClientIndex.
type UpdateClientIndexRequest struct {
	Active                 *bool   `json:"Active,omitempty"`
	ClientIndexID          *int    `json:"ClientIndexID,omitempty"`
	ClientIndexName        *string `json:"ClientIndexName,omitempty"`
	EditOnEnrollmentRoster *bool   `json:"EditOnEnrollmentRoster,omitempty"`
	RequiredBizMode        *bool   `json:"RequiredBizMode,omitempty"`
	RequiredConsumerMode   *bool   `json:"RequiredConsumerMode,omitempty"`
	ShowInConsumerMode     *bool   `json:"ShowInConsumerMode,omitempty"`
	ShowOnEnrollmentRoster *bool   `json:"ShowOnEnrollmentRoster,omitempty"`
	ShowOnNewClient        *bool   `json:"ShowOnNewClient,omitempty"`
	SortOrder              *int    `json:"SortOrder,omitempty"`
}

// UpdateClientIndexResponse is the response type of UpdateClientIndex.
type UpdateClientIndexResponse = UpdateSiteClientIndexResponse

// UpdateClientIndex calls POST /public/v{version}/site/updateclientindex.
func (c *Client) UpdateClientIndex(ctx context.Context, req *UpdateClientIndexRequest) (*UpdateClientIndexResponse, error) {
	out := &UpdateClientIndexResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/site/updateclientindex",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
