// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// AddStaffRequest holds the parameters for AddStaff.
type AddStaffRequest struct {
	Address                  *string             `json:"Address,omitempty"`
	Address2                 *string             `json:"Address2,omitempty"`
	AlwaysAllowDoubleBooking *bool               `json:"AlwaysAllowDoubleBooking,omitempty"`
	AppointmentInstructor    *bool               `json:"AppointmentInstructor,omitempty"`
	Bio                      *string             `json:"Bio,omitempty"`
	City                     *string             `json:"City,omitempty"`
	ClassAssistant           *bool               `json:"ClassAssistant,omitempty"`
	ClassAssistant2          *bool               `json:"ClassAssistant2,omitempty"`
	ClassTeacher             *bool               `json:"ClassTeacher,omitempty"`
	Country                  *string             `json:"Country,omitempty"`
	DefaultClassPayRate      *int                `json:"DefaultClassPayRate,omitempty"`
	Email                    *string             `json:"Email,omitempty"`
	EmpID                    *string             `json:"EmpID,omitempty"`
	EmploymentEnd            *connector.DateTime `json:"EmploymentEnd,omitempty"`
	EmploymentStart          *connector.DateTime `json:"EmploymentStart,omitempty"`
	FirstName                *string             `json:"FirstName,omitempty"`
	HomePhone                *string             `json:"HomePhone,omitempty"`
	IndependentContractor    *bool               `json:"IndependentContractor,omitempty"`
	IsMale                   *bool               `json:"IsMale,omitempty"`
	LastName                 *string             `json:"LastName,omitempty"`
	MobilePhone              *string             `json:"MobilePhone,omitempty"`
	Notes                    *string             `json:"Notes,omitempty"`
	PostalCode               *string             `json:"PostalCode,omitempty"`
	ProviderIDs              []string            `json:"ProviderIDs,omitempty"`
	SortOrder                *int                `json:"SortOrder,omitempty"`
	State                    *string             `json:"State,omitempty"`
	WorkPhone                *string             `json:"WorkPhone,omitempty"`
}

// AddStaff calls POST /public/v{version}/staff/addstaff.
func (c *Client) AddStaff(ctx context.Context, req *AddStaffRequest) (*AddStaffResponse, error) {
	out := &AddStaffResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/staff/addstaff",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddStaffAvailabilityRequest holds the parameters for AddStaffAvailability.
type AddStaffAvailabilityRequest struct {
	DaysOfWeek     []string `json:"DaysOfWeek,omitempty"`
	Description    *string  `json:"Description,omitempty"`
	EndDate        *string  `json:"EndDate,omitempty"`
	EndTime        *string  `json:"EndTime,omitempty"`
	IsAvailability *bool    `json:"IsAvailability,omitempty"`
	LocationId     *int     `json:"LocationId,omitempty"`
	ProgramIds     []int    `json:"ProgramIds,omitempty"`
	StaffId        *int64   `json:"StaffId,omitempty"`
	StartDate      *string  `json:"StartDate,omitempty"`
	StartTime      *string  `json:"StartTime,omitempty"`
	Status         *string  `json:"Status,omitempty"`
}

// AddStaffAvailabilityResponse is the (empty) response type of AddStaffAvailability.
type AddStaffAvailabilityResponse struct{}

// AddStaffAvailability calls POST /public/v{version}/staff/staffavailability.
func (c *Client) AddStaffAvailability(ctx context.Context, req *AddStaffAvailabilityRequest) (*AddStaffAvailabilityResponse, error) {
	out := &AddStaffAvailabilityResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/staff/staffavailability",
		Req:    req,
		Body:   req,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignStaffSessionTypeRequest holds the parameters for AssignStaffSessionType.
type AssignStaffSessionTypeRequest struct {
	Active        *bool    `json:"Active,omitempty"`
	FinishTime    *int     `json:"FinishTime,omitempty"`
	PayRateAmount *float64 `json:"PayRateAmount,omitempty"`
	PayRateType   *string  `json:"PayRateType,omitempty"`
	PrepTime      *int     `json:"PrepTime,omitempty"`
	SessionTypeId *int     `json:"SessionTypeId,omitempty"`
	StaffId       *int64   `json:"StaffId,omitempty"`
	TimeLength    *int     `json:"TimeLength,omitempty"`
}

// AssignStaffSessionType calls POST /public/v{version}/staff/assignsessiontype.
func (c *Client) AssignStaffSessionType(ctx context.Context, req *AssignStaffSessionTypeRequest) (*AssignStaffSessionTypeResponse, error) {
	out := &AssignStaffSessionTypeResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/staff/assignsessiontype",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSalesRepsRequest holds the parameters for GetSalesReps.
type GetSalesRepsRequest struct {
	ActiveOnly      *bool `json:"-" query:"request.activeOnly"`
	Limit           *int  `json:"-" query:"request.limit"`
	Offset          *int  `json:"-" query:"request.offset"`
	SalesRepNumbers []int `json:"-" query:"request.salesRepNumbers"`
}

// GetSalesReps calls GET /public/v{version}/staff/salesreps.
func (c *Client) GetSalesReps(ctx context.Context, req *GetSalesRepsRequest) (*GetSalesRepsResponse, error) {
	out := &GetSalesRepsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/staff/salesreps",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStaffRequest holds the parameters for GetStaff.
type GetStaffRequest struct {
	Filters         []string            `json:"-" query:"request.filters"`
	IncludeInactive *bool               `json:"-" query:"request.includeInactive"`
	Limit           *int                `json:"-" query:"request.limit"`
	LocationId      *int                `json:"-" query:"request.locationId"`
	Offset          *int                `json:"-" query:"request.offset"`
	SessionTypeId   *int                `json:"-" query:"request.sessionTypeId"`
	StaffIds        []int64             `json:"-" query:"request.staffIds"`
	StartDateTime   *connector.DateTime `json:"-" query:"request.startDateTime"`
}

// GetStaff calls GET /public/v{version}/staff/staff.
func (c *Client) GetStaff(ctx context.Context, req *GetStaffRequest) (*GetStaffResponse, error) {
	out := &GetStaffResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/staff/staff",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStaffImageURLRequest holds the parameters for GetStaffImageURL.
type GetStaffImageURLRequest struct {
	StaffId *int64 `json:"-" query:"request.staffId"`
}

// GetStaffImageURL calls GET /public/v{version}/staff/imageurl.
func (c *Client) GetStaffImageURL(ctx context.Context, req *GetStaffImageURLRequest) (*GetStaffImageURLResponse, error) {
	out := &GetStaffImageURLResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/staff/imageurl",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStaffPermissionsRequest holds the parameters for GetStaffPermissions.
type GetStaffPermissionsRequest struct {
	StaffId *int64 `json:"-" query:"request.staffId"`
}

// GetStaffPermissions calls GET /public/v{version}/staff/staffpermissions.
func (c *Client) GetStaffPermissions(ctx context.Context, req *GetStaffPermissionsRequest) (*GetStaffPermissionsResponse, error) {
	out := &GetStaffPermissionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/staff/staffpermissions",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStaffSessionTypesRequest holds the parameters for GetStaffSessionTypes.
type GetStaffSessionTypesRequest struct {
	Limit      *int   `json:"-" query:"request.limit"`
	Offset     *int   `json:"-" query:"request.offset"`
	OnlineOnly *bool  `json:"-" query:"request.onlineOnly"`
	ProgramIds []int  `json:"-" query:"request.programIds"`
	StaffId    *int64 `json:"-" query:"request.staffId"`
}

// GetStaffSessionTypes calls GET /public/v{version}/staff/sessiontypes.
func (c *Client) GetStaffSessionTypes(ctx context.Context, req *GetStaffSessionTypesRequest) (*GetStaffSessionTypesResponse, error) {
	out := &GetStaffSessionTypesResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "GET",
		Path:   "/public/v{version}/staff/sessiontypes",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateStaffRequest holds the parameters for UpdateStaff.
type UpdateStaffRequest struct {
	Active                   *bool               `json:"Active,omitempty"`
	Address                  *string             `json:"Address,omitempty"`
	Address2                 *string             `json:"Address2,omitempty"`
	AlwaysAllowDoubleBooking *bool               `json:"AlwaysAllowDoubleBooking,omitempty"`
	AppointmentInstructor    *bool               `json:"AppointmentInstructor,omitempty"`
	Bio                      *string             `json:"Bio,omitempty"`
	City                     *string             `json:"City,omitempty"`
	ClassAssistant           *bool               `json:"ClassAssistant,omitempty"`
	ClassAssistant2          *bool               `json:"ClassAssistant2,omitempty"`
	ClassTeacher             *bool               `json:"ClassTeacher,omitempty"`
	Country                  *string             `json:"Country,omitempty"`
	DefaultClassPayRate      *int                `json:"DefaultClassPayRate,omitempty"`
	Email                    *string             `json:"Email,omitempty"`
	EmpID                    *string             `json:"EmpID,omitempty"`
	EmploymentEnd            *connector.DateTime `json:"EmploymentEnd,omitempty"`
	EmploymentStart          *connector.DateTime `json:"EmploymentStart,omitempty"`
	FirstName                *string             `json:"FirstName,omitempty"`
	HomePhone                *string             `json:"HomePhone,omitempty"`
	ID                       *int64              `json:"ID,omitempty"`
	IndependentContractor    *bool               `json:"IndependentContractor,omitempty"`
	IsMale                   *bool               `json:"IsMale,omitempty"`
	LastName                 *string             `json:"LastName,omitempty"`
	MobilePhone              *string             `json:"MobilePhone,omitempty"`
	Notes                    *string             `json:"Notes,omitempty"`
	PostalCode               *string             `json:"PostalCode,omitempty"`
	ProviderIDs              []string            `json:"ProviderIDs,omitempty"`
	SortOrder                *int                `json:"SortOrder,omitempty"`
	State                    *string             `json:"State,omitempty"`
	WorkPhone                *string             `json:"WorkPhone,omitempty"`
}

// UpdateStaff calls POST /public/v{version}/staff/updatestaff.
func (c *Client) UpdateStaff(ctx context.Context, req *UpdateStaffRequest) (*UpdateStaffResponse, error) {
	out := &UpdateStaffResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/staff/updatestaff",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateStaffPermissionsRequest holds the parameters for UpdateStaffPermissions.
type UpdateStaffPermissionsRequest struct {
	PermissionGroupName *string `json:"PermissionGroupName,omitempty"`
	StaffId             *int64  `json:"StaffId,omitempty"`
}

// UpdateStaffPermissions calls POST /public/v{version}/staff/updatestaffpermissions.
func (c *Client) UpdateStaffPermissions(ctx context.Context, req *UpdateStaffPermissionsRequest) (*UpdateStaffPermissionsResponse, error) {
	out := &UpdateStaffPermissionsResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/staff/updatestaffpermissions",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
