// Code generated by connector-gen. DO NOT EDIT.

package mindbody

import (
	"context"
	"github.com/pax-beehive/connector"
)

// IssueTokenRequest holds the parameters for IssueToken.
type IssueTokenRequest struct {
	Password *string `json:"Password,omitempty"`
	Username *string `json:"Username,omitempty"`
}

// IssueTokenResponse is the response type of IssueToken.
type IssueTokenResponse = IssueResponse

// IssueToken calls POST /public/v{version}/usertoken/issue.
func (c *Client) IssueToken(ctx context.Context, req *IssueTokenRequest) (*IssueTokenResponse, error) {
	out := &IssueTokenResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/usertoken/issue",
		Req:    req,
		Body:   req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenewTokenRequest holds the parameters for RenewToken.
type RenewTokenRequest struct {
}

// RenewTokenResponse is the response type of RenewToken.
type RenewTokenResponse = map[string]any

// RenewToken calls POST /public/v{version}/usertoken/renew.
func (c *Client) RenewToken(ctx context.Context, req *RenewTokenRequest) (*RenewTokenResponse, error) {
	out := &RenewTokenResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "POST",
		Path:   "/public/v{version}/usertoken/renew",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevokeTokenRequest holds the parameters for RevokeToken.
type RevokeTokenRequest struct {
}

// RevokeTokenResponse is the response type of RevokeToken.
type RevokeTokenResponse = map[string]any

// RevokeToken calls DELETE /public/v{version}/usertoken/revoke.
func (c *Client) RevokeToken(ctx context.Context, req *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	out := &RevokeTokenResponse{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "DELETE",
		Path:   "/public/v{version}/usertoken/revoke",
		Req:    req,
		Out:    out,
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
