package genlib

// Templates for the generated files. Imports are added by the renderer
// based on what the rendered body actually references.

const fileHeaderTmpl = `// Code generated by connector-gen. DO NOT EDIT.

package {{.Package}}
`

const typesTmpl = `
{{- range .Models}}
// {{.Name}} is the {{.Doc}} model.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}
{{end}}`

const opsTmpl = `
{{- range .Ops}}
// {{.MethodName}}Request holds the parameters for {{.MethodName}}.
type {{.MethodName}}Request struct {
{{- range .Request.Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}

{{if .RespAlias -}}
// {{.MethodName}}Response is the response type of {{.MethodName}}.
type {{.MethodName}}Response = {{.RespAlias}}
{{else if not .HasOut -}}
// {{.MethodName}}Response is the (empty) response type of {{.MethodName}}.
type {{.MethodName}}Response struct{}
{{end -}}
// {{.MethodName}} calls {{.HTTPMethod}} {{.Path}}.
func (c *Client) {{.MethodName}}(ctx context.Context, req *{{.MethodName}}Request) (*{{.MethodName}}Response, error) {
	if req == nil {
		req = &{{.MethodName}}Request{}
	}
	out := &{{.MethodName}}Response{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "{{.HTTPMethod}}",
		Path:   "{{.Path}}",
		Req:    req,
{{- if .BodyExpr}}
		Body:   {{.BodyExpr}},
{{- end}}
{{- if .HasOut}}
		Out:    out,
{{- end}}
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
{{end}}`

// agentsTmpl generates AGENTS.md: an agent-facing capability guide for one
// connector. Handwritten content (title, description, notes) comes from
// gen.yaml; the operation catalog is derived from the spec.
const agentsTmpl = `<!-- Code generated by connector-gen. DO NOT EDIT.
     Edit gen.yaml (title / description / agent_notes) and run make gen. -->

# {{.Title}}

{{.Description}}

{{.Notes}}

## Capability catalog ({{.Total}} operations)

Every operation below is a method on ` + "`*{{.Package}}.Client`" + ` with the
uniform signature:

` + "```go" + `
func (c *Client) Xxx(ctx context.Context, req *XxxRequest) (*XxxResponse, error)
` + "```" + `

The request struct carries every input of the HTTP call: path params, query
params, and the request body (flattened into the struct). Optional fields
are pointers (use ` + "`connector.Ptr(v)`" + `); slice fields repeat the query key.
Field-level details for an operation live in the ` + "`<tag>_gen.go`" + ` file next
to this document (search for ` + "`XxxRequest`" + `); shared model types are in
` + "`types_gen.go`" + `.

Anything not listed here is outside this connector's capability boundary.
{{range .Groups}}
### {{.Tag}}
{{range .Ops}}
- ` + "`{{.MethodName}}`" + ` — ` + "`{{.HTTPMethod}} {{.DocPath}}`" + `{{end}}
{{end}}`

// roundtripTmpl generates one table-driven round-trip test per operation
// against an httptest stub. The client-construction expression comes from
// gen.yaml's test_new_client (default: NewClient(&Config{BaseURL: srv.URL})).
const roundtripTmpl = `
type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
{{- range .Ops}}
	{
		name:   "{{.MethodName}}",
		method: "{{.HTTPMethod}}",
		path:   "{{.TestPath}}",
		resp:   {{printf "%q" .RespBodyLit}},
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.{{.MethodName}}(ctx, &{{.MethodName}}Request{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.{{.MethodName}}(ctx, nil)
		},
	},
{{- end}}
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
`
