package genlib

// Templates for the generated files. Imports are added by the renderer
// based on what the rendered body actually references.

const fileHeaderTmpl = `// Code generated by connector-gen. DO NOT EDIT.

package {{.Package}}
`

const typesTmpl = `
{{- range .Models}}
// {{.Name}} is the {{.Doc}} model.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}
{{end}}`

const opsTmpl = `
{{- range .Ops}}
// {{.MethodName}}Request holds the parameters for {{.MethodName}}.
type {{.MethodName}}Request struct {
{{- range .Request.Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}

{{if .RespAlias -}}
// {{.MethodName}}Response is the response type of {{.MethodName}}.
type {{.MethodName}}Response = {{.RespAlias}}
{{else if not .HasOut -}}
// {{.MethodName}}Response is the (empty) response type of {{.MethodName}}.
type {{.MethodName}}Response struct{}
{{end -}}
// {{.MethodName}} calls {{.HTTPMethod}} {{.Path}}.
func (c *Client) {{.MethodName}}(ctx context.Context, req *{{.MethodName}}Request) (*{{.MethodName}}Response, error) {
	out := &{{.MethodName}}Response{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "{{.HTTPMethod}}",
		Path:   "{{.Path}}",
		Req:    req,
{{- if .BodyExpr}}
		Body:   {{.BodyExpr}},
{{- end}}
{{- if .HasOut}}
		Out:    out,
{{- end}}
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
{{end}}`

// roundtripTmpl generates one table-driven round-trip test per operation
// against an httptest stub. It assumes the handwritten layer provides
// NewClient(&Config{APIKey, SiteID, BaseURL}) (*Client, error); a connector
// with a different constructor would need a config override for this
// template.
const roundtripTmpl = `
type roundtripCase struct {
	name   string
	method string
	path   string
	resp   string
	invoke func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
{{- range .Ops}}
	{
		name:   "{{.MethodName}}",
		method: "{{.HTTPMethod}}",
		path:   "{{.TestPath}}",
		resp:   {{printf "%q" .RespBodyLit}},
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.{{.MethodName}}(ctx, &{{.MethodName}}Request{})
		},
	},
{{- end}}
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := NewClient(&Config{APIKey: "k", SiteID: "-99", BaseURL: srv.URL})
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}
`
