package genlib

// Templates for the generated files. Imports are added by the renderer
// based on what the rendered body actually references.

const fileHeaderTmpl = `// Code generated by connector-gen. DO NOT EDIT.

package {{.Package}}
`

const typesTmpl = `
{{- range .Models}}
// {{.Name}} is the {{.Doc}} model.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}
{{end}}`

const opsTmpl = `
{{- range .Ops}}
// {{.MethodName}}Request holds the parameters for {{.MethodName}}.
type {{.MethodName}}Request struct {
{{- range .Request.Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `
{{- end}}
}

{{if .RespAlias -}}
// {{.MethodName}}Response is the response type of {{.MethodName}}.
type {{.MethodName}}Response = {{.RespAlias}}
{{else if not .HasOut -}}
// {{.MethodName}}Response is the (empty) response type of {{.MethodName}}.
type {{.MethodName}}Response struct{}
{{end -}}
// {{.MethodName}} calls {{.HTTPMethod}} {{.Path}}.
func (c *Client) {{.MethodName}}(ctx context.Context, req *{{.MethodName}}Request) (*{{.MethodName}}Response, error) {
	if req == nil {
		req = &{{.MethodName}}Request{}
	}
	out := &{{.MethodName}}Response{}
	err := c.core.Do(ctx, &connector.Call{
		Method: "{{.HTTPMethod}}",
		Path:   "{{.Path}}",
		Req:    req,
{{- if .BodyExpr}}
		Body:   {{.BodyExpr}},
{{- end}}
{{- if .HasOut}}
		Out:    out,
{{- end}}
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}
{{end}}`

const actionsTmpl = `
var connectorActionManifest = [...]connector.ActionDescriptor{
{{- range .Ops}}
	{
		Provider:      "{{$.Package}}",
		Method:        "{{.MethodName}}",
		HTTPMethod:    "{{.HTTPMethod}}",
		RequestType:   "{{.Request.Name}}",
		ResponseType:  "{{.MethodName}}Response",
		RequiredScope: "{{.RequiredScope}}",
		Idempotency:   connector.ActionIdempotency("{{.Idempotency}}"),
	},
{{- end}}
}

// ConnectorActions returns the deterministic action manifest for this provider.
func ConnectorActions() []connector.ActionDescriptor {
	return append([]connector.ActionDescriptor(nil), connectorActionManifest[:]...)
}

type connectorActionHandler func(context.Context, *Client, json.RawMessage) (json.RawMessage, error)

var connectorActionHandlers = map[string]connectorActionHandler{
{{- range .Ops}}
	"{{.MethodName}}": invoke{{.MethodName}}Action,
{{- end}}
}

// InvokeAction validates and invokes one generated connector action.
func (c *Client) InvokeAction(ctx context.Context, call connector.ActionCall) (json.RawMessage, error) {
	if call.Provider != "{{.Package}}" {
		return nil, &connector.UnknownProviderError{Provider: call.Provider}
	}
	handler, ok := connectorActionHandlers[call.Method]
	if !ok {
		return nil, &connector.UnknownActionError{Provider: call.Provider, Method: call.Method}
	}
	return handler(ctx, c, call.Request)
}
{{range .Ops}}
func invoke{{.MethodName}}Action(ctx context.Context, c *Client, input json.RawMessage) (json.RawMessage, error) {
	var wire struct {
{{- range .Request.Fields}}
		{{.Name}} {{.Type}} ` + "`{{.ActionTag}}`" + `
{{- end}}
	}
	if err := connector.DecodeActionRequest("{{$.Package}}", "{{.MethodName}}", input, &wire); err != nil {
		return nil, err
	}
	out, err := c.{{.MethodName}}(ctx, &{{.MethodName}}Request{
{{- range .Request.Fields}}
		{{.Name}}: wire.{{.Name}},
{{- end}}
	})
	if err != nil {
		return nil, err
	}
	return json.Marshal(out)
}
{{end}}`

// agentsTmpl generates AGENTS.md: an agent-facing capability guide for one
// connector. Handwritten content (title, description, notes) comes from
// gen.yaml; the operation catalog is derived from the spec.
const agentsTmpl = `<!-- Code generated by connector-gen. DO NOT EDIT.
     Edit gen.yaml (title / description / agent_notes) and run make gen. -->

# {{.Title}}

{{.Description}}

{{.Notes}}

## Capability catalog ({{.Total}} operations)

Every operation below is a method on ` + "`*{{.Package}}.Client`" + ` with the
uniform signature:

` + "```go" + `
func (c *Client) Xxx(ctx context.Context, req *XxxRequest) (*XxxResponse, error)
` + "```" + `

The request struct carries every input of the HTTP call: path params, query
params, and the request body (flattened into the struct). Optional fields
are pointers (use ` + "`connector.Ptr(v)`" + `); slice fields repeat the query key.
Field-level details for an operation live in the ` + "`<tag>_gen.go`" + ` file next
to this document (search for ` + "`XxxRequest`" + `); shared model types are in
` + "`types_gen.go`" + `.

### Client options (all connectors)

` + "`NewClient(cfg, opts...)`" + ` accepts shared options from the root
` + "`connector`" + ` package:

- ` + "`connector.WithTimeout(d)`" + ` — overall per-call deadline (covers retries).
- ` + "`connector.WithRetry(connector.RetryPolicy{})`" + ` — opt-in automatic
  retries with exponential backoff honoring ` + "`Retry-After`" + `. Defaults:
  3 attempts, statuses 429/502/503/504; non-idempotent methods (POST) are
  retried only on 429 unless ` + "`RetryNonIdempotent`" + ` is set.
- ` + "`connector.WithHTTPClient(hc)`" + ` — custom ` + "`*http.Client`" + `.

### Error handling (all connectors)

Every non-2xx response is a ` + "`*connector.APIError`" + ` (StatusCode, service
Code/Message, raw Body, and the server's ` + "`RetryAfter`" + ` hint). Classify
without unwrapping via ` + "`connector.IsRateLimited(err)`" + ` (429),
` + "`IsUnauthorized`" + ` (401), ` + "`IsForbidden`" + ` (403), ` + "`IsNotFound`" + ` (404),
` + "`IsServerError`" + ` (5xx), ` + "`IsRetryable`" + ` (429/502/503/504), or use
` + "`connector.AsAPIError(err)`" + ` / ` + "`connector.StatusCode(err)`" + `.

Anything not listed here is outside this connector's capability boundary.
{{range .Groups}}
### {{.Tag}}
{{range .Ops}}
- ` + "`{{.MethodName}}`" + ` — ` + "`{{.HTTPMethod}} {{.DocPath}}`" + `{{end}}
{{end}}`

// roundtripTmpl generates one table-driven round-trip test per operation
// against an httptest stub. The client-construction expression comes from
// gen.yaml's test_new_client (default: NewClient(&Config{BaseURL: srv.URL})).
const roundtripTmpl = `
type roundtripCase struct {
	name      string
	method    string
	path      string
	resp      string
	invoke    func(ctx context.Context, c *Client) (any, error)
	invokeNil func(ctx context.Context, c *Client) (any, error)
}

var roundtripCases = []roundtripCase{
{{- range .Ops}}
	{
		name:   "{{.MethodName}}",
		method: "{{.HTTPMethod}}",
		path:   "{{.TestPath}}",
		resp:   {{printf "%q" .RespBodyLit}},
		invoke: func(ctx context.Context, c *Client) (any, error) {
			return c.{{.MethodName}}(ctx, &{{.MethodName}}Request{})
		},
		invokeNil: func(ctx context.Context, c *Client) (any, error) {
			return c.{{.MethodName}}(ctx, nil)
		},
	},
{{- end}}
}

func TestGeneratedRoundtrips(t *testing.T) {
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invoke(context.Background(), c)
			if err != nil {
				t.Fatal(err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method {
				t.Errorf("method = %q, want %q", gotMethod, tc.method)
			}
			if gotPath != tc.path {
				t.Errorf("path = %q, want %q", gotPath, tc.path)
			}
		})
	}
}

// TestGeneratedNilRequests verifies every method tolerates a nil request
// without panicking (path params fall back to their zero values).
func TestGeneratedNilRequests(t *testing.T) {
	var mu sync.Mutex
	var nextResp string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		if nextResp == "" {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		_, _ = w.Write([]byte(nextResp))
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := tc.invokeNil(context.Background(), c)
			if err != nil {
				t.Fatalf("nil request: %v", err)
			}
			if out == nil {
				t.Fatal("nil response")
			}
		})
	}
}
`

const actionsTestTmpl = `
func TestGeneratedActionManifest(t *testing.T) {
	actions := ConnectorActions()
	if len(actions) != len(roundtripCases) {
		t.Fatalf("manifest entries = %d, operations = %d", len(actions), len(roundtripCases))
	}
	seen := make(map[string]bool, len(actions))
	for _, action := range actions {
		if action.Provider != "{{.Package}}" {
			t.Errorf("provider = %q", action.Provider)
		}
		if action.Method == "" || action.HTTPMethod == "" || action.RequestType == "" || action.ResponseType == "" || action.RequiredScope == "" || action.Idempotency == "" {
			t.Errorf("incomplete descriptor: %+v", action)
		}
		if seen[action.Method] {
			t.Errorf("duplicate action %q", action.Method)
		}
		seen[action.Method] = true
	}
	if len(actions) > 0 {
		actions[0].Method = "mutated"
		if ConnectorActions()[0].Method == "mutated" {
			t.Fatal("ConnectorActions exposed mutable manifest storage")
		}
	}
}

func TestGeneratedActionDispatch(t *testing.T) {
	actions := ConnectorActions()
	var mu sync.Mutex
	var gotMethod, gotPath, nextResp string
	var nextStatus int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		gotMethod, gotPath = r.Method, r.URL.Path
		if nextStatus != 0 {
			w.WriteHeader(nextStatus)
			nextStatus = 0
		}
		if nextResp != "" {
			_, _ = w.Write([]byte(nextResp))
		}
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}

	for i, tc := range roundtripCases {
		t.Run(tc.name, func(t *testing.T) {
			action := actions[i]
			if action.Method != tc.name {
				t.Fatalf("manifest method = %q, operation = %q", action.Method, tc.name)
			}
			mu.Lock()
			nextResp = tc.resp
			mu.Unlock()
			out, err := c.InvokeAction(context.Background(), connector.ActionCall{
				Provider: action.Provider,
				Method:   action.Method,
				Request:  json.RawMessage(` + "`{}`" + `),
			})
			if err != nil {
				t.Fatal(err)
			}
			if !json.Valid(out) {
				t.Fatalf("invalid JSON response: %s", out)
			}
			mu.Lock()
			defer mu.Unlock()
			if gotMethod != tc.method || gotPath != tc.path {
				t.Errorf("request = %s %s, want %s %s", gotMethod, gotPath, tc.method, tc.path)
			}
		})
	}
}

func TestGeneratedActionDispatchErrors(t *testing.T) {
	if len(roundtripCases) == 0 {
		t.Skip("connector has no actions")
	}
	var mu sync.Mutex
	nextStatus := http.StatusOK
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		defer mu.Unlock()
		w.WriteHeader(nextStatus)
		_, _ = w.Write([]byte(roundtripCases[0].resp))
	}))
	defer srv.Close()
	c, err := {{.TestNewClient}}
	if err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	first := roundtripCases[0]

	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "wrong", Method: first.name})
	var providerErr *connector.UnknownProviderError
	if !errors.As(err, &providerErr) {
		t.Fatalf("wrong provider error = %T, want *connector.UnknownProviderError", err)
	}

	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "{{.Package}}", Method: "Missing"})
	var actionErr *connector.UnknownActionError
	if !errors.As(err, &actionErr) {
		t.Fatalf("unknown method error = %T, want *connector.UnknownActionError", err)
	}

	_, err = c.InvokeAction(ctx, connector.ActionCall{
		Provider: "{{.Package}}",
		Method:   first.name,
		Request:  json.RawMessage(` + "`{`" + `),
	})
	var requestErr *connector.InvalidActionRequestError
	if !errors.As(err, &requestErr) {
		t.Fatalf("malformed request error = %T, want *connector.InvalidActionRequestError", err)
	}

	mu.Lock()
	nextStatus = http.StatusTooManyRequests
	mu.Unlock()
	_, err = c.InvokeAction(ctx, connector.ActionCall{Provider: "{{.Package}}", Method: first.name})
	if _, ok := connector.AsAPIError(err); !ok {
		t.Fatalf("provider error = %T, want *connector.APIError", err)
	}
}
`
